import type { ExamQuestion } from "@/lib/ccma/exams/types";

function q(
  id: string,
  domainSlug: string,
  domainTitle: string,
  type: "knowledge" | "scenario",
  difficulty: 1 | 2 | 3,
  prompt: string,
  a: string,
  b: string,
  c: string,
  d: string,
  correct: "A" | "B" | "C" | "D",
  rationale: string,
  memoryTip: string,
): ExamQuestion {
  return {
    id,
    domainSlug,
    domainTitle,
    prompt,
    type,
    choices: [
      { id: "A", label: "A", text: a },
      { id: "B", label: "B", text: b },
      { id: "C", label: "C", text: c },
      { id: "D", label: "D", text: d },
    ],
    correctChoiceId: correct,
    rationale,
    memoryTip,
    difficulty,
  };
}

// ── Domain 1: Clinical Patient Care ──────────────────────────────────────────

const CPC = "clinical-patient-care";
const CPC_TITLE = "Clinical Patient Care";

const clinicalPatientCare: ExamQuestion[] = [
  q("cpc-001", CPC, CPC_TITLE, "knowledge", 1,
    "What is the normal resting oral temperature for an adult?",
    "96.8°F (36.0°C)", "98.6°F (37.0°C)", "100.4°F (38.0°C)", "99.0°F (37.2°C)",
    "B",
    "Normal adult oral temperature is 98.6°F (37.0°C). Temperatures above 100.4°F are generally considered fever.",
    "Think 98.6 = standard. One degree higher = fever territory."),

  q("cpc-002", CPC, CPC_TITLE, "knowledge", 1,
    "What is the normal resting pulse rate range for an adult?",
    "40–60 bpm", "60–100 bpm", "100–120 bpm", "50–90 bpm",
    "B",
    "The normal adult resting heart rate is 60–100 beats per minute. Below 60 is bradycardia; above 100 is tachycardia.",
    "60 to 100 — anything outside this range, report it."),

  q("cpc-003", CPC, CPC_TITLE, "knowledge", 1,
    "What is the normal respiratory rate range for an adult at rest?",
    "8–12 breaths/min", "12–20 breaths/min", "20–30 breaths/min", "6–10 breaths/min",
    "B",
    "Normal adult respiratory rate is 12–20 breaths per minute. Count for a full 30 seconds × 2 without alerting the patient.",
    "12 to 20 — less than 12 or more than 20 needs reporting."),

  q("cpc-004", CPC, CPC_TITLE, "knowledge", 1,
    "Which blood pressure reading is considered normal for an adult?",
    "140/90 mmHg", "120/80 mmHg", "130/85 mmHg", "150/95 mmHg",
    "B",
    "Normal adult BP is less than 120/80 mmHg (AHA guidelines). Values 120–129 systolic are elevated; ≥130 is Stage 1 hypertension.",
    "120/80 = normal. Higher numbers = more risk."),

  q("cpc-005", CPC, CPC_TITLE, "knowledge", 1,
    "What is the normal oxygen saturation (SpO2) range for a healthy adult?",
    "85–90%", "90–94%", "95–100%", "80–95%",
    "C",
    "Normal SpO2 is 95–100%. Values below 90% indicate hypoxemia requiring immediate clinical evaluation.",
    "95–100% is the green zone. Below 90% = call for help."),

  q("cpc-006", CPC, CPC_TITLE, "knowledge", 1,
    "The six rights of medication administration include the right patient, right medication, right dose, right route, right time, and:",
    "Right documentation", "Right prescription", "Right temperature", "Right pharmacy",
    "A",
    "The sixth right is right documentation. Always record the medication immediately after administration, not before.",
    "Six rights: patient, med, dose, route, time, DOCUMENTATION."),

  q("cpc-007", CPC, CPC_TITLE, "knowledge", 1,
    "According to standard precautions, when must a medical assistant perform hand hygiene?",
    "Only after removing gloves", "Before and after every patient contact", "Only when hands are visibly soiled", "Before entering the exam room only",
    "B",
    "Standard precautions require hand hygiene before and after every patient contact, regardless of glove use. Gloves are not a substitute for hand hygiene.",
    "Before AND after — not just one or the other."),

  q("cpc-008", CPC, CPC_TITLE, "knowledge", 2,
    "A rectal temperature reading is generally how much higher than an oral reading?",
    "0.5°F higher", "1.0°F higher", "1.5°F higher", "2.0°F higher",
    "B",
    "Rectal temperature is approximately 1°F higher than oral. Axillary readings are about 1°F lower than oral.",
    "Rectal = oral + 1°F. Axillary = oral − 1°F."),

  q("cpc-009", CPC, CPC_TITLE, "knowledge", 1,
    "Where is the apical pulse most accurately auscultated?",
    "Right sternal border, 2nd intercostal space", "Left midclavicular line, 5th intercostal space", "Right midclavicular line, 4th intercostal space", "Epigastric region",
    "B",
    "The apical pulse is heard at the apex of the heart — left midclavicular line, 5th intercostal space (PMI). Count for a full minute.",
    "Fifth space, left side, midclavicular line = apex."),

  q("cpc-010", CPC, CPC_TITLE, "knowledge", 2,
    "Which technique is used when collecting a urine specimen for culture and sensitivity?",
    "First-void morning sample", "Clean-catch midstream", "Catheterized specimen only", "Any random sample in a sterile cup",
    "B",
    "A clean-catch midstream sample is the standard non-invasive collection method for culture. The patient cleans the meatus, voids briefly, then collects mid-stream.",
    "Clean-catch midstream: clean first, catch in the middle."),

  q("cpc-011", CPC, CPC_TITLE, "knowledge", 1,
    "What is the primary venipuncture site in adults?",
    "Radial artery", "Antecubital fossa (median cubital vein)", "Femoral vein", "External jugular vein",
    "B",
    "The median cubital vein in the antecubital fossa is the preferred site — accessible, relatively stationary, and well-supported by tissue.",
    "Antecubital fossa, median cubital vein = first choice."),

  q("cpc-012", CPC, CPC_TITLE, "knowledge", 1,
    "What does the abbreviation 'NPO' mean?",
    "Normal pulse oximetry", "Nothing by mouth", "No prescribed orders", "Normal postoperative",
    "B",
    "NPO stands for 'nil per os' (Latin: nothing by mouth). Patients are placed on NPO status before procedures requiring sedation or anesthesia.",
    "NPO = nothing by mouth. Latin: nil per os."),

  q("cpc-013", CPC, CPC_TITLE, "knowledge", 2,
    "Which infection control practice directly breaks the chain of infection at the 'means of transmission' link?",
    "Administering vaccines", "Using proper hand hygiene and PPE", "Isolating susceptible hosts", "Treating the source",
    "B",
    "Hand hygiene and PPE interrupt transmission — the path pathogens travel between host and reservoir. Vaccines address susceptibility; isolation addresses the host.",
    "Transmission link = how it travels. Break it with handwashing and PPE."),

  q("cpc-014", CPC, CPC_TITLE, "knowledge", 2,
    "When donning PPE, what is the correct order?",
    "Gloves, gown, mask, goggles", "Gown, mask/respirator, goggles/face shield, gloves", "Mask, gown, gloves, goggles", "Goggles, gloves, gown, mask",
    "B",
    "The CDC-recommended donning order is: gown → mask/respirator → goggles/face shield → gloves. Gloves go on last to keep the hands from contaminating other equipment.",
    "Don: Gown, Mask, Goggles, Gloves (G-M-G-G)."),

  q("cpc-015", CPC, CPC_TITLE, "knowledge", 2,
    "What is the normal fasting blood glucose range for a non-diabetic adult?",
    "60–80 mg/dL", "70–99 mg/dL", "100–125 mg/dL", "126–140 mg/dL",
    "B",
    "Normal fasting glucose is 70–99 mg/dL. Values of 100–125 indicate prediabetes; ≥126 mg/dL on two occasions confirms diabetes.",
    "70–99 fasting = normal. 100–125 = pre. 126+ = diabetes."),

  q("cpc-016", CPC, CPC_TITLE, "knowledge", 2,
    "Which action most effectively prevents transmission of bloodborne pathogens?",
    "Wearing a gown at all times", "Using needless systems and safety-engineered sharps", "Double-gloving for all procedures", "Disinfecting all surfaces every hour",
    "B",
    "OSHA's Bloodborne Pathogen Standard requires engineering controls — safety-engineered devices reduce the source of exposure. PPE is secondary protection.",
    "Engineering controls first, PPE second."),

  q("cpc-017", CPC, CPC_TITLE, "knowledge", 2,
    "When preparing a patient for a fasting blood draw, the MA should confirm the patient has fasted for at least:",
    "4 hours", "8–12 hours", "24 hours", "2 hours",
    "B",
    "An 8–12 hour fast is standard for fasting lipid panels and glucose tests. Water is generally permitted.",
    "8–12 hours fasting. Water OK. Coffee is not."),

  q("cpc-018", CPC, CPC_TITLE, "scenario", 2,
    "A patient's blood pressure reads 188/112 mmHg. The medical assistant should:",
    "Recheck in the other arm and document both readings", "Immediately report the finding to the provider", "Ask the patient to rest 5 minutes and recheck before notifying anyone", "Document the reading and proceed with the visit",
    "B",
    "A BP of 188/112 is hypertensive crisis range (>180/120). The MA must notify the provider immediately. Do not wait; delay in treatment could be dangerous.",
    "Hypertensive crisis: >180/120. Notify immediately — don't recheck first."),

  q("cpc-019", CPC, CPC_TITLE, "scenario", 2,
    "While taking a patient's vital signs, the patient suddenly reports crushing chest pain radiating to the left arm. The medical assistant's first action should be:",
    "Finish taking the remaining vital signs, then notify the provider", "Call 911 and notify the provider immediately", "Offer the patient water and ask them to lie down", "Check oxygen saturation and wait to see if pain resolves",
    "B",
    "Crushing chest pain with radiation to the left arm is a classic MI presentation. This is a medical emergency. Call 911 and notify the provider simultaneously.",
    "Chest pain + left arm radiation = possible MI. Call 911 first."),

  q("cpc-020", CPC, CPC_TITLE, "scenario", 2,
    "After drawing blood, the MA sustains a needlestick injury. What is the first action?",
    "Immediately apply a tourniquet above the puncture site", "Wash the area thoroughly with soap and water", "Apply pressure to stop the bleeding", "Document the injury and continue with the next patient",
    "B",
    "OSHA requires the site be washed with soap and water immediately. Then report to a supervisor, complete an exposure incident report, and follow the facility's post-exposure protocol.",
    "Needlestick: wash first, then report. Never squeeze or suck."),

  q("cpc-021", CPC, CPC_TITLE, "scenario", 2,
    "A patient scheduled for a procedure mentions a latex allergy. The medical assistant should:",
    "Proceed normally since most gloves are latex-free today", "Alert the provider and switch to latex-free supplies before the patient enters the room", "Document the allergy and provide antihistamines prophylactically", "Postpone the procedure until the allergy can be verified",
    "B",
    "Latex allergy requires a latex-safe environment before the patient enters. Alert the care team and replace all latex-containing items proactively.",
    "Latex allergy: act before the patient enters. Prep the room first."),

  q("cpc-022", CPC, CPC_TITLE, "scenario", 2,
    "During a sterile procedure setup, the MA's sleeve brushes the sterile field. The correct response is:",
    "Continue the procedure since only the gloves touch the patient", "Consider the entire sterile field contaminated and set up a new one", "Remove the item that was touched and continue", "Apply additional sterile draping over the contaminated area",
    "B",
    "Any contact with the sterile field from a non-sterile source contaminates the entire field. A new sterile field must be set up before the procedure continues.",
    "Sterile field: if in doubt, it's contaminated. Start over."),

  q("cpc-023", CPC, CPC_TITLE, "scenario", 2,
    "A patient refuses to take a prescribed medication. The medical assistant should:",
    "Administer the medication anyway since the provider ordered it", "Document the refusal and inform the provider", "Explain the importance of the medication and administer if the patient agrees", "Discharge the patient for non-compliance",
    "B",
    "Patients have the right to refuse treatment. The MA must document the refusal completely, notify the provider, and not administer without consent.",
    "Patient refusal = document + notify provider. Never force."),

  q("cpc-024", CPC, CPC_TITLE, "scenario", 3,
    "When counting an apical pulse, the MA notices the rhythm is irregular with occasional missed beats. The correct action is:",
    "Count for 30 seconds and multiply by 2 for efficiency", "Count for a full 60 seconds and report the irregular rhythm to the provider", "Recheck the radial pulse to confirm", "Document the finding as normal variation",
    "B",
    "An irregular apical pulse must be counted for a full minute. Any dysrhythmia — missed beats, irregular intervals — must be reported to the provider. Do not shortcut to 30 seconds.",
    "Irregular pulse: always count a full 60 seconds, then report."),

  q("cpc-025", CPC, CPC_TITLE, "scenario", 2,
    "During venipuncture, the patient becomes pale, diaphoretic, and unresponsive. The medical assistant should:",
    "Immediately remove the needle, lower the patient's head, and call for help", "Finish the draw quickly before the patient fully loses consciousness", "Apply smelling salts and continue the procedure", "Ask the patient to breathe deeply and keep the needle in place",
    "B",
    "Vasovagal syncope requires immediate needle removal to prevent injury, followed by positioning (supine, legs elevated) and calling for assistance. Never leave the patient alone.",
    "Syncope during draw: remove needle, lower head, call for help."),
];

// ── Domain 2: Patient Care Coordination and Education ──────────────────────

const PCCE = "patient-care-coordination-and-education";
const PCCE_TITLE = "Patient Care Coordination and Education";

const patientCareCoordination: ExamQuestion[] = [
  q("pcc-001", PCCE, PCCE_TITLE, "knowledge", 1,
    "What is the teach-back method?",
    "Teaching a skill by demonstrating it three times", "Asking patients to restate instructions in their own words to confirm understanding", "Reading discharge instructions aloud to the patient", "Providing written materials to take home",
    "B",
    "Teach-back confirms understanding — the patient explains back what they were taught. It identifies gaps before the patient leaves the office.",
    "Teach-back = patient explains it back to you, not the other way."),

  q("pcc-002", PCCE, PCCE_TITLE, "knowledge", 1,
    "Health literacy is best defined as:",
    "A patient's ability to pay for healthcare", "The capacity to obtain, process, and understand basic health information to make decisions", "A provider's skill in explaining diagnoses", "The number of health-related books a patient has read",
    "B",
    "Health literacy is the patient's ability to navigate the healthcare system, understand instructions, and act on health information — regardless of education level.",
    "Health literacy = can the patient understand AND use health info?"),

  q("pcc-003", PCCE, PCCE_TITLE, "knowledge", 2,
    "Which professional typically initiates a referral to a specialist?",
    "The medical assistant", "The referring physician or provider", "The specialist's office", "The patient's insurance company",
    "B",
    "Referrals originate from the treating provider. The MA assists by gathering information, completing forms, and coordinating scheduling — but does not initiate the referral independently.",
    "Provider initiates referrals. MA coordinates logistics."),

  q("pcc-004", PCCE, PCCE_TITLE, "knowledge", 1,
    "What is the medical assistant's primary role in chronic disease management?",
    "Diagnosing comorbidities", "Supporting adherence through education, monitoring, and care coordination", "Prescribing medications for chronic conditions", "Determining the care plan independently",
    "B",
    "CMAs support chronic disease management by educating patients, tracking adherence, reinforcing provider instructions, and flagging concerns. Diagnosis and prescribing are outside scope.",
    "CMA role in chronic disease: educate, monitor, coordinate, flag."),

  q("pcc-005", PCCE, PCCE_TITLE, "knowledge", 2,
    "An advance directive is a document that:",
    "Authorizes a provider to perform emergency procedures without consent", "Specifies a patient's healthcare wishes if they become unable to communicate", "Releases a provider from liability", "Gives a family member billing authority",
    "B",
    "An advance directive (living will, healthcare proxy) documents a patient's preferences for end-of-life care. Providers are required to ask about it at admission.",
    "Advance directive = patient's voice when they can't speak."),

  q("pcc-006", PCCE, PCCE_TITLE, "knowledge", 1,
    "According to current guidelines, colorectal cancer screening should begin at age:",
    "40", "45", "50", "60",
    "B",
    "The USPSTF and ACS updated colorectal cancer screening to begin at age 45 for average-risk adults. Previous guidance started at 50.",
    "Colorectal screening: starts at 45 now, not 50."),

  q("pcc-007", PCCE, PCCE_TITLE, "knowledge", 2,
    "A patient portal primarily serves which function?",
    "Allowing staff to schedule appointments without patient contact", "Enabling patients to access records, request refills, and communicate with the care team", "Processing insurance claims electronically", "Replacing in-person visits with virtual care",
    "B",
    "Patient portals are secure online tools giving patients access to their health records, lab results, appointment scheduling, and messaging — improving engagement and adherence.",
    "Portal = patient self-service hub: records, messages, refills."),

  q("pcc-008", PCCE, PCCE_TITLE, "knowledge", 2,
    "Social determinants of health include all EXCEPT:",
    "Housing stability", "Genetic predisposition to disease", "Access to nutritious food", "Transportation to medical appointments",
    "B",
    "Social determinants are non-medical factors — where people live, work, learn, and play. Genetics is a biological determinant, not a social one.",
    "SDOH = environment + society. Genes are NOT a social determinant."),

  q("pcc-009", PCCE, PCCE_TITLE, "knowledge", 2,
    "Which approach is used in motivational interviewing to support behavior change?",
    "Telling patients what they must do to improve health", "Asking open-ended questions and reflecting patient ambivalence to build motivation", "Providing written instructions and expecting compliance", "Scheduling more frequent appointments",
    "B",
    "Motivational interviewing uses open-ended questions, affirmations, reflective listening, and summarizing to evoke a patient's own motivation for change rather than imposing direction.",
    "MI: guide, don't tell. Evoke the patient's own reasons."),

  q("pcc-010", PCCE, PCCE_TITLE, "knowledge", 1,
    "The medical assistant should document patient education in the chart to:",
    "Avoid liability for any poor patient outcomes", "Create a legal record and enable care continuity across the team", "Satisfy insurance billing requirements only", "Meet HIPAA documentation standards",
    "B",
    "Documenting education creates a legal record, supports care continuity, and allows the full care team to build on prior teaching. Include what was taught, method, and patient understanding.",
    "Document education: what, how, and did the patient understand?"),

  q("pcc-011", PCCE, PCCE_TITLE, "knowledge", 2,
    "Which patient education material is most appropriate for a patient with low health literacy?",
    "Detailed brochures with medical terminology", "Simple written materials with pictures at a 6th-grade reading level", "Medical textbook chapters explaining the condition", "Internet links to research studies",
    "B",
    "Low health literacy patients benefit from plain language, visuals, and short sentences. The average American reads at a 7th–8th grade level; health materials should target 6th grade.",
    "Low literacy: simple words, pictures, short sentences. Grade 6."),

  q("pcc-012", PCCE, PCCE_TITLE, "knowledge", 2,
    "What is the purpose of a care coordinator in a primary care practice?",
    "To perform clinical procedures alongside the physician", "To guide patients through the healthcare system, manage transitions, and reduce gaps in care", "To manage insurance billing for the practice", "To supervise all allied health staff",
    "B",
    "Care coordinators help patients navigate complex systems, follow up on referrals, manage chronic conditions, and prevent gaps between providers — especially at care transitions.",
    "Care coordinator = navigator who prevents patients from falling through the cracks."),

  q("pcc-013", PCCE, PCCE_TITLE, "knowledge", 1,
    "Informed consent means the patient:",
    "Signs a form acknowledging receipt of services", "Understands the procedure, benefits, risks, and alternatives before agreeing", "Agrees to pay for the services rendered", "Acknowledges the privacy notice",
    "B",
    "Informed consent requires the patient to understand the procedure, its risks, benefits, and alternatives. The provider obtains consent; the MA may witness and document.",
    "Informed consent = understand the what, why, risks, and alternatives."),

  q("pcc-014", PCCE, PCCE_TITLE, "knowledge", 2,
    "A preventive care reminder should be sent when:",
    "A patient misses a payment", "A patient is due for a screening or immunization based on age, sex, or risk factors", "The provider requests additional documentation", "A patient's insurance coverage changes",
    "B",
    "Preventive care reminders improve adherence to screening schedules (e.g., mammograms, colonoscopies, flu shots) and are a core care coordination function in the MA role.",
    "Preventive reminders: triggered by age, sex, risk — not billing."),

  q("pcc-015", PCCE, PCCE_TITLE, "knowledge", 1,
    "Cultural competence in healthcare means:",
    "Being fluent in the languages of all patients", "Providing care that respects and responds to patient cultural beliefs and communication needs", "Treating all patients exactly the same regardless of background", "Requiring patients to adapt to the clinic's standard processes",
    "B",
    "Cultural competence involves awareness, knowledge, and skill to work effectively across cultural differences. It improves trust, communication, and health outcomes.",
    "Cultural competence: meet the patient where they are."),

  q("pcc-016", PCCE, PCCE_TITLE, "knowledge", 2,
    "Which annual immunization is recommended for all adults age 6 months and older?",
    "Pneumococcal vaccine", "Influenza (flu) vaccine", "Shingles vaccine", "Hepatitis B vaccine",
    "B",
    "The CDC recommends annual flu vaccine for everyone 6 months and older. It is the only vaccine recommended on an annual schedule for the general adult population.",
    "Flu shot: annual for everyone 6 months+."),

  q("pcc-017", PCCE, PCCE_TITLE, "knowledge", 2,
    "A Patient-Centered Medical Home (PCMH) model emphasizes:",
    "Specialist-led fragmented care", "Team-based, coordinated care with the patient as an active partner", "Fee-for-service billing to maximize volume", "Reducing patient access to lower costs",
    "B",
    "PCMH is an approach where a primary care team provides comprehensive, coordinated care with the patient at the center. It improves outcomes and reduces costly emergency use.",
    "PCMH = team-based, coordinated, patient-centered primary care."),

  q("pcc-018", PCCE, PCCE_TITLE, "scenario", 2,
    "A diabetic patient admits to frequently skipping their insulin injections due to fear of needles. The most appropriate initial response from the medical assistant is:",
    "Tell the patient that skipping insulin is dangerous and they must comply", "Express empathy, ask open-ended questions about their concerns, and involve the provider", "Document the non-compliance and schedule a follow-up appointment", "Demonstrate the injection technique immediately to alleviate the fear",
    "B",
    "Non-adherence is best addressed with empathy and motivational interviewing before education or correction. Judging or lecturing the patient first breaks rapport.",
    "Non-adherence: empathy first, then explore, then educate."),

  q("pcc-019", PCCE, PCCE_TITLE, "scenario", 2,
    "After explaining discharge instructions, the patient says 'I understand.' The best follow-up by the medical assistant is:",
    "Accept the response and document 'patient verbalized understanding'", "Ask the patient to explain the key instructions back in their own words", "Provide written instructions and dismiss the patient", "Call the patient the next day to review",
    "B",
    "Teach-back confirms actual understanding — not just stated understanding. A patient saying 'I understand' doesn't confirm comprehension.",
    "Always use teach-back. 'I understand' is not enough."),

  q("pcc-020", PCCE, PCCE_TITLE, "scenario", 2,
    "A patient needs a cardiology referral but expresses concern about costs and transportation. The medical assistant should:",
    "Tell the patient the referral is mandatory and schedule it without discussion", "Acknowledge the barriers, document them, and connect the patient with social services or care coordinator", "Cancel the referral since the patient is unlikely to go", "Refer the patient to a closer cardiologist without consulting the provider",
    "B",
    "Social determinants like cost and transportation are real barriers to care. The MA should acknowledge them, document, and involve care coordination or social work resources.",
    "Identify barriers, document, connect to resources. Don't ignore them."),

  q("pcc-021", PCCE, PCCE_TITLE, "scenario", 2,
    "A patient who speaks no English arrives for an appointment. The medical assistant should:",
    "Use a family member present in the office to interpret", "Access a qualified medical interpreter service (in-person or telephonic)", "Attempt to communicate through gestures and proceed with the visit", "Reschedule the appointment for when an interpreter is available",
    "B",
    "Federal law (Title VI) requires meaningful access for limited English proficiency patients. Use a qualified medical interpreter. Family members are not appropriate — they may omit or alter information.",
    "LEP patients: qualified interpreter required. Family = not appropriate."),

  q("pcc-022", PCCE, PCCE_TITLE, "scenario", 2,
    "A patient who has missed three follow-up appointments calls to reschedule. The medical assistant should:",
    "Refuse to reschedule until the patient explains the missed appointments", "Schedule the appointment, document the pattern, and alert the provider", "Send a warning letter before scheduling", "Discharge the patient from the practice",
    "B",
    "Repeated missed appointments may signal barriers to care. Schedule the patient, document the pattern, and notify the provider so the care team can address underlying issues.",
    "Missed appointments: schedule + document + notify provider."),

  q("pcc-023", PCCE, PCCE_TITLE, "scenario", 2,
    "An elderly patient is hesitant to get the recommended shingles vaccine because they 'never get shots.' The medical assistant's best approach is:",
    "Document the refusal and move on", "Explain the benefits, acknowledge the preference, ask what concerns them, and share information without pressure", "Insist the patient receive the vaccine before leaving", "Tell the patient their provider will be angry if they skip it",
    "B",
    "Vaccine hesitancy is addressed with motivational communication: acknowledge concerns, provide accurate information, and respect autonomy. Coercion and dismissal are counterproductive.",
    "Hesitant patient: listen, inform, respect. Never pressure."),

  q("pcc-024", PCCE, PCCE_TITLE, "scenario", 2,
    "A patient asks about a health claim they saw on social media. The medical assistant should:",
    "Confirm the claim if it sounds reasonable", "Encourage the patient to discuss it with their provider and direct them to credible sources", "Tell the patient all social media health content is wrong", "Ignore the question since it is outside the MA's scope",
    "B",
    "MAs should not confirm or deny unverified health claims. Direct patients to their provider and to credible resources (CDC, NIH, AHA). Dismissing the question reduces trust.",
    "Social media claims: don't validate, don't dismiss — redirect to the provider."),

  q("pcc-025", PCCE, PCCE_TITLE, "scenario", 3,
    "A patient with poorly controlled hypertension has not filled their new prescription in two weeks. The medical assistant's best response after identifying this gap is:",
    "Note it in the chart and wait for the next scheduled visit", "Contact the patient, explore barriers, and notify the provider of the non-adherence", "Report the patient's non-compliance to their insurer", "Assume the patient is seeing another provider",
    "B",
    "Medication non-adherence is a critical gap. The MA should proactively reach out, explore why (cost, side effects, access), document findings, and loop in the provider.",
    "Non-adherence gap: call the patient, explore why, tell the provider."),
];

// ── Domain 3: Administrative Assisting ───────────────────────────────────────

const AA = "administrative-assisting";
const AA_TITLE = "Administrative Assisting";

const administrativeAssisting: ExamQuestion[] = [
  q("aa-001", AA, AA_TITLE, "knowledge", 1,
    "HIPAA's minimum necessary standard requires that:",
    "All patient information be shared among the entire care team", "Only the information necessary to accomplish the intended purpose be disclosed", "Patients receive a copy of all their records at every visit", "Staff memorize patient PHI to avoid written disclosures",
    "B",
    "The minimum necessary standard limits PHI disclosure to what is needed for the specific purpose. It prevents over-sharing even within covered entities.",
    "Minimum necessary: share only what's needed. Nothing extra."),

  q("aa-002", AA, AA_TITLE, "knowledge", 1,
    "Which of the following is NOT considered Protected Health Information (PHI) under HIPAA?",
    "Social Security number linked to a diagnosis", "De-identified statistical health data", "Medical record numbers", "Date of service combined with a patient name",
    "B",
    "De-identified data — with all 18 identifiers removed — is not PHI under HIPAA. Statistical data without any identifier does not fall under HIPAA protections.",
    "De-identified = no identifiers = NOT PHI."),

  q("aa-003", AA, AA_TITLE, "knowledge", 2,
    "ICD-10-CM codes are used to document:",
    "Procedures performed during a visit", "Diagnoses, symptoms, and reasons for a medical encounter", "Time spent with each patient", "Drug prescriptions and refills",
    "B",
    "ICD-10-CM (International Classification of Diseases, 10th edition, Clinical Modification) codes capture diagnoses and reasons for visits. CPT codes document procedures.",
    "ICD-10 = diagnoses. CPT = procedures. Know the difference."),

  q("aa-004", AA, AA_TITLE, "knowledge", 2,
    "A superbill is used to:",
    "Report adverse drug events to the FDA", "Capture diagnosis and procedure codes for billing after a patient encounter", "Schedule follow-up appointments", "Document patient consent",
    "B",
    "A superbill (encounter form) lists the ICD-10 and CPT codes associated with a visit, allowing the billing team to submit a claim to the insurance company.",
    "Superbill = the billing summary of what happened in the visit."),

  q("aa-005", AA, AA_TITLE, "knowledge", 2,
    "What is a prior authorization?",
    "Written consent from the patient before a procedure", "Approval from the insurance company before a service is rendered", "A provider's note justifying treatment necessity", "A referral letter to a specialist",
    "B",
    "Prior authorization (PA) is insurer pre-approval for certain services, medications, or procedures. Without it, coverage may be denied. The MA assists by gathering clinical documentation.",
    "Prior auth = insurer says yes BEFORE the service happens."),

  q("aa-006", AA, AA_TITLE, "knowledge", 1,
    "The primary difference between an EHR and an EMR is:",
    "EMR includes billing; EHR does not", "EHR is designed to share data across multiple provider settings; EMR is practice-specific", "EHR is paper-based; EMR is electronic", "There is no practical difference",
    "B",
    "An EHR (Electronic Health Record) is interoperable — designed to move with the patient across providers. An EMR is a digital version of one practice's paper records.",
    "EHR = shared across providers. EMR = one practice only."),

  q("aa-007", AA, AA_TITLE, "knowledge", 2,
    "Which scheduling method assigns patients to arrive at the beginning of each hour, then schedules them in order of arrival?",
    "Wave scheduling", "Double-booking", "Open access scheduling", "Cluster scheduling",
    "A",
    "Wave scheduling has multiple patients arrive at the same time (e.g., three patients all at 9:00 AM) with the assumption that one will be a quick visit. Modified wave staggers them slightly.",
    "Wave = batch arrival at the hour, served in order."),

  q("aa-008", AA, AA_TITLE, "knowledge", 1,
    "A Notice of Privacy Practices (NPP) must be provided to patients:",
    "Only at the first visit and upon request", "At every visit to ensure awareness", "Only when a privacy breach occurs", "When requested by the insurer",
    "B",
    "HIPAA requires covered entities to provide an NPP at the first encounter and make it available on request. Patients acknowledge receipt in writing, but don't have to sign it.",
    "NPP: give at first visit, get acknowledgment. Offer again on request."),

  q("aa-009", AA, AA_TITLE, "knowledge", 2,
    "When releasing medical records to another provider, which document must be present?",
    "Insurance card copy", "Signed patient authorization for release of information", "Provider-to-provider verbal authorization", "A copy of the patient's advance directive",
    "B",
    "A valid release of information (ROI) form signed by the patient (or legal guardian) is required before disclosing PHI, unless an exception applies (e.g., treatment continuity).",
    "ROI form: required before releasing records, except for treatment exceptions."),

  q("aa-010", AA, AA_TITLE, "knowledge", 2,
    "An Advance Beneficiary Notice (ABN) is used when:",
    "A Medicare patient refuses treatment", "A service may not be covered by Medicare and the patient must be informed of their financial responsibility", "Medicaid patients switch plans", "A provider retires from Medicare participation",
    "B",
    "An ABN informs Medicare patients that a service may not be covered, allowing them to decide whether to proceed knowing they may pay out-of-pocket.",
    "ABN = Medicare warning: 'this might not be covered, you decide.'"),

  q("aa-011", AA, AA_TITLE, "knowledge", 2,
    "When a patient does not show for an appointment, the medical assistant should:",
    "Delete the appointment from the schedule", "Document the no-show in the patient's chart and attempt to contact the patient", "Bill the patient immediately for the missed visit", "Report the no-show to the insurance company",
    "B",
    "No-shows must be documented with date, time, and attempts to contact. Some practices charge for missed appointments — document per facility policy.",
    "No-show: document it, call the patient, follow facility policy."),

  q("aa-012", AA, AA_TITLE, "knowledge", 2,
    "Under HIPAA, patients have the right to do all of the following EXCEPT:",
    "Request corrections to their health information", "Access their own medical records", "Demand providers delete all records of a visit", "Request an accounting of disclosures",
    "C",
    "Patients can request amendments and have the right to access records, but they cannot require deletion of clinical records. Providers may deny certain amendment requests.",
    "Patients can ACCESS and REQUEST CORRECTION — not delete clinical records."),

  q("aa-013", AA, AA_TITLE, "knowledge", 1,
    "The HITECH Act strengthened HIPAA by:",
    "Creating a new national ID for patients", "Expanding breach notification requirements and increasing penalties for violations", "Requiring all providers to use paper backup systems", "Allowing patients to opt out of electronic records",
    "B",
    "HITECH (2009) extended HIPAA's reach to business associates, mandated breach notifications, and increased civil and criminal penalties for violations.",
    "HITECH = HIPAA 2.0. Bigger fines, breach notices, business associates included."),

  q("aa-014", AA, AA_TITLE, "knowledge", 2,
    "CPT code 99213 refers to which type of service?",
    "A new patient comprehensive exam", "An established patient office visit of moderate complexity", "A consultation with a specialist", "A preventive care visit",
    "B",
    "99213 is a Level 3 established patient E&M code for a low-to-moderate complexity office visit. E&M codes range from 99202–99215 for office visits.",
    "99213 = established patient, moderate complexity. Common outpatient code."),

  q("aa-015", AA, AA_TITLE, "knowledge", 2,
    "Coordination of benefits (COB) applies when a patient:",
    "Has both a primary and secondary insurance plan", "Owes a copayment for a visit", "Has a deductible that has not been met", "Uses a provider outside their network",
    "A",
    "COB determines which insurer pays first (primary) and which pays after (secondary) when a patient has more than one insurance plan. Prevents double payment.",
    "COB: two insurers, one pays first. Prevents overpayment."),

  q("aa-016", AA, AA_TITLE, "knowledge", 2,
    "A business associate agreement (BAA) under HIPAA is required when:",
    "A patient receives care from two different providers", "A vendor or contractor has access to PHI on behalf of a covered entity", "A provider switches EHR systems", "A patient authorizes record release",
    "B",
    "HIPAA requires BAAs with any third party (business associate) that creates, receives, maintains, or transmits PHI on behalf of the covered entity.",
    "BAA: any vendor touching your PHI needs one."),

  q("aa-017", AA, AA_TITLE, "knowledge", 2,
    "Which entity assigns National Provider Identifier (NPI) numbers?",
    "State medical boards", "CMS (Centers for Medicare and Medicaid Services)", "The Joint Commission", "The AMA",
    "B",
    "NPI numbers are assigned by CMS and uniquely identify healthcare providers in HIPAA standard electronic transactions. Every provider needs one to submit claims.",
    "NPI = unique provider ID assigned by CMS for billing."),

  q("aa-018", AA, AA_TITLE, "scenario", 2,
    "A patient calls asking for a copy of their medical records to bring to a specialist. The medical assistant should:",
    "Provide the records immediately over the phone", "Ask the patient to complete a signed records release authorization form first", "Tell the patient only the specialist can request the records", "Charge the patient before fulfilling the request",
    "B",
    "A signed authorization for release of information is required before disclosing PHI. Verbal authorization is not sufficient. The process must comply with state and HIPAA timelines.",
    "Records release: signed ROI form first, always."),

  q("aa-019", AA, AA_TITLE, "scenario", 2,
    "While in the hallway, a MA overhears two staff members discussing a patient's HIV status with the office door open. The correct action is:",
    "Ignore the conversation since the staff know the patient", "Discreetly remind the staff of privacy requirements and close the door", "File a HIPAA complaint with the HHS", "Report the incident to the patient",
    "B",
    "Incidental disclosures are a HIPAA concern. The appropriate first step is to address it internally with the staff — redirect them to a private space and remind them of the minimum necessary standard.",
    "Overheard PHI: close the door, remind the staff. Don't escalate first."),

  q("aa-020", AA, AA_TITLE, "scenario", 2,
    "An insurance company denies a claim for a procedure the provider believes is medically necessary. The medical assistant's role is to:",
    "Accept the denial and collect the balance from the patient", "Assist the provider in preparing documentation for an appeal", "Contact the insurance company to argue the case directly", "Reschedule the procedure under a different CPT code",
    "B",
    "The MA can gather records, prior auth documentation, and clinical notes to support an appeal. The provider signs off. Never recode to obtain coverage — that is fraud.",
    "Claim denied: gather documentation for appeal. Never recode."),

  q("aa-021", AA, AA_TITLE, "scenario", 2,
    "A patient requests to see their own medical record during a visit. The medical assistant should:",
    "Refuse because records can only be shared at designated release times", "Inform the patient of their right to access, and follow the facility's process for providing access", "Allow the patient to take the original chart home", "Ask the provider if it is okay before acknowledging the right",
    "B",
    "HIPAA grants patients the right to access their own PHI within 30 days of the request. The MA should follow the facility's process — they don't need provider permission to acknowledge this right.",
    "Patients have the right to access their records. Facilitate it; don't block it."),

  q("aa-022", AA, AA_TITLE, "scenario", 2,
    "A new MA notices a colleague looking up the chart of a famous local patient 'out of curiosity.' The correct response is:",
    "Look up the chart too since curiosity is natural", "Remind the colleague that accessing records without a treatment need violates HIPAA", "Report it to the patient immediately", "Ignore it since no information was shared externally",
    "B",
    "Accessing PHI without a legitimate need violates HIPAA — curiosity is not a permitted purpose. The MA should address it with the colleague and report it per facility policy if it continues.",
    "HIPAA: accessing records without a need = violation. Even internal."),

  q("aa-023", AA, AA_TITLE, "scenario", 2,
    "A patient's prior authorization expires before the scheduled procedure. The medical assistant should:",
    "Proceed with the procedure and resubmit authorization after", "Contact the insurance company immediately to renew or extend the prior authorization", "Cancel the procedure and reschedule for six months later", "Submit the claim without the auth and appeal if denied",
    "B",
    "An expired prior auth means the insurer's coverage approval is no longer valid. Proceeding without renewal risks denial. The MA should initiate the renewal process as soon as the gap is identified.",
    "Expired prior auth: renew before the procedure, not after."),

  q("aa-024", AA, AA_TITLE, "scenario", 2,
    "A patient schedules an appointment but their insurance card shows coverage ended last month. The medical assistant should:",
    "Proceed with the visit and bill self-pay after", "Notify the patient and ask them to verify or update their insurance before the visit", "Refuse the appointment until insurance is confirmed", "Bill the old insurance anyway",
    "B",
    "Insurance must be verified before the visit. Proactively notifying the patient allows them to update coverage or arrange payment, avoiding billing problems after the encounter.",
    "Verify insurance before the visit. Notify the patient if there's an issue."),

  q("aa-025", AA, AA_TITLE, "scenario", 3,
    "During phone triage, a patient describes sudden severe headache described as 'the worst headache of my life.' The medical assistant should:",
    "Schedule a routine appointment for the following week", "Advise the patient to go to the emergency department immediately or call 911", "Recommend over-the-counter pain relievers and call back if it worsens", "Transfer the call to a nurse to assess",
    "B",
    "A 'thunderclap' headache — worst headache of one's life — is a red-flag symptom for subarachnoid hemorrhage. This requires immediate emergency evaluation, not a routine appointment.",
    "Worst headache of life = thunderclap = 911. Never delay."),
];

// ── Domain 4: Laboratory Procedures ──────────────────────────────────────────

const LP = "laboratory-procedures";
const LP_TITLE = "Laboratory Procedures";

const laboratoryProcedures: ExamQuestion[] = [
  q("lab-001", LP, LP_TITLE, "knowledge", 1,
    "Which of the following is a CLIA-waived test?",
    "Complete blood count (CBC)", "Blood glucose by fingerstick (glucometer)", "Prothrombin time (PT/INR)", "Comprehensive metabolic panel (CMP)",
    "B",
    "CLIA-waived tests are simple, low-risk tests cleared for use outside a full laboratory. Fingerstick glucose, urine dipstick, rapid strep, and urine pregnancy tests are common examples.",
    "CLIA-waived = simple, low-risk. Glucometer, dipstick, rapid strep."),

  q("lab-002", LP, LP_TITLE, "knowledge", 2,
    "Quality control for a glucometer should be performed:",
    "Once per month", "Each time a new test strip lot is opened and daily per manufacturer guidelines", "Only when a patient result seems incorrect", "At the end of each work week",
    "B",
    "QC confirms the meter and strips are functioning correctly. Most glucometer protocols require QC at the start of each day and whenever a new vial of strips is used.",
    "QC: new lot + daily. Not just when something seems wrong."),

  q("lab-003", LP, LP_TITLE, "knowledge", 2,
    "Chain of custody documentation for a specimen is required primarily in which situation?",
    "Routine complete blood count", "Legal or forensic specimens such as drug testing for employment or court order", "Prenatal blood work", "Point-of-care rapid testing",
    "B",
    "Chain of custody creates an unbroken, documented record of specimen handling for legal purposes. It is required for drug screens used in legal proceedings, workplace testing, and forensic cases.",
    "Chain of custody = legal specimens. Document every hand that touches it."),

  q("lab-004", LP, LP_TITLE, "knowledge", 2,
    "When performing venipuncture with multiple tubes, which tube is collected first in the correct order of draw?",
    "EDTA (lavender top)", "Blood culture bottles", "SST (gold/tiger top)", "Sodium citrate (light blue top)",
    "B",
    "The correct order of draw starts with blood culture bottles, then sodium citrate (light blue), SST (gold), sodium heparin (green), EDTA (lavender), and oxalate/fluoride (gray).",
    "Order of draw: Blood Culture → Blue → Gold → Green → Lavender → Gray."),

  q("lab-005", LP, LP_TITLE, "knowledge", 2,
    "A tourniquet should be released no later than how long after application?",
    "30 seconds", "1 minute", "3 minutes", "5 minutes",
    "B",
    "Tourniquet time should not exceed 1 minute. Prolonged application causes hemoconcentration and hemolysis, affecting potassium, protein, and coagulation results.",
    "Tourniquet off within 1 minute. Longer = hemoconcentration."),

  q("lab-006", LP, LP_TITLE, "knowledge", 2,
    "Which pre-analytical error most commonly causes a hemolyzed specimen?",
    "Incorrect patient identification", "Drawing too quickly, using too small a needle, or vigorous mixing", "Labeling the tube before drawing", "Drawing from the antecubital fossa",
    "B",
    "Hemolysis occurs when red cells rupture. Small gauge needles, excessive vacuum, vigorous shaking, and prolonged tourniquet all cause hemolysis. It falsely elevates potassium.",
    "Hemolysis = ruptured RBCs. Caused by force, small needles, or poor technique."),

  q("lab-007", LP, LP_TITLE, "knowledge", 1,
    "What is the normal specific gravity range of urine?",
    "1.001–1.010", "1.010–1.030", "1.030–1.050", "1.050–1.080",
    "B",
    "Normal urine specific gravity is 1.010–1.030, reflecting the kidney's concentration ability. Values below 1.010 suggest dilute urine; above 1.030 may indicate dehydration.",
    "Urine SG: 1.010–1.030. Low = dilute. High = concentrated."),

  q("lab-008", LP, LP_TITLE, "knowledge", 2,
    "Glucose in the urine (glycosuria) most commonly indicates:",
    "Normal kidney function", "Diabetes mellitus or uncontrolled blood glucose", "Kidney infection", "Normal pregnancy",
    "B",
    "Glycosuria occurs when blood glucose exceeds the renal threshold (~180 mg/dL). It is a hallmark of uncontrolled diabetes mellitus but can also be seen in pregnancy (gestational) or renal glycosuria.",
    "Glucose in urine = blood glucose exceeded renal threshold (~180)."),

  q("lab-009", LP, LP_TITLE, "knowledge", 2,
    "When performing a throat culture for Group A Strep, the swab should contact:",
    "The tip of the tongue only", "Both tonsillar pillars and the posterior pharynx, avoiding the tongue and uvula", "The inner cheek mucosa", "The roof of the mouth",
    "B",
    "A proper throat culture swabs the tonsillar fossae and posterior pharynx where Group A Strep colonizes. Contact with the tongue or uvula increases gag reflex and reduces specimen quality.",
    "Throat swab: tonsils + back of throat. Avoid tongue and uvula."),

  q("lab-010", LP, LP_TITLE, "knowledge", 2,
    "Sharps containers should be replaced or sealed when they are:",
    "Completely full", "Three-quarters (¾) full", "Half full", "After each use",
    "B",
    "OSHA requires disposal of sharps containers when 3/4 full to prevent overfilling, which increases the risk of needlestick injury when closing or transporting.",
    "Sharps container: replace at 3/4 full. Never overfill."),

  q("lab-011", LP, LP_TITLE, "knowledge", 2,
    "What is the preferred site for capillary puncture in an adult?",
    "Central pad of the fingertip", "Lateral fingertip of the middle or ring finger", "Earlobe", "Back of the hand",
    "B",
    "The lateral aspect of the middle or ring finger avoids the nerve-dense fingertip center and provides adequate blood flow. The thumb, index, and pinky are avoided.",
    "Capillary puncture: lateral surface of middle or ring finger."),

  q("lab-012", LP, LP_TITLE, "knowledge", 1,
    "Which of the following requires proper biohazard disposal?",
    "Unused paper towels from handwashing", "All materials contaminated with blood or body fluids", "Empty specimen transport bags", "Used examination table paper",
    "B",
    "OSHA's Bloodborne Pathogen Standard requires biohazard disposal of all materials potentially contaminated with blood or OPIM (other potentially infectious materials).",
    "Biohazard = anything with blood or body fluids on it."),

  q("lab-013", LP, LP_TITLE, "knowledge", 2,
    "A fasting lipid panel requires the patient to fast for:",
    "4 hours", "8–12 hours", "24 hours", "2 hours",
    "B",
    "Lipid panels traditionally require 8–12 hours of fasting to accurately measure triglycerides and LDL. Some guidelines now allow non-fasting lipid screening, but fasting is still standard for follow-up testing.",
    "Fasting lipid: 8–12 hours. Water allowed."),

  q("lab-014", LP, LP_TITLE, "knowledge", 1,
    "Urine specimens for culture and sensitivity should be transported to the lab within how long, or refrigerated?",
    "30 minutes", "2 hours", "4 hours", "8 hours",
    "B",
    "Urine for C&S must reach the lab within 2 hours at room temperature. If delayed, the specimen should be refrigerated at 2–8°C to prevent bacterial overgrowth.",
    "Urine C&S: lab within 2 hours or refrigerate."),

  q("lab-015", LP, LP_TITLE, "knowledge", 2,
    "A rapid antigen strep test result is negative, but the provider suspects strep throat. What should happen next?",
    "Treat empirically with antibiotics since the test is often wrong", "Send a throat culture to the lab, as rapid tests have lower sensitivity", "Repeat the rapid test immediately", "Discharge the patient without treatment",
    "B",
    "Rapid strep tests have high specificity but lower sensitivity (~80%). A negative rapid test with high clinical suspicion requires a confirmatory throat culture.",
    "Negative rapid strep + high suspicion = send culture to lab."),

  q("lab-016", LP, LP_TITLE, "knowledge", 1,
    "Which tube additive is found in a lavender-top vacutainer?",
    "Sodium citrate", "EDTA (ethylenediaminetetraacetic acid)", "Sodium heparin", "Serum separator gel",
    "B",
    "Lavender tops contain EDTA, an anticoagulant that preserves cells for CBC and differential. The tube must be inverted 8–10 times to mix the additive.",
    "Lavender top = EDTA = CBC tube."),

  q("lab-017", LP, LP_TITLE, "knowledge", 2,
    "Lab safety requires that laboratory coats and gloves be removed before:",
    "Entering the specimen processing area", "Leaving the laboratory area for non-lab spaces", "Handling biohazard waste", "Using the centrifuge",
    "B",
    "PPE used in the lab should never be worn outside the lab to prevent cross-contamination. Remove and appropriately dispose of or store PPE before leaving the designated area.",
    "Lab PPE: stays in the lab. Remove before leaving."),

  q("lab-018", LP, LP_TITLE, "scenario", 2,
    "A glucometer QC result falls outside the acceptable range. The medical assistant should:",
    "Use the meter anyway since QC failures are often minor", "Not use the meter, troubleshoot per the manufacturer's protocol, and document the failure", "Report the QC failure to the patient", "Wait for a new lot of strips",
    "B",
    "Out-of-range QC means the meter should not be used for patient testing until the problem is resolved. Troubleshoot (check strips, battery, technique), rerun QC, and document per CLIA requirements.",
    "QC fail: stop testing, troubleshoot, document. Don't use it."),

  q("lab-019", LP, LP_TITLE, "scenario", 2,
    "After venipuncture, the MA notices the tourniquet was left on for 3 minutes during a difficult draw. The best action is:",
    "Proceed with labeling and sending the specimen", "Discard the tubes and redraw after the arm has been free for several minutes", "Note the delay in the chart and send the specimen anyway", "Ask the provider if the prolonged tourniquet matters",
    "B",
    "Prolonged tourniquet causes hemoconcentration, altering potassium, proteins, and coagulation results. The draw should be repeated after the stasis resolves.",
    "Tourniquet >1 minute: discard, wait, redraw."),

  q("lab-020", LP, LP_TITLE, "scenario", 2,
    "A specimen tube arrives in the lab with the patient's label missing. The medical assistant should:",
    "Label it from memory since the draw was just completed", "Discard the specimen and perform a redraw with proper labeling", "Contact the lab to see if they can identify it", "Send it to the lab with a note explaining the missing label",
    "B",
    "An unlabeled specimen is a critical error and cannot be processed. Mislabeling is a top cause of transfusion reactions and wrong-patient results. Redraw and label at the bedside.",
    "No label = discard and redraw. Never guess or relabel from memory."),

  q("lab-021", LP, LP_TITLE, "scenario", 2,
    "A patient refuses to provide a urine specimen for a drug screen, claiming they are unable to urinate at this time. The medical assistant should:",
    "Document the refusal and proceed with the rest of the visit", "Offer water, wait the facility's allotted time, and document the circumstances per protocol", "Mark the result as positive", "Reschedule the drug test",
    "B",
    "Drug testing protocols allow a defined waiting period if a patient cannot provide a specimen initially. Follow the chain-of-custody protocol including documentation of the delay.",
    "Can't void: water + wait time + document per protocol."),

  q("lab-022", LP, LP_TITLE, "scenario", 2,
    "A patient's urine specimen appears bright red. The medical assistant should:",
    "Discard it and ask for a fresh sample", "Document the appearance and notify the provider before processing", "Assume it is contamination from the collection process", "Proceed with routine urinalysis",
    "B",
    "Gross hematuria (visible blood) is a clinically significant finding that must be communicated to the provider. It could indicate infection, stones, trauma, or malignancy.",
    "Red urine = hematuria until proven otherwise. Notify provider immediately."),

  q("lab-023", LP, LP_TITLE, "scenario", 2,
    "During venipuncture, the needle accidentally punctures the MA's glove but not the skin. The correct action is:",
    "Continue the draw and change gloves after finishing", "Stop the procedure, safely remove the contaminated glove, perform hand hygiene, and don new gloves before continuing", "Complete the draw quickly and wash hands afterward", "Only change gloves if there was visible blood",
    "B",
    "A compromised glove is a contamination risk. Stop the procedure, follow safe sharps protocols, perform hand hygiene, and reglove. Integrity of the barrier must be maintained.",
    "Compromised glove: stop, remove, wash hands, reglove."),

  q("lab-024", LP, LP_TITLE, "scenario", 2,
    "The lab calls to report a glucose result of 42 mg/dL (critical low) for an inpatient. The medical assistant should:",
    "Document the result and leave a note for the provider to review at next rounds", "Immediately notify the provider and document the critical value notification", "Recheck the result before notifying anyone", "Notify the patient directly",
    "B",
    "Critical lab values require immediate provider notification. The MA must document the time, value, who was notified, and the provider's acknowledgment. Do not delay.",
    "Critical value: notify provider immediately, document everything."),

  q("lab-025", LP, LP_TITLE, "scenario", 3,
    "A patient receiving anticoagulation therapy has a point-of-care INR result of 6.2. The medical assistant should:",
    "Repeat the test to confirm before notifying anyone", "Immediately report the critical value to the provider and document the notification", "Schedule a repeat test for next week", "Advise the patient to skip their next dose",
    "B",
    "An INR of 6.2 is a critical value indicating dangerously high bleeding risk. The provider must be notified immediately. The MA should not advise medication changes or delay reporting.",
    "INR 6.2 = critical. Notify provider immediately. Never counsel medication changes."),
];

// ── Domain 5: Diagnostic Testing ─────────────────────────────────────────────

const DT = "diagnostic-testing";
const DT_TITLE = "Diagnostic Testing";

const diagnosticTesting: ExamQuestion[] = [
  q("dt-001", DT, DT_TITLE, "knowledge", 2,
    "In a standard 12-lead ECG, which leads are considered the limb leads?",
    "V1–V6", "Leads I, II, III, aVR, aVL, aVF", "V1, V2, V3, V4 only", "Leads II, III, V1, V2",
    "B",
    "The 12-lead ECG has 6 limb leads (I, II, III, aVR, aVL, aVF) placed on the extremities and 6 precordial/chest leads (V1–V6) placed on the chest wall.",
    "6 limb leads: I, II, III + aVR, aVL, aVF. 6 chest: V1–V6."),

  q("dt-002", DT, DT_TITLE, "knowledge", 2,
    "V1 electrode placement is at:",
    "5th intercostal space, left midclavicular line", "4th intercostal space, right sternal border", "4th intercostal space, left sternal border", "5th intercostal space, midaxillary line",
    "B",
    "V1 is placed at the 4th intercostal space, right sternal border. V2 is at the 4th ICS left sternal border. These are the first two precordial leads placed.",
    "V1: 4th ICS, right sternal. V2: 4th ICS, left sternal."),

  q("dt-003", DT, DT_TITLE, "knowledge", 2,
    "In a normal sinus rhythm, the heart rate falls between:",
    "40–60 bpm", "60–100 bpm", "100–120 bpm", "50–80 bpm",
    "B",
    "Normal sinus rhythm (NSR) is characterized by a regular P-wave before each QRS, consistent P-R interval (0.12–0.20 sec), and rate of 60–100 bpm.",
    "NSR: 60–100 bpm, regular P before QRS, consistent PR."),

  q("dt-004", DT, DT_TITLE, "knowledge", 2,
    "Which of the following is a common cause of artifact on an ECG tracing?",
    "Rapid heart rate", "Patient movement or poor electrode contact", "ST elevation", "Short QT interval",
    "B",
    "Artifact (interference on the tracing) is caused by patient movement, muscle tremor, loose electrodes, dried gel, electrical interference (AC), or poor skin preparation.",
    "Artifact: movement, loose leads, AC interference. Not a cardiac finding."),

  q("dt-005", DT, DT_TITLE, "knowledge", 2,
    "The P wave on an ECG represents:",
    "Ventricular depolarization", "Atrial depolarization", "Ventricular repolarization", "Bundle of His conduction",
    "B",
    "The P wave reflects atrial depolarization — electrical activation spreading across the atria before they contract. A normal P wave is upright in leads II and flat or inverted in aVR.",
    "P wave = atria depolarizing. It starts the whole sequence."),

  q("dt-006", DT, DT_TITLE, "knowledge", 2,
    "The QRS complex represents:",
    "Atrial repolarization", "Ventricular depolarization", "Atrial depolarization", "Ventricular repolarization",
    "B",
    "The QRS complex reflects ventricular depolarization — the electrical activation of both ventricles. It must be followed by mechanical contraction (ventricular systole).",
    "QRS = ventricles depolarize. The big 'spike' on the ECG."),

  q("dt-007", DT, DT_TITLE, "knowledge", 2,
    "The normal PR interval duration is:",
    "0.04–0.10 seconds", "0.12–0.20 seconds", "0.20–0.30 seconds", "0.30–0.44 seconds",
    "B",
    "The PR interval measures conduction from the SA node through the AV node. Normal is 0.12–0.20 seconds (3–5 small squares on standard ECG paper).",
    "Normal PR: 0.12–0.20 sec. Longer = first-degree AV block."),

  q("dt-008", DT, DT_TITLE, "knowledge", 3,
    "ST elevation in multiple contiguous leads of an ECG most likely indicates:",
    "Normal variant", "Pericarditis or acute myocardial infarction", "Bundle branch block", "Hypokalemia",
    "B",
    "ST elevation in contiguous leads (same coronary territory) is the classic sign of STEMI (ST-elevation myocardial infarction) until proven otherwise. It requires immediate physician notification.",
    "ST elevation in multiple leads = possible STEMI. Notify immediately."),

  q("dt-009", DT, DT_TITLE, "knowledge", 2,
    "Spirometry measures which respiratory parameter?",
    "Blood oxygen saturation", "Airflow and lung volumes, primarily FEV1 and FVC", "Arterial blood gas composition", "Diffusion capacity of the lungs",
    "B",
    "Spirometry measures how much air a patient can exhale (FVC) and how fast in the first second (FEV1). The FEV1/FVC ratio helps distinguish obstructive from restrictive lung disease.",
    "Spirometry = FEV1 and FVC. Measures airflow, not oxygen."),

  q("dt-010", DT, DT_TITLE, "knowledge", 1,
    "The Snellen chart is used to measure:",
    "Peripheral vision", "Distance visual acuity", "Color vision", "Intraocular pressure",
    "B",
    "The Snellen chart measures distance visual acuity at 20 feet. Normal vision is 20/20. 20/40 means the patient sees at 20 feet what a person with normal vision sees at 40 feet.",
    "Snellen = distance acuity at 20 feet. Normal = 20/20."),

  q("dt-011", DT, DT_TITLE, "knowledge", 1,
    "The Ishihara test is used to screen for:",
    "Depth perception", "Color vision deficiency", "Visual acuity", "Glaucoma",
    "B",
    "The Ishihara test uses pseudoisochromatic plates with numbers or patterns embedded in colored dots to identify red-green color vision deficiency.",
    "Ishihara = color blindness test. Colored dot plates."),

  q("dt-012", DT, DT_TITLE, "knowledge", 2,
    "How far from the ECG machine should the patient be positioned to minimize AC (60-cycle) interference?",
    "Within 1 foot", "At least 3 feet away from electrical equipment and outlets", "Distance does not matter", "In a Faraday cage",
    "B",
    "AC interference (60-cycle baseline wander) is reduced by positioning the patient away from electrical outlets and equipment. Also check that lead wires are not tangled or running parallel to power cords.",
    "AC artifact: move patient away from electrical outlets. Untangle wires."),

  q("dt-013", DT, DT_TITLE, "knowledge", 2,
    "Before performing an ECG, the medical assistant should ask the patient to:",
    "Eat a large meal to stabilize blood pressure", "Remove all metal jewelry, lie still, and breathe normally", "Perform light exercise to increase cardiac activity", "Hold their breath during the tracing",
    "B",
    "Metal can cause artifact; jewelry should be removed from the chest/arms. Patient stillness and relaxed breathing produce clean tracings.",
    "ECG prep: remove metal, lie still, breathe normally."),

  q("dt-014", DT, DT_TITLE, "knowledge", 2,
    "A patient scheduled for an upper GI series (barium swallow) should be instructed to:",
    "Eat a high-fiber meal the night before", "Fast for 8–12 hours before the procedure and avoid smoking or chewing gum", "Take a laxative the day before", "Take their regular medications with a full glass of water",
    "B",
    "Upper GI series requires an empty stomach for clear barium visualization. Smoking and gum stimulate gastric secretions. Some medications may need to be held — confirm with the provider.",
    "Upper GI prep: NPO 8–12 hours. No smoking, no gum."),

  q("dt-015", DT, DT_TITLE, "knowledge", 2,
    "Pulse oximetry readings can be falsely low in which of the following patients?",
    "Patients with normal hemoglobin", "Patients with dark nail polish, poor perfusion, or carbon monoxide poisoning", "Patients who are well-hydrated", "Patients in supine position",
    "B",
    "Nail polish (especially dark colors), poor peripheral perfusion (cold extremities, shock), and carbon monoxide (which binds hemoglobin like oxygen) all cause falsely normal or falsely low SpO2 readings.",
    "SpO2 false reading: dark polish, poor perfusion, CO poisoning."),

  q("dt-016", DT, DT_TITLE, "knowledge", 2,
    "In audiometry, a pure-tone threshold of 0–25 dB is classified as:",
    "Mild hearing loss", "Normal hearing", "Moderate hearing loss", "Severe hearing loss",
    "B",
    "Audiometry classification: Normal = 0–25 dB; Mild loss = 26–40 dB; Moderate = 41–55 dB; Moderately severe = 56–70 dB; Severe = 71–90 dB; Profound = 91+ dB.",
    "Normal hearing: threshold ≤25 dB. Anything above = some level of loss."),

  q("dt-017", DT, DT_TITLE, "knowledge", 2,
    "Which lead is most commonly used for rhythm monitoring on a continuous ECG?",
    "aVR", "Lead II", "V5", "V6",
    "B",
    "Lead II is the most common monitoring lead — it provides the clearest P waves and upright QRS, making rhythm interpretation easier.",
    "Rhythm monitoring: Lead II is standard. Best P wave visibility."),

  q("dt-018", DT, DT_TITLE, "scenario", 2,
    "An ECG tracing shows a wandering baseline throughout the recording. The most likely cause is:",
    "Ventricular tachycardia", "Patient movement, breathing, or loose electrode contact", "Atrial fibrillation", "ST elevation",
    "B",
    "Wandering baseline is an artifact. Most common causes: patient breathing (diaphragmatic movement), restlessness, poor electrode contact, or dried electrode gel.",
    "Wandering baseline = artifact. Check electrodes and patient position."),

  q("dt-019", DT, DT_TITLE, "scenario", 2,
    "A patient has significant chest hair that may affect ECG electrode adhesion. The medical assistant should:",
    "Place the electrodes over the hair and proceed", "Dry-shave the electrode sites with a disposable razor before applying the electrodes", "Apply extra electrode gel to compensate", "Skip the precordial leads that are affected",
    "B",
    "Hair prevents good electrode contact, causing artifact. Dry-shaving the site (per facility protocol using a single-use razor) ensures clean contact and accurate results.",
    "Chest hair + ECG: dry shave the site, then apply electrodes."),

  q("dt-020", DT, DT_TITLE, "scenario", 3,
    "While performing a routine ECG, the MA notices ST elevation in leads II, III, and aVF. The correct action is:",
    "Repeat the ECG to confirm before notifying the provider", "Immediately show the tracing to the provider and do not delay", "Document the finding and include it in the chart for the provider to review later", "Inform the patient of the finding before notifying the provider",
    "B",
    "ST elevation in inferior leads (II, III, aVF) is a possible inferior STEMI. This requires immediate provider notification — do not delay for a repeat tracing or documentation first.",
    "Possible STEMI on ECG: show the provider immediately. Time = myocardium."),

  q("dt-021", DT, DT_TITLE, "scenario", 2,
    "A patient with a pacemaker is scheduled for a routine 12-lead ECG. The medical assistant should:",
    "Refuse to perform the ECG since pacemakers are a contraindication", "Perform the ECG as usual and note the presence of the pacemaker on the requisition", "Avoid placing electrodes over the pacemaker site only", "Skip the limb leads to avoid interference",
    "B",
    "Pacemakers are not a contraindication to ECG — they produce characteristic pacemaker spikes that the provider needs to interpret. Note the device on the requisition.",
    "Pacemaker + ECG: perform it normally, document the device."),

  q("dt-022", DT, DT_TITLE, "scenario", 2,
    "During spirometry, a patient produces multiple effort-dependent maneuvers with widely varying results. The medical assistant should:",
    "Use the highest FVC result regardless of reproducibility", "Coach the patient through additional attempts, document the best two reproducible maneuvers, and note effort quality", "Report only the first attempt", "Repeat the test on a different day",
    "B",
    "Spirometry requires at least 3 acceptable maneuvers with the two best FVC values within 150 mL of each other (ATS/ERS acceptability criteria). Coaching technique affects results significantly.",
    "Spirometry: 3 acceptable attempts, 2 best within 150 mL. Coach effort."),

  q("dt-023", DT, DT_TITLE, "scenario", 2,
    "A patient fails the Snellen visual acuity screen at the 20/40 line in the right eye. The medical assistant should:",
    "Retest immediately under brighter lighting", "Document the result and notify the provider for further evaluation or referral", "Advise the patient to purchase reading glasses over the counter", "Retest after the patient rests their eyes for 10 minutes",
    "B",
    "A failed vision screen is a finding for the provider to evaluate. The MA documents the result and flags it. The MA should not advise treatment or self-medication.",
    "Failed vision screen: document, notify provider. Don't advise OTC glasses."),

  q("dt-024", DT, DT_TITLE, "scenario", 2,
    "A patient scheduled for an MRI mentions they have a cardiac pacemaker implanted. The medical assistant should:",
    "Proceed with scheduling since newer pacemakers are MRI-compatible", "Notify the provider and MRI department immediately so compatibility can be verified before the procedure", "Cancel the MRI and schedule a CT instead without consulting the provider", "Ask the patient if they have ever had an MRI before",
    "B",
    "MRI and pacemakers can be dangerous. Some devices are MRI-conditional, others are not. The provider and MRI safety officer must confirm compatibility before the procedure.",
    "Pacemaker + MRI: verify compatibility first. Never assume it's safe."),

  q("dt-025", DT, DT_TITLE, "scenario", 2,
    "After completing an ECG, the medical assistant realizes the V3 and V4 lead wires were switched during the recording. The correct action is:",
    "Document the error in the chart and submit the tracing", "Repeat the ECG with correct lead placement and note that the original was discarded due to placement error", "Correct the labels on the original printout", "Alert the provider that the interpretation should reverse V3 and V4",
    "B",
    "Lead placement errors create inaccurate waveforms that cannot be corrected after the fact. A repeat ECG with correct placement is required.",
    "Lead placement error: repeat the ECG. Never relabel or correct the paper."),
];

// ── Domain 6: Pharmacology ────────────────────────────────────────────────────

const PH = "pharmacology";
const PH_TITLE = "Pharmacology";

const pharmacology: ExamQuestion[] = [
  q("ph-001", PH, PH_TITLE, "knowledge", 1,
    "Which of the following is a Schedule II controlled substance?",
    "Alprazolam (Xanax)", "Oxycodone (OxyContin)", "Tramadol", "Propoxyphene",
    "B",
    "Schedule II drugs have high abuse potential with currently accepted medical use. Examples include oxycodone, morphine, fentanyl, methylphenidate (Ritalin), and Adderall.",
    "Schedule II: highest medical-use controlled substances. Oxycodone, morphine, fentanyl."),

  q("ph-002", PH, PH_TITLE, "knowledge", 1,
    "The sig code 'qid' means:",
    "Every other day", "Four times a day", "Every 12 hours", "Twice a day",
    "B",
    "QID = quater in die (Latin: four times a day). Common abbreviations: BID = twice daily; TID = three times daily; QID = four times daily.",
    "QID = 4x/day. BID = 2x. TID = 3x. QID = 4x."),

  q("ph-003", PH, PH_TITLE, "knowledge", 1,
    "The abbreviation 'prn' on a prescription means:",
    "Every night at bedtime", "As needed", "Before meals", "Per repeat notification",
    "B",
    "PRN (pro re nata, Latin) = as needed. The patient takes the medication only when the condition it treats is present (e.g., pain PRN).",
    "PRN = as needed. Not on a fixed schedule."),

  q("ph-004", PH, PH_TITLE, "knowledge", 1,
    "The abbreviation 'ac' on a prescription means:",
    "After meals", "Before meals", "At bedtime", "Every morning",
    "B",
    "AC = ante cibum (Latin: before meals). PC = post cibum (after meals). HS = hora somni (at bedtime).",
    "ac = before meals. pc = after meals. hs = bedtime."),

  q("ph-005", PH, PH_TITLE, "knowledge", 2,
    "Which side effect is most commonly associated with ACE inhibitors?",
    "Hyperkalemia and dry cough", "Tachycardia and flushing", "Bradycardia and depression", "Weight gain and fluid retention",
    "A",
    "ACE inhibitors (e.g., lisinopril, enalapril) commonly cause a persistent dry cough due to bradykinin accumulation. They can also cause hyperkalemia, especially with renal impairment.",
    "ACE inhibitor: dry cough + hyperkalemia. Switch to ARB if cough intolerable."),

  q("ph-006", PH, PH_TITLE, "knowledge", 2,
    "Beta-blockers lower blood pressure primarily by:",
    "Dilating blood vessels directly", "Blocking beta-adrenergic receptors to reduce heart rate and cardiac output", "Increasing sodium excretion by the kidneys", "Blocking calcium channels in smooth muscle",
    "B",
    "Beta-blockers (e.g., metoprolol, atenolol) block beta-1 and/or beta-2 receptors, slowing heart rate and reducing myocardial contractility, thus lowering cardiac output and BP.",
    "Beta-blockers: slow the heart rate. HR down → BP down."),

  q("ph-007", PH, PH_TITLE, "knowledge", 2,
    "Patients on loop diuretics (e.g., furosemide) should be monitored for:",
    "Hyperkalemia", "Hypokalemia and dehydration", "Hypernatremia", "Polycythemia",
    "B",
    "Loop diuretics promote potassium excretion along with sodium and water, leading to hypokalemia. Patients may need potassium supplementation and regular electrolyte monitoring.",
    "Loop diuretics: watch for low potassium (hypokalemia)."),

  q("ph-008", PH, PH_TITLE, "knowledge", 2,
    "A patient on warfarin (Coumadin) should be instructed to:",
    "Avoid all fruits and vegetables", "Maintain a consistent intake of vitamin K–rich foods and report significant diet changes", "Increase iron intake", "Avoid protein-rich foods",
    "B",
    "Warfarin's anticoagulant effect is affected by vitamin K intake (leafy greens). Consistency matters more than elimination — sudden changes alter INR.",
    "Warfarin + vitamin K: keep intake consistent. Don't eliminate, don't spike."),

  q("ph-009", PH, PH_TITLE, "knowledge", 1,
    "Insulin vials that have been opened should be stored at:",
    "−20°C in a freezer", "Room temperature for up to 28 days (most formulations)", "Refrigerated at all times until empty", "At room temperature indefinitely",
    "B",
    "Unopened insulin: refrigerate. Once opened, most insulin formulations can be stored at room temperature (below 77°F) for up to 28 days without significant potency loss.",
    "Opened insulin: room temp up to 28 days. Unopened: refrigerate."),

  q("ph-010", PH, PH_TITLE, "knowledge", 2,
    "A DEA number on a prescription indicates:",
    "The pharmacy's license to dispense", "The prescriber is registered to prescribe controlled substances", "The patient has been screened for substance abuse", "The drug is FDA-approved",
    "B",
    "A DEA (Drug Enforcement Administration) number is assigned to providers authorized to prescribe, dispense, or administer controlled substances. It is required on all controlled substance prescriptions.",
    "DEA number = provider is authorized to prescribe controlled substances."),

  q("ph-011", PH, PH_TITLE, "knowledge", 2,
    "Which route of administration places medication under the tongue to be absorbed directly into the bloodstream?",
    "Buccal", "Sublingual", "Intradermal", "Transdermal",
    "B",
    "Sublingual (SL) administration places the drug under the tongue where it dissolves and absorbs rapidly into the sublingual vasculature, bypassing first-pass hepatic metabolism.",
    "Sublingual = under the tongue. Buccal = between cheek and gum."),

  q("ph-012", PH, PH_TITLE, "knowledge", 2,
    "Drug classification 'anticholinergic' means the drug:",
    "Activates the parasympathetic nervous system", "Blocks muscarinic acetylcholine receptors, reducing gland secretions and GI motility", "Stimulates the sympathetic nervous system", "Blocks adrenergic receptors",
    "B",
    "Anticholinergic effects (SLUDGE reversal): dry mouth, urinary retention, constipation, blurred vision, tachycardia, and confusion. Examples: atropine, antihistamines, tricyclics.",
    "Anticholinergic: dry mouth, retention, constipation, blurred vision. 'Dry as a bone.'"),

  q("ph-013", PH, PH_TITLE, "knowledge", 2,
    "A contraindication to a medication means:",
    "The drug requires dose adjustment", "The drug should NOT be administered due to potential harm that outweighs any benefit", "The patient must be monitored more closely", "The drug may cause minor side effects",
    "B",
    "A contraindication is a condition or factor that makes administration of a drug inadvisable. Absolute contraindications mean the drug must never be used; relative contraindications require judgment.",
    "Contraindication = harm outweighs benefit. Don't give it."),

  q("ph-014", PH, PH_TITLE, "knowledge", 2,
    "A Schedule II controlled substance log must account for every dose and be:",
    "Reviewed monthly by the office manager", "Reconciled with each dispensing or administration, with no gaps in count", "Maintained only for narcotics, not stimulants", "Updated weekly",
    "B",
    "Schedule II drug logs require running counts — every dose in and out must be documented in real time. Any discrepancy must be reported immediately. Audits compare counts to documentation.",
    "Schedule II log: every dose in/out in real time. No gaps."),

  q("ph-015", PH, PH_TITLE, "knowledge", 2,
    "A drug interaction occurs when:",
    "A patient skips a dose of medication", "One drug alters the effect of another drug, either increasing or decreasing its action", "A patient takes a medication with food", "A drug requires refrigeration",
    "B",
    "Drug interactions can be pharmacokinetic (altering absorption, metabolism) or pharmacodynamic (additive or opposing effects). The MA should flag potential interactions to the prescriber.",
    "Drug interaction: one drug changes what another drug does."),

  q("ph-016", PH, PH_TITLE, "knowledge", 1,
    "Which of the following is a common anticholinergic medication side effect?",
    "Bradycardia", "Dry mouth", "Diarrhea", "Excessive salivation",
    "B",
    "Anticholinergic drugs block acetylcholine and produce: dry mouth, urinary retention, blurred vision, constipation, tachycardia, and heat intolerance.",
    "Anticholinergic: 'dry as a bone, blind as a bat, red as a beet, mad as a hatter.'"),

  q("ph-017", PH, PH_TITLE, "knowledge", 2,
    "Statins (e.g., atorvastatin, simvastatin) are used to treat:",
    "Hypertension only", "Elevated LDL cholesterol and to reduce cardiovascular risk", "Diabetes mellitus", "Arrhythmias",
    "B",
    "Statins inhibit HMG-CoA reductase, reducing cholesterol synthesis. They lower LDL, stabilize plaques, and reduce risk of MI and stroke. Monitor for myopathy and liver enzymes.",
    "Statins = lower LDL. Watch for muscle pain (myopathy)."),

  q("ph-018", PH, PH_TITLE, "scenario", 2,
    "A patient calls to say they accidentally took a double dose of their blood pressure medication. The medical assistant should:",
    "Tell the patient not to worry and take the next scheduled dose", "Advise the patient to sit down, monitor for dizziness or fainting, and notify the provider immediately", "Recommend the patient go to the emergency room regardless of symptoms", "Instruct the patient to take an extra dose tomorrow to rebalance",
    "B",
    "A double dose of antihypertensives can cause hypotension, dizziness, or syncope. The patient needs immediate guidance and provider notification. Reserve emergency services for symptomatic cases.",
    "Double BP dose: sit down, watch for dizziness, call the provider."),

  q("ph-019", PH, PH_TITLE, "scenario", 2,
    "A medication error is discovered after a patient has already left the office. The medical assistant should:",
    "Wait to see if the patient calls with complaints before acting", "Notify the provider immediately and document the error in the incident report and patient chart per facility policy", "Tell the patient the next time they call in", "Correct the chart entry to reflect the correct medication",
    "B",
    "Medication errors must be reported immediately to the provider and documented honestly in the incident report. Altering the record to hide the error is fraud.",
    "Medication error: notify provider now, document honestly. Never alter the chart."),

  q("ph-020", PH, PH_TITLE, "scenario", 2,
    "While preparing a medication, the MA picks up a vial labeled 'Drug A' instead of the ordered 'Drug B.' The MA should:",
    "Administer Drug A since the vials are stored together and are likely similar", "Stop, return Drug A to storage, locate Drug B, and verify the six rights before administration", "Ask a colleague to confirm the vial is acceptable", "Administer the drug and document the substitution",
    "B",
    "The Six Rights require verification before administration. If the right drug has not been confirmed, stop. Never substitute medications or rely on storage proximity for identification.",
    "Wrong drug pulled: stop, put it back, find the right one. Six rights every time."),

  q("ph-021", PH, PH_TITLE, "scenario", 2,
    "The end-of-day Schedule II controlled substance count does not reconcile with the log. The medical assistant should:",
    "Recount once more, then record the discrepancy without notifying anyone", "Immediately notify the supervising provider or pharmacist and follow the facility's controlled substance discrepancy protocol", "Assume a counting error and correct the log to match the physical count", "Wait until the next day to see if it resolves",
    "B",
    "Controlled substance discrepancies must be reported immediately. Falsifying logs is a federal offense. Follow facility protocol — this may trigger a DEA report.",
    "Schedule II discrepancy: report immediately. Never correct the log to match."),

  q("ph-022", PH, PH_TITLE, "scenario", 2,
    "After receiving an injection, a patient begins reporting itching, hives, and throat tightness. The medical assistant should:",
    "Apply topical antihistamine cream and observe the patient", "Recognize this as a possible anaphylactic reaction, alert the provider, and prepare to administer epinephrine per protocol", "Give the patient water and have them lie down", "Document the symptoms and schedule a follow-up appointment",
    "B",
    "Hives + throat tightness after injection = anaphylaxis warning signs. This is a life-threatening emergency. Epinephrine (0.3 mg IM thigh, EpiPen) is the first-line treatment.",
    "Post-injection: hives + throat tightness = anaphylaxis. Epi first."),

  q("ph-023", PH, PH_TITLE, "scenario", 2,
    "The MA discovers that a medication on the crash cart has expired by two months. The correct action is:",
    "Leave it until the next scheduled cart check", "Remove the expired medication immediately, replace it with a current one, and document the replacement", "Use it for the current patient and order a replacement", "Cross off the expiration date and write in a new date",
    "B",
    "Expired medications must be removed immediately, replaced, and documented. Never use expired medications or alter expiration dates — this is unsafe and illegal.",
    "Expired medication: remove now, replace, document. Never alter dates."),

  q("ph-024", PH, PH_TITLE, "scenario", 2,
    "A patient asks if it is safe to take ibuprofen with their prescribed lisinopril. The medical assistant should:",
    "Tell the patient ibuprofen is safe with all medications", "Advise the patient to ask the provider, as NSAIDs can reduce the effectiveness of ACE inhibitors and affect kidney function", "Tell the patient to stop the lisinopril while taking ibuprofen", "Say the combination is dangerous and refuse to discuss further",
    "B",
    "NSAIDs (like ibuprofen) can reduce the antihypertensive effect of ACE inhibitors and worsen renal function. The MA should not prescribe or countermand — defer to the provider.",
    "NSAID + ACE inhibitor concern: don't prescribe. Redirect to the provider."),

  q("ph-025", PH, PH_TITLE, "scenario", 3,
    "A patient's chart shows an allergy to penicillin. The provider orders amoxicillin. The medical assistant should:",
    "Fill the prescription since amoxicillin is mild", "Alert the provider to the allergy before dispensing, as amoxicillin is a penicillin-class antibiotic", "Substitute with a similar antibiotic from the cabinet", "Ask the patient if they want to try it anyway",
    "B",
    "Amoxicillin IS a penicillin. A documented penicillin allergy means the prescriber must be notified before the order is filled. Cross-reactivity also exists with some cephalosporins.",
    "Amoxicillin = penicillin. Allergy documented? Notify the provider before filling."),
];

// ── Domain 7: Medical Terminology and Anatomy ─────────────────────────────────

const MT = "medical-terminology-and-anatomy";
const MT_TITLE = "Medical Terminology and Anatomy";

const medicalTerminologyAndAnatomy: ExamQuestion[] = [
  q("mt-001", MT, MT_TITLE, "knowledge", 1,
    "The prefix 'brady-' means:",
    "Rapid or fast", "Slow", "Painful", "Large",
    "B",
    "Brady- means slow (e.g., bradycardia = slow heart rate, bradypnea = slow breathing). The opposite prefix is tachy- (fast).",
    "Brady = slow. Tachy = fast. BRADy = sloW."),

  q("mt-002", MT, MT_TITLE, "knowledge", 1,
    "The prefix 'tachy-' means:",
    "Under or below", "Rapid or fast", "Across", "Difficult",
    "B",
    "Tachy- means rapid or fast (e.g., tachycardia = fast heart rate >100 bpm, tachypnea = fast breathing >20/min).",
    "Tachycardia: TACHY = fast, cardia = heart."),

  q("mt-003", MT, MT_TITLE, "knowledge", 1,
    "The suffix '-itis' means:",
    "Surgical removal of", "Inflammation of", "Disease of", "Enlargement of",
    "B",
    "-itis means inflammation. Examples: appendicitis, hepatitis, otitis, arthritis. Inflammation is characterized by redness, heat, swelling, and pain.",
    "-itis = inflammation. Append-itis, hepat-itis, arth-ritis."),

  q("mt-004", MT, MT_TITLE, "knowledge", 1,
    "The suffix '-ectomy' means:",
    "Incision into", "Surgical removal of", "Inflammation of", "Visual examination of",
    "B",
    "-ectomy = surgical removal (e.g., appendectomy = removal of appendix, cholecystectomy = removal of gallbladder, mastectomy = removal of breast tissue).",
    "-ectomy = removal. AppendECTOMY removes the appendix."),

  q("mt-005", MT, MT_TITLE, "knowledge", 1,
    "The root word 'cardi-' refers to:",
    "The liver", "The heart", "The kidney", "The skin",
    "B",
    "Cardi- refers to the heart. Examples: cardiomegaly (enlarged heart), cardiomyopathy (heart muscle disease), cardiology (study of the heart).",
    "Cardi = heart. CARDIology, CARDIac."),

  q("mt-006", MT, MT_TITLE, "knowledge", 1,
    "The root word 'hepat-' refers to:",
    "The kidney", "The liver", "The lung", "The stomach",
    "B",
    "Hepat- refers to the liver (Greek: hēpar). Examples: hepatitis (liver inflammation), hepatomegaly (enlarged liver), hepatocyte (liver cell).",
    "Hepat = liver. HEPATitis, HEPATomegaly."),

  q("mt-007", MT, MT_TITLE, "knowledge", 1,
    "The root word 'nephr-' refers to:",
    "The nerve", "The kidney", "The uterus", "The brain",
    "B",
    "Nephr- refers to the kidney. Examples: nephrology (study of kidneys), nephritis (kidney inflammation), nephrectomy (kidney removal).",
    "Nephr = kidney. NEPHRology, NEPHRectomy."),

  q("mt-008", MT, MT_TITLE, "knowledge", 1,
    "The root word 'derm-' refers to:",
    "The blood", "The skin", "The bone", "The muscle",
    "B",
    "Derm- (dermat-) refers to the skin. Examples: dermatology (study of the skin), dermatitis (skin inflammation), epidermis (outer skin layer).",
    "Derm = skin. DERMatology, DERMatitis."),

  q("mt-009", MT, MT_TITLE, "knowledge", 1,
    "In anatomical position, the patient is:",
    "Lying face down with arms at the sides", "Standing erect, facing forward, arms at the sides with palms facing forward", "Lying face up with arms at the sides", "Sitting upright with knees flexed",
    "B",
    "Anatomical position: standing erect, facing forward, arms at sides with palms facing anteriorly (forward). It is the reference position for all anatomical directional terms.",
    "Anatomical position: standing, facing forward, palms FORWARD."),

  q("mt-010", MT, MT_TITLE, "knowledge", 1,
    "Which anatomical term describes a structure closer to the head?",
    "Inferior", "Superior", "Posterior", "Lateral",
    "B",
    "Superior = toward the head (cephalad). Inferior = toward the feet (caudal). The heart is superior to the stomach; the stomach is inferior to the heart.",
    "Superior = toward the head. Inferior = toward the feet."),

  q("mt-011", MT, MT_TITLE, "knowledge", 1,
    "Which term describes a structure located farther from the midline of the body?",
    "Medial", "Lateral", "Proximal", "Distal",
    "B",
    "Lateral = away from the midline. Medial = toward the midline. The ears are lateral to the nose; the nose is medial to the ears.",
    "Lateral = away from midline. Medial = toward midline."),

  q("mt-012", MT, MT_TITLE, "knowledge", 1,
    "In terms of limb direction, 'proximal' means:",
    "Farther from the point of attachment", "Closer to the point of attachment (trunk)", "On the outer surface", "On the inner surface",
    "B",
    "Proximal = closer to the trunk or origin. Distal = farther from the trunk. The knee is proximal to the ankle; the ankle is distal to the knee.",
    "Proximal = closer to the body. Distal = farther from the body."),

  q("mt-013", MT, MT_TITLE, "knowledge", 2,
    "The sagittal plane divides the body into:",
    "Superior and inferior portions", "Left and right portions", "Anterior and posterior portions", "Medial and lateral portions",
    "B",
    "The sagittal plane divides left and right. The midsagittal (median) plane divides equally; a parasagittal plane divides unequally. The coronal plane divides front/back; the transverse (axial) plane divides top/bottom.",
    "Sagittal = left/right. Coronal = front/back. Transverse = top/bottom."),

  q("mt-014", MT, MT_TITLE, "knowledge", 1,
    "The suffix '-scopy' means:",
    "Surgical removal", "Visual examination using a scope", "Incision into", "Creation of an opening",
    "B",
    "-scopy = visual examination (e.g., colonoscopy, bronchoscopy, cystoscopy). The instrument used ends in -scope; the procedure ends in -scopy.",
    "-scopy = look with a scope. -scope = the instrument."),

  q("mt-015", MT, MT_TITLE, "knowledge", 1,
    "The abbreviation 'SOAP' in charting stands for:",
    "Symptoms, Observations, Assessment, Plan", "Subjective, Objective, Assessment, Plan", "Subjective, Outcome, Analysis, Prognosis", "Symptoms, Orders, Actions, Progress",
    "B",
    "SOAP notes: Subjective (patient's complaint), Objective (measurable findings), Assessment (diagnosis/impression), Plan (treatment). Standard outpatient documentation format.",
    "SOAP: Subjective, Objective, Assessment, Plan."),

  q("mt-016", MT, MT_TITLE, "knowledge", 2,
    "The combining form 'pulmon/o' refers to:",
    "The heart", "The lungs", "The stomach", "The kidney",
    "B",
    "Pulmon/o = lung (Latin: pulmo). Examples: pulmonary (pertaining to the lungs), pulmonologist (lung specialist), pulmonary embolism (clot in the lung).",
    "Pulmon/o = lung. PULMONary, PULMONologist."),

  q("mt-017", MT, MT_TITLE, "knowledge", 2,
    "The term 'dyspnea' means:",
    "Rapid breathing", "Difficult or labored breathing", "Cessation of breathing", "Slow breathing",
    "B",
    "Dys- = difficult/abnormal; -pnea = breathing. Dyspnea = difficulty breathing. Apnea = no breathing. Bradypnea = slow. Tachypnea = fast.",
    "Dyspnea = difficult breathing. Dys = difficult, pnea = breathing."),

  q("mt-018", MT, MT_TITLE, "scenario", 2,
    "A physician's order reads 'administer Amoxicillin 500 mg PO TID × 10 days.' The medical assistant interprets this as:",
    "Give 500 mg amoxicillin by injection twice daily for 10 days", "Give 500 mg amoxicillin by mouth three times daily for 10 days", "Give 500 mg amoxicillin daily at bedtime for 10 days", "Give 500 mg amoxicillin intravenously four times daily for 10 days",
    "B",
    "PO = by mouth (per os). TID = three times daily (ter in die). × 10 days = duration. The complete interpretation is oral amoxicillin 500 mg three times daily for 10 days.",
    "PO = by mouth. TID = 3x/day. Decode every abbreviation."),

  q("mt-019", MT, MT_TITLE, "scenario", 2,
    "A patient asks what 'hypertension' means. The medical assistant explains it as:",
    "Low blood sugar", "Consistently elevated blood pressure above normal ranges", "Rapid heart rate", "Inflammation of the heart",
    "B",
    "Hyper- = above normal; -tension = pressure. Hypertension = high blood pressure. Hypotension = low blood pressure. Use plain language when explaining to patients.",
    "Hyper = high. Hypo = low. Hypertension = high BP."),

  q("mt-020", MT, MT_TITLE, "scenario", 2,
    "A chart reads 'patient has bilateral lower extremity edema.' In plain language, this means:",
    "The patient has pain in one leg", "Both legs are swollen with fluid accumulation", "One leg has a rash", "The patient's feet are infected",
    "B",
    "Bilateral = both sides; lower extremity = legs; edema = fluid accumulation/swelling. Translating medical terminology for patients is a core MA communication skill.",
    "Bilateral = both sides. Edema = swelling. Lower extremity = legs."),

  q("mt-021", MT, MT_TITLE, "scenario", 2,
    "A physician documents 'patient has a contusion on the right lateral malleolus.' The medical assistant understands this means:",
    "A fracture in the left ankle", "A bruise on the outer right ankle bone", "An infection of the right knee", "A strain of the right knee ligament",
    "B",
    "Contusion = bruise. Right = right side. Lateral = outer. Malleolus = ankle bone (the bony protrusion). Lateral malleolus = outer ankle.",
    "Contusion = bruise. Lateral malleolus = outer ankle bone."),

  q("mt-022", MT, MT_TITLE, "scenario", 2,
    "An order is written 'apply 0.5% hydrocortisone cream to affected area BID.' A new staff member reads 'BID' as 'once daily.' What should the medical assistant do?",
    "Allow the error since the difference is minor", "Correct the interpretation immediately: BID = twice daily, and ensure the patient receives accurate instructions", "Cross out BID and write 'daily' to avoid confusion", "Ask the patient which they prefer",
    "B",
    "Abbreviation errors are a leading cause of medication errors. BID = twice daily (bis in die). Correcting the interpretation before patient instruction is critical.",
    "BID = twice daily. Always clarify abbreviation errors immediately."),

  q("mt-023", MT, MT_TITLE, "scenario", 2,
    "A patient's chart documents 'hematuria x 3 days.' In plain language, this means:",
    "Headache for three days", "Blood in the urine for three days", "Swelling for three days", "Fatigue for three days",
    "B",
    "Hematuria = blood (hemat-) + urine (-uria). It can be gross (visible) or microscopic. The 'x 3 days' notation indicates duration.",
    "Hematuria = blood in urine. Hemat = blood, uria = urine."),

  q("mt-024", MT, MT_TITLE, "scenario", 2,
    "A lab report states the patient has 'leukocytosis.' The medical assistant understands this as:",
    "A decrease in red blood cells", "An elevated white blood cell count", "Clotting disorder", "An elevated platelet count",
    "B",
    "Leukocytosis: leukocyt- = white blood cell; -osis = abnormal increase in. This often indicates infection, inflammation, or (in severe cases) malignancy.",
    "Leukocytosis = elevated WBCs. -osis = increased. Leukopenia = decreased."),

  q("mt-025", MT, MT_TITLE, "scenario", 2,
    "A physician dictates 'the patient has tachycardia and diaphoresis.' When documenting, the medical assistant should record:",
    "Slow heart rate and vomiting", "Rapid heart rate and excessive sweating", "Irregular heart rate and fever", "Chest pain and shortness of breath",
    "B",
    "Tachycardia = rapid heart rate (tachy = fast, cardia = heart). Diaphoresis = profuse sweating (a sign of sympathetic activation, often accompanying shock, MI, or hypoglycemia).",
    "Tachycardia = fast heart. Diaphoresis = heavy sweating."),
];

// ── Export ────────────────────────────────────────────────────────────────────

export const CCMA_EXAM_BANK: ExamQuestion[] = [
  ...clinicalPatientCare,
  ...patientCareCoordination,
  ...administrativeAssisting,
  ...laboratoryProcedures,
  ...diagnosticTesting,
  ...pharmacology,
  ...medicalTerminologyAndAnatomy,
];

export const CCMA_DOMAIN_SLUGS = [
  "clinical-patient-care",
  "patient-care-coordination-and-education",
  "administrative-assisting",
  "laboratory-procedures",
  "diagnostic-testing",
  "pharmacology",
  "medical-terminology-and-anatomy",
] as const;

export type CcmaExamBankDomainSlug = (typeof CCMA_DOMAIN_SLUGS)[number];
