export type {
  ProgressionDomainInput,
  ProgressionQuizAttempt,
  ProgressionMockAttempt,
  ProgressionDomainSummary,
  ReadinessState,
  ReadinessLabel,
  ReadinessActionType,
  NextBestTask,
  ReadinessChecklistItem,
  ActivityRecencySignal,
  ProgressionSnapshot,
  BuildStudentProgressionSnapshotArgs,
} from "@/lib/ccma/progression/ccma-readiness-engine";

export {
  RECENT_ATTEMPT_WEIGHTS,
  clampNumber,
  roundNumber,
  averageScores,
  weightedRecentAverage,
  getScoreStandardDeviation,
  getLatestVsPreviousAverages,
  getDaysSinceDate,
  buildDomainSummaries,
  calculateDomainImprovement,
  calculateQuizSignal,
  calculatePracticeExamSignal,
  calculateActivityRecencySignal,
  buildWeightedReadinessScore,
  determinePracticeExamUnlock,
  determineReadinessState,
  determineNextBestTask,
  determineEncouragements,
  buildReadinessChecklist,
  buildStudentProgressionSnapshot,
} from "@/lib/ccma/progression/ccma-readiness-engine";
