import type { ExamChoice, ExamQuestion } from "@/lib/exams/types";

const domainTitles = {
  "foundational-knowledge-basic-science": "Foundational Knowledge and Basic Science",
  "anatomy-and-physiology": "Anatomy and Physiology",
  "patient-intake-and-vitals": "Patient Intake and Vitals",
  "general-patient-care": "General Patient Care",
  "infection-control-and-safety": "Infection Control and Safety",
  "point-of-care-testing-and-laboratory-procedures": "Point of Care Testing and Laboratory Procedures",
  phlebotomy: "Phlebotomy",
  "ekg-and-cardiovascular-testing": "EKG and Cardiovascular Testing",
  "patient-care-coordination-and-education": "Patient Care Coordination and Education",
  "administrative-assisting": "Administrative Assisting",
  "communication-and-customer-service": "Communication and Customer Service",
  "medical-law-and-ethics": "Medical Law and Ethics",
} as const;

type DomainSlug = keyof typeof domainTitles;

function choice(id: "a" | "b" | "c" | "d", text: string): ExamChoice {
  return { id, label: id.toUpperCase(), text };
}

function question(
  id: string,
  domainSlug: DomainSlug,
  prompt: string,
  choices: [ExamChoice, ExamChoice, ExamChoice, ExamChoice],
  correctChoiceId: "a" | "b" | "c" | "d",
  rationale: string,
  memoryTip: string,
  difficulty: 1 | 2 | 3,
): ExamQuestion {
  return {
    id,
    domainSlug,
    domainTitle: domainTitles[domainSlug],
    prompt,
    choices,
    correctChoiceId,
    rationale,
    memoryTip,
    difficulty,
  };
}

export const ccmaExamBank: ExamQuestion[] = [
  question(
    "fk-001",
    "foundational-knowledge-basic-science",
    "A task requires provider judgment and falls outside MA scope. What should the medical assistant do?",
    [
      choice("a", "Complete the task independently to save time"),
      choice("b", "Escalate to the provider and stay within scope"),
      choice("c", "Ask the patient what should be done"),
      choice("d", "Document nothing until the end of the day"),
    ],
    "b",
    "Scope questions reward patient safety, role awareness, and escalation to the provider.",
    "Support, do not overstep.",
    1,
  ),
  question(
    "fk-002",
    "foundational-knowledge-basic-science",
    "A medication is ordered in grams, but the bottle is labeled in milligrams. What should the MA recognize first?",
    [
      choice("a", "A need for unit conversion"),
      choice("b", "A privacy concern"),
      choice("c", "A scheduling error"),
      choice("d", "A specimen issue"),
    ],
    "a",
    "Dosage questions often begin with recognizing that a metric conversion is required.",
    "Check the units before the dose.",
    2,
  ),
  question(
    "fk-003",
    "foundational-knowledge-basic-science",
    "Which route of medication administration places the drug directly into muscle tissue?",
    [
      choice("a", "Intradermal"),
      choice("b", "Intramuscular"),
      choice("c", "Topical"),
      choice("d", "Sublingual"),
    ],
    "b",
    "Intramuscular medication is administered into muscle tissue.",
    "IM = into muscle.",
    1,
  ),
  question(
    "fk-004",
    "foundational-knowledge-basic-science",
    "The suffix '-itis' most often indicates:",
    [
      choice("a", "Inflammation"),
      choice("b", "Slow movement"),
      choice("c", "Surgical repair"),
      choice("d", "Blood cell"),
    ],
    "a",
    "Medical terminology uses the suffix '-itis' to indicate inflammation.",
    "Itis = inflamed.",
    1,
  ),
  question(
    "fk-005",
    "foundational-knowledge-basic-science",
    "Why should a medical assistant use reliable medication information resources instead of guessing from memory?",
    [
      choice("a", "Because medication details can affect dose, precautions, and side effects"),
      choice("b", "Because medication questions never involve patient safety"),
      choice("c", "Because only pharmacies can read drug information"),
      choice("d", "Because route of administration does not matter"),
    ],
    "a",
    "Medication information tools help confirm important safety details such as dose, precautions, and side effects.",
    "Verify medication facts before acting.",
    2,
  ),
  question(
    "ap-001",
    "anatomy-and-physiology",
    "Questions about gas exchange and oxygenation are most closely tied to which body system?",
    [
      choice("a", "Respiratory system"),
      choice("b", "Digestive system"),
      choice("c", "Integumentary system"),
      choice("d", "Urinary system"),
    ],
    "a",
    "Gas exchange and oxygenation are core respiratory-system functions.",
    "Oxygen exchange points to lungs.",
    1,
  ),
  question(
    "ap-002",
    "anatomy-and-physiology",
    "A disease process that disrupts the body's internal balance is affecting:",
    [
      choice("a", "Homeostasis"),
      choice("b", "Scheduling"),
      choice("c", "Chain of command"),
      choice("d", "Revenue cycle"),
    ],
    "a",
    "Homeostasis describes the body's internal balance and is commonly disrupted by illness.",
    "Homeostasis = internal balance.",
    1,
  ),
  question(
    "ap-003",
    "anatomy-and-physiology",
    "Which organ is most directly responsible for filtering blood and helping regulate fluid balance?",
    [
      choice("a", "Liver"),
      choice("b", "Kidneys"),
      choice("c", "Pancreas"),
      choice("d", "Gallbladder"),
    ],
    "b",
    "The kidneys filter waste from blood and help regulate fluid and electrolyte balance.",
    "Kidneys filter and balance.",
    1,
  ),
  question(
    "ap-004",
    "anatomy-and-physiology",
    "Blood glucose regulation is most closely linked to which organ?",
    [
      choice("a", "Pancreas"),
      choice("b", "Spleen"),
      choice("c", "Appendix"),
      choice("d", "Esophagus"),
    ],
    "a",
    "The pancreas is strongly associated with blood-glucose regulation.",
    "Pancreas helps manage sugar.",
    1,
  ),
  question(
    "ap-005",
    "anatomy-and-physiology",
    "Why is pairing a diagnostic test with the body system it evaluates useful on the CCMA exam?",
    [
      choice("a", "It helps connect the test to the function or problem being assessed"),
      choice("b", "It removes the need to know any symptoms"),
      choice("c", "It guarantees the patient has that disorder"),
      choice("d", "It replaces documentation"),
    ],
    "a",
    "Diagnostics make more sense when linked to the system and function they evaluate.",
    "Tie the test to the system.",
    2,
  ),
  question(
    "iv-001",
    "patient-intake-and-vitals",
    "Before taking vital signs, the MA should first:",
    [
      choice("a", "Verify the patient's identity"),
      choice("b", "Open the billing screen"),
      choice("c", "Call the pharmacy"),
      choice("d", "Review only the last visit note"),
    ],
    "a",
    "Patient identification is the first safety step before clinical data collection.",
    "No ID, no vitals.",
    1,
  ),
  question(
    "iv-002",
    "patient-intake-and-vitals",
    "A blood pressure reading is much higher than expected. What is the best conceptual response?",
    [
      choice("a", "Ignore it if the patient feels fine"),
      choice("b", "Verify appropriately, document, and report"),
      choice("c", "Delete the reading and leave it blank"),
      choice("d", "Ask the patient to guess the normal value"),
    ],
    "b",
    "Abnormal findings should be rechecked according to policy, documented, and escalated appropriately.",
    "Verify, document, escalate.",
    2,
  ),
  question(
    "iv-003",
    "patient-intake-and-vitals",
    "Which statement best describes the chief complaint?",
    [
      choice("a", "It is the main reason for today's visit"),
      choice("b", "It is the patient's insurance plan"),
      choice("c", "It is the office inventory level"),
      choice("d", "It is the provider's billing code"),
    ],
    "a",
    "The chief complaint captures the main reason the patient is seeking care today.",
    "Chief complaint = why the patient came today.",
    1,
  ),
  question(
    "iv-004",
    "patient-intake-and-vitals",
    "Why does it help to understand what a vital sign measures instead of just memorizing the numbers?",
    [
      choice("a", "It helps the MA understand why a finding matters"),
      choice("b", "It makes patient identification unnecessary"),
      choice("c", "It removes the need for documentation"),
      choice("d", "It means abnormal values can be ignored"),
    ],
    "a",
    "Understanding what the measurement represents improves recognition, communication, and follow-up.",
    "Every number reflects body function.",
    2,
  ),
  question(
    "iv-005",
    "patient-intake-and-vitals",
    "Which option lists common core vital signs used in routine intake?",
    [
      choice("a", "Blood pressure, pulse, respirations, and temperature"),
      choice("b", "Height, room number, insurance group, and pharmacy"),
      choice("c", "Diet history, occupation, hobbies, and exercise"),
      choice("d", "Co-pay, deductible, coinsurance, and authorization"),
    ],
    "a",
    "Blood pressure, pulse, respirations, and temperature are common core vital signs.",
    "BP, pulse, respirations, temperature.",
    1,
  ),
  question(
    "gp-001",
    "general-patient-care",
    "Before a minor office procedure begins, the MA should prioritize:",
    [
      choice("a", "Room and supply preparation plus patient setup"),
      choice("b", "Leaving the room to answer phones"),
      choice("c", "Skipping draping to save time"),
      choice("d", "Waiting until after the procedure to explain anything"),
    ],
    "a",
    "Preparation includes room setup, patient readiness, positioning, draping, and needed supplies.",
    "Prepare the space and the patient.",
    1,
  ),
  question(
    "gp-002",
    "general-patient-care",
    "If a patient becomes symptomatic immediately after an injection, the MA should first focus on:",
    [
      choice("a", "Patient safety and prompt response"),
      choice("b", "Cleaning the tray before anything else"),
      choice("c", "Finishing the inventory log"),
      choice("d", "Completing billing charges"),
    ],
    "a",
    "When a condition changes unexpectedly, patient safety and appropriate response come first.",
    "Safety before cleanup.",
    2,
  ),
  question(
    "gp-003",
    "general-patient-care",
    "Why are positioning and draping part of good patient care?",
    [
      choice("a", "They support safety, privacy, and comfort"),
      choice("b", "They replace informed consent"),
      choice("c", "They make documentation optional"),
      choice("d", "They eliminate the need for hand hygiene"),
    ],
    "a",
    "Positioning and draping support patient safety, dignity, privacy, and comfort.",
    "Position for safety, drape for dignity.",
    1,
  ),
  question(
    "gp-004",
    "general-patient-care",
    "After a routine procedure is completed, what remains important even if the patient tolerated it well?",
    [
      choice("a", "Accurate documentation"),
      choice("b", "Deleting the visit note"),
      choice("c", "Ignoring provider instructions"),
      choice("d", "Skipping equipment cleanup"),
    ],
    "a",
    "Documentation remains a key part of safe patient care after procedures.",
    "If it happened, chart it clearly.",
    1,
  ),
  question(
    "gp-005",
    "general-patient-care",
    "Medication-administration questions often reward which habit?",
    [
      choice("a", "Careful route and safety awareness"),
      choice("b", "Using the fastest route available"),
      choice("c", "Skipping verification if the patient has taken it before"),
      choice("d", "Relying on memory instead of the order"),
    ],
    "a",
    "Medication support questions commonly test safe workflow, route awareness, and verification.",
    "Check the route, check the order, stay safe.",
    2,
  ),
  question(
    "ic-001",
    "infection-control-and-safety",
    "Which precaution standard applies to every patient encounter?",
    [
      choice("a", "Standard precautions"),
      choice("b", "Droplet precautions only"),
      choice("c", "Airborne precautions only"),
      choice("d", "Isolation precautions only if requested"),
    ],
    "a",
    "Standard precautions are the baseline approach for all patient encounters.",
    "Standard is for everyone.",
    1,
  ),
  question(
    "ic-002",
    "infection-control-and-safety",
    "A sterile glove touches a nonsterile surface. What should the MA do?",
    [
      choice("a", "Keep going if the surface looked clean"),
      choice("b", "Replace the contaminated glove"),
      choice("c", "Ask the patient if they mind"),
      choice("d", "Finish first and fix it later"),
    ],
    "b",
    "Once sterility is broken, the contaminated item must be corrected immediately.",
    "Contaminated means replace it.",
    2,
  ),
  question(
    "ic-003",
    "infection-control-and-safety",
    "Why is hand hygiene still important when gloves are worn?",
    [
      choice("a", "Gloves do not replace clean technique"),
      choice("b", "Gloves automatically sterilize the hands"),
      choice("c", "Hand hygiene is only for surgery"),
      choice("d", "It is only needed at the end of the week"),
    ],
    "a",
    "Hand hygiene remains important because gloves are not a replacement for proper clean technique.",
    "Gloves are a barrier, not a substitute.",
    2,
  ),
  question(
    "ic-004",
    "infection-control-and-safety",
    "A task creates splash risk from blood or body fluids. What should guide PPE choice?",
    [
      choice("a", "Expected exposure risk"),
      choice("b", "Which item is easiest to find"),
      choice("c", "What another patient wore last time"),
      choice("d", "The color of the exam room"),
    ],
    "a",
    "PPE should match the expected exposure risk for the task being performed.",
    "Match the barrier to the risk.",
    2,
  ),
  question(
    "ic-005",
    "infection-control-and-safety",
    "Why do equipment checks, cleaning workflows, and quality logs matter in the clinic?",
    [
      choice("a", "They support patient and staff safety"),
      choice("b", "They exist only for billing"),
      choice("c", "They eliminate the need for training"),
      choice("d", "They make abnormal results irrelevant"),
    ],
    "a",
    "These processes help confirm the environment and equipment are safe before patient care continues.",
    "Safety systems protect people before problems grow.",
    2,
  ),
  question(
    "lp-001",
    "point-of-care-testing-and-laboratory-procedures",
    "A specimen is collected correctly but labeled with the wrong patient information. The biggest issue is:",
    [
      choice("a", "Specimen integrity and patient safety are compromised"),
      choice("b", "The test will still be valid"),
      choice("c", "Only billing is affected"),
      choice("d", "The temperature no longer matters"),
    ],
    "a",
    "Incorrect labeling creates patient-identification risk and invalidates confidence in the specimen.",
    "Wrong label, wrong risk.",
    1,
  ),
  question(
    "lp-002",
    "point-of-care-testing-and-laboratory-procedures",
    "If a point-of-care control is out of range, the MA should recognize that:",
    [
      choice("a", "The result may not be valid"),
      choice("b", "The result is automatically normal"),
      choice("c", "The patient can ignore the test"),
      choice("d", "Documentation is no longer needed"),
    ],
    "a",
    "An out-of-range control means the testing system may not be functioning acceptably, so the result cannot be trusted.",
    "Bad control, bad confidence.",
    2,
  ),
  question(
    "lp-003",
    "point-of-care-testing-and-laboratory-procedures",
    "Why do timing and technique matter in waived testing?",
    [
      choice("a", "Missed steps or wrong timing can invalidate the result"),
      choice("b", "Simple tests cannot become invalid"),
      choice("c", "Timing matters only for billing"),
      choice("d", "Technique is irrelevant if the patient is stable"),
    ],
    "a",
    "Even simple tests can become invalid when timing or technique is not followed correctly.",
    "Simple does not mean careless.",
    2,
  ),
  question(
    "lp-004",
    "point-of-care-testing-and-laboratory-procedures",
    "After a test result is obtained, the MA should still:",
    [
      choice("a", "Document and route the result appropriately"),
      choice("b", "Assume the provider already knows"),
      choice("c", "Throw away the result if it looks abnormal"),
      choice("d", "Skip the chart if the patient is waiting"),
    ],
    "a",
    "Testing workflow includes accurate documentation and safe result communication.",
    "Read it, record it, route it.",
    1,
  ),
  question(
    "lp-005",
    "point-of-care-testing-and-laboratory-procedures",
    "Expired testing supplies create what type of concern?",
    [
      choice("a", "Result validity concern"),
      choice("b", "Dietary concern"),
      choice("c", "Scheduling concern"),
      choice("d", "Only a cosmetic concern"),
    ],
    "a",
    "Expired materials can undermine confidence in test validity.",
    "Expired supplies weaken trust in results.",
    2,
  ),
  question(
    "ph-001",
    "phlebotomy",
    "Why is immediate accurate labeling crucial in phlebotomy?",
    [
      choice("a", "It links the specimen to the correct patient"),
      choice("b", "It removes the need for patient identifiers"),
      choice("c", "It changes the order of draw"),
      choice("d", "It prevents all bruising"),
    ],
    "a",
    "Specimen labeling is a patient-safety step that ensures the sample belongs to the right individual.",
    "Correct tube, correct patient.",
    1,
  ),
  question(
    "ph-002",
    "phlebotomy",
    "After removing the needle, the MA should prioritize:",
    [
      choice("a", "Sharps safety, hemostasis, and proper specimen handling"),
      choice("b", "Leaving the uncapped needle on the tray"),
      choice("c", "Skipping tube checks if the draw was smooth"),
      choice("d", "Walking away before bleeding is controlled"),
    ],
    "a",
    "Post-draw safety includes needle safety, patient bleeding control, and correct specimen workflow.",
    "Protect the team, the patient, and the sample.",
    1,
  ),
  question(
    "ph-003",
    "phlebotomy",
    "Why does order of draw matter in phlebotomy?",
    [
      choice("a", "It helps reduce additive carryover between tubes"),
      choice("b", "It determines the patient's diagnosis on its own"),
      choice("c", "It replaces patient identification"),
      choice("d", "It makes labeling optional"),
    ],
    "a",
    "Order of draw helps reduce additive carryover and protects specimen quality.",
    "Correct order helps protect the sample.",
    2,
  ),
  question(
    "ph-004",
    "phlebotomy",
    "Which vein is commonly used for routine venipuncture when available?",
    [
      choice("a", "Median cubital vein"),
      choice("b", "Femoral vein"),
      choice("c", "Jugular vein"),
      choice("d", "Temporal vein"),
    ],
    "a",
    "The median cubital vein is commonly used for routine venipuncture.",
    "Median cubital is the common routine choice.",
    2,
  ),
  question(
    "ph-005",
    "phlebotomy",
    "Why is pre-draw preparation so important before venipuncture starts?",
    [
      choice("a", "It helps prevent avoidable errors before the draw begins"),
      choice("b", "It makes patient consent unnecessary"),
      choice("c", "It removes the need for specimen transport rules"),
      choice("d", "It guarantees the draw will be painless"),
    ],
    "a",
    "Preparation supports correct identification, supplies, site choice, and smoother workflow before the puncture.",
    "Prevent the error before the puncture.",
    2,
  ),
  question(
    "ekg-001",
    "ekg-and-cardiovascular-testing",
    "Which step best improves EKG tracing quality before recording begins?",
    [
      choice("a", "Proper skin prep and correct lead placement"),
      choice("b", "Letting the patient hold the lead wires"),
      choice("c", "Starting the machine before electrodes adhere"),
      choice("d", "Ignoring motion artifact"),
    ],
    "a",
    "Clean skin prep and accurate lead placement are foundational for a clearer EKG tracing.",
    "Prep and placement come first.",
    1,
  ),
  question(
    "ekg-002",
    "ekg-and-cardiovascular-testing",
    "If a cardiovascular symptom or finding seems concerning, the MA should:",
    [
      choice("a", "Document accurately and notify the provider promptly"),
      choice("b", "Wait until the patient leaves to mention it"),
      choice("c", "Erase the tracing and start over without saying anything"),
      choice("d", "Ask the patient to monitor it at home first"),
    ],
    "a",
    "Concerning symptoms or findings require accurate documentation and prompt escalation.",
    "Concerning heart data does not wait.",
    2,
  ),
  question(
    "ekg-003",
    "ekg-and-cardiovascular-testing",
    "An EKG primarily records the heart's:",
    [
      choice("a", "Electrical activity"),
      choice("b", "Bone density"),
      choice("c", "Digestive enzyme level"),
      choice("d", "Visual acuity"),
    ],
    "a",
    "An electrocardiogram records electrical activity from the heart.",
    "EKG = electrical activity of the heart.",
    1,
  ),
  question(
    "ekg-004",
    "ekg-and-cardiovascular-testing",
    "Motion artifact on an EKG most directly affects:",
    [
      choice("a", "Tracing quality"),
      choice("b", "The patient's legal name"),
      choice("c", "The room temperature"),
      choice("d", "Insurance coverage"),
    ],
    "a",
    "Movement can create artifact that reduces tracing quality.",
    "Movement can muddy the tracing.",
    1,
  ),
  question(
    "ekg-005",
    "ekg-and-cardiovascular-testing",
    "Why is it useful to know which symptoms often lead to cardiovascular testing?",
    [
      choice("a", "It helps connect the test to the clinical concern"),
      choice("b", "It eliminates the need for documentation"),
      choice("c", "It proves the patient has heart disease"),
      choice("d", "It replaces patient identification"),
    ],
    "a",
    "Connecting symptoms to the purpose of the test helps the learner interpret why cardiovascular testing is being used.",
    "Know the symptom, then the test purpose.",
    2,
  ),
  question(
    "pc-001",
    "patient-care-coordination-and-education",
    "Which action best reflects good care coordination?",
    [
      choice("a", "Helping the patient complete the referral and follow-up plan"),
      choice("b", "Handing over a form with no explanation"),
      choice("c", "Avoiding community resources because they take time"),
      choice("d", "Documenting only after the next appointment"),
    ],
    "a",
    "Care coordination is about continuity and helping the next step actually happen.",
    "Close the loop.",
    1,
  ),
  question(
    "pc-002",
    "patient-care-coordination-and-education",
    "Patient education is most effective when it is:",
    [
      choice("a", "Matched to the patient's needs and the provider plan"),
      choice("b", "The same script for every patient"),
      choice("c", "Skipped if the visit is busy"),
      choice("d", "Focused only on billing questions"),
    ],
    "a",
    "Education should be clear, audience-appropriate, and aligned with the plan of care.",
    "Teach to the patient in front of you.",
    1,
  ),
  question(
    "pc-003",
    "patient-care-coordination-and-education",
    "Which statement best reflects teach-back?",
    [
      choice("a", "Ask the patient to explain the instructions in their own words"),
      choice("b", "Ask only whether the patient understands"),
      choice("c", "Skip questions so the visit stays shorter"),
      choice("d", "Use only technical language to sound precise"),
    ],
    "a",
    "Teach-back confirms understanding by asking the patient to explain the plan back in their own words.",
    "Understanding is shown, not assumed.",
    2,
  ),
  question(
    "pc-004",
    "patient-care-coordination-and-education",
    "Why do return precautions and follow-up instructions matter?",
    [
      choice("a", "They help the patient know the next steps after the visit"),
      choice("b", "They replace provider assessment"),
      choice("c", "They are only needed for billing"),
      choice("d", "They make referrals unnecessary"),
    ],
    "a",
    "Clear follow-up and return instructions support continuity and safer care after the visit.",
    "The visit ends, but the plan continues.",
    1,
  ),
  question(
    "pc-005",
    "patient-care-coordination-and-education",
    "Preventive care questions often emphasize:",
    [
      choice("a", "Screenings, reminders, and follow-through"),
      choice("b", "Ignoring routine care unless symptoms are severe"),
      choice("c", "Only emergency treatment"),
      choice("d", "Removing patient choice from the plan"),
    ],
    "a",
    "Preventive care often involves timely screenings, reminders, and helping patients complete the next step.",
    "Prevention needs follow-through.",
    2,
  ),
  question(
    "ad-001",
    "administrative-assisting",
    "A patient calls with a need that sounds urgent. Scheduling should reflect the:",
    [
      choice("a", "Urgency and type of visit needed"),
      choice("b", "Most convenient empty slot only"),
      choice("c", "Staff lunch schedule first"),
      choice("d", "Patient's favorite provider even if unavailable for days"),
    ],
    "a",
    "Administrative workflow includes recognizing urgency and matching it to the appropriate appointment type.",
    "Right problem, right slot.",
    1,
  ),
  question(
    "ad-002",
    "administrative-assisting",
    "Why do prior authorizations and accurate records matter in office workflow?",
    [
      choice("a", "They support continuity, coverage, compliance, and timely care"),
      choice("b", "They replace the medical record"),
      choice("c", "They are optional for all procedures"),
      choice("d", "They eliminate patient education needs"),
    ],
    "a",
    "Administrative follow-through helps patients access services while supporting coverage and compliance.",
    "Good admin work keeps care moving.",
    2,
  ),
  question(
    "ad-003",
    "administrative-assisting",
    "Which term describes the amount a patient may owe before the plan begins paying for covered services subject to that requirement?",
    [
      choice("a", "Deductible"),
      choice("b", "Copayment"),
      choice("c", "Coinsurance"),
      choice("d", "Referral"),
    ],
    "a",
    "A deductible is the amount a patient may owe before the plan begins paying for covered services subject to the deductible.",
    "Deductible comes before plan payment on covered services subject to it.",
    2,
  ),
  question(
    "ad-004",
    "administrative-assisting",
    "Which term describes a fixed amount a patient pays for a covered service?",
    [
      choice("a", "Copayment"),
      choice("b", "Coinsurance"),
      choice("c", "Deductible"),
      choice("d", "Preauthorization"),
    ],
    "a",
    "A copayment is a fixed amount a patient pays for a covered service.",
    "Copayment = fixed amount.",
    1,
  ),
  question(
    "ad-005",
    "administrative-assisting",
    "Which term describes the patient's percentage share of the allowed amount for a covered service?",
    [
      choice("a", "Coinsurance"),
      choice("b", "Copayment"),
      choice("c", "Deductible"),
      choice("d", "Chief complaint"),
    ],
    "a",
    "Coinsurance refers to the patient's percentage share of the allowed amount for a covered service.",
    "Coinsurance = percentage share.",
    2,
  ),
  question(
    "cm-001",
    "communication-and-customer-service",
    "Why should a medical assistant adapt communication style to the patient or audience?",
    [
      choice("a", "Different people need different support for understanding and safety"),
      choice("b", "It saves the office from documenting care"),
      choice("c", "It means using technical jargon whenever possible"),
      choice("d", "It replaces informed consent"),
    ],
    "a",
    "Audience-aware communication improves clarity, safety, and respect across patient interactions.",
    "Same goal, better delivery.",
    1,
  ),
  question(
    "cm-002",
    "communication-and-customer-service",
    "A frustrated patient is escalating at the front desk. The MA's best initial response is to:",
    [
      choice("a", "Stay calm, listen, and respond professionally"),
      choice("b", "Match the patient's tone so they feel heard"),
      choice("c", "Argue about office policy"),
      choice("d", "Ignore the patient until they calm down alone"),
    ],
    "a",
    "Difficult interactions are best handled with calm professionalism, listening, and appropriate next steps.",
    "Calm is a clinical skill too.",
    1,
  ),
  question(
    "cm-003",
    "communication-and-customer-service",
    "Which question style is most likely to encourage a patient to share useful details?",
    [
      choice("a", "An open-ended question"),
      choice("b", "A question that can only be answered yes or no"),
      choice("c", "A question asked while walking away"),
      choice("d", "A question filled with unexplained jargon"),
    ],
    "a",
    "Open-ended questions often help patients share more complete information.",
    "Open-ended questions invite fuller answers.",
    2,
  ),
  question(
    "cm-004",
    "communication-and-customer-service",
    "If a language barrier affects understanding, the safest communication support is to:",
    [
      choice("a", "Use appropriate interpretation support according to policy"),
      choice("b", "Assume the patient understood the instructions"),
      choice("c", "Talk much louder in English"),
      choice("d", "Skip the education discussion"),
    ],
    "a",
    "Communication support should help accuracy and understanding rather than relying on assumptions.",
    "Clarity matters more than guesswork.",
    2,
  ),
  question(
    "cm-005",
    "communication-and-customer-service",
    "A good phone message for the clinical team should include:",
    [
      choice("a", "The patient's concern and the urgency of the call"),
      choice("b", "Only the patient's first name"),
      choice("c", "No callback information"),
      choice("d", "Only the staff member's opinion"),
    ],
    "a",
    "Useful phone messages are clear, accurate, and include the concern and urgency so the team can respond safely.",
    "Good messages move care forward.",
    2,
  ),
  question(
    "le-001",
    "medical-law-and-ethics",
    "Which principle is central to privacy protection under laws such as HIPAA?",
    [
      choice("a", "Protect patient information from unauthorized sharing"),
      choice("b", "Discuss patient details openly if the intention is helpful"),
      choice("c", "Share records whenever a family member asks"),
      choice("d", "Skip documentation to keep records private"),
    ],
    "a",
    "Privacy law and ethics questions focus on protecting information and limiting disclosure appropriately.",
    "Private means protected.",
    1,
  ),
  question(
    "le-002",
    "medical-law-and-ethics",
    "If a reportable safety or abuse concern is suspected, the MA should:",
    [
      choice("a", "Follow reporting and escalation requirements"),
      choice("b", "Wait to see if it happens again next month"),
      choice("c", "Discuss it casually with unrelated coworkers first"),
      choice("d", "Leave it undocumented to protect privacy"),
    ],
    "a",
    "Law-and-ethics questions often test patient protection, mandatory reporting, and appropriate escalation.",
    "Protect and report.",
    2,
  ),
  question(
    "le-003",
    "medical-law-and-ethics",
    "Which action best reflects the minimum-necessary standard?",
    [
      choice("a", "Share only the information needed for the purpose"),
      choice("b", "Share the entire chart whenever any question is asked"),
      choice("c", "Avoid documenting patient care"),
      choice("d", "Discuss patient details where anyone nearby can hear"),
    ],
    "a",
    "Minimum necessary means limiting the use, disclosure, or request to what is needed for the purpose.",
    "Needed, not everything known.",
    2,
  ),
  question(
    "le-004",
    "medical-law-and-ethics",
    "Why do informed consent questions matter in clinical workflow?",
    [
      choice("a", "They relate to respecting patient rights and informed decision-making"),
      choice("b", "They apply only to billing"),
      choice("c", "They remove the need for documentation"),
      choice("d", "They matter only after a procedure is over"),
    ],
    "a",
    "Consent questions are tied to patient rights and appropriate informed decision-making.",
    "Consent protects patient choice.",
    2,
  ),
  question(
    "le-005",
    "medical-law-and-ethics",
    "When a legal or ethical situation feels unclear, which approach is strongest?",
    [
      choice("a", "Protect the patient, follow policy, and escalate appropriately"),
      choice("b", "Ignore the issue if it seems uncomfortable"),
      choice("c", "Make a private rule on the spot"),
      choice("d", "Assume privacy no longer matters"),
    ],
    "a",
    "When doubt appears, strong answers usually protect the patient and follow policy-based escalation.",
    "Protect the patient, then take the safe path.",
    2,
  ),
];
