import type { ExamQuestion } from "@/lib/exams/types";

export const texasCnaExamBank: ExamQuestion[] = [
  {
    id: "ic-001",
    domainSlug: "infection-control-and-safety",
    domainTitle: "Infection Control and Safety",
    prompt: "What should a nurse aide do first before touching a resident?",
    choices: [
      { id: "a", label: "A", text: "Put on gloves only" },
      { id: "b", label: "B", text: "Wash hands or perform hand hygiene" },
      { id: "c", label: "C", text: "Lower the bed" },
      { id: "d", label: "D", text: "Ask another aide for help" },
    ],
    correctChoiceId: "b",
    rationale: "Hand hygiene is the first step in standard precautions before resident contact.",
    memoryTip: "Clean hands first, then care starts.",
    difficulty: 1,
  },
  {
    id: "ic-002",
    domainSlug: "infection-control-and-safety",
    domainTitle: "Infection Control and Safety",
    prompt: "Gloves should be changed:",
    choices: [
      { id: "a", label: "A", text: "Only when they tear" },
      { id: "b", label: "B", text: "Between dirty and clean tasks and between residents" },
      { id: "c", label: "C", text: "Once per shift" },
      { id: "d", label: "D", text: "Only after toileting care" },
    ],
    correctChoiceId: "b",
    rationale: "Gloves are task-specific and must be changed to prevent cross-contamination.",
    memoryTip: "New task, new gloves.",
    difficulty: 1,
  },
  {
    id: "ic-003",
    domainSlug: "infection-control-and-safety",
    domainTitle: "Infection Control and Safety",
    prompt: "When carrying soiled linens, the nurse aide should:",
    choices: [
      { id: "a", label: "A", text: "Hold them away from the uniform" },
      { id: "b", label: "B", text: "Shake them out before bagging" },
      { id: "c", label: "C", text: "Place them on the floor briefly" },
      { id: "d", label: "D", text: "Mix them with clean supplies" },
    ],
    correctChoiceId: "a",
    rationale: "Soiled linens should be handled carefully and kept away from clothing to reduce contamination.",
    memoryTip: "Dirty linen stays off you and off the floor.",
    difficulty: 2,
  },
  {
    id: "pr-001",
    domainSlug: "patient-rights-and-ethics",
    domainTitle: "Patient Rights and Ethics",
    prompt: "A resident has the right to:",
    choices: [
      { id: "a", label: "A", text: "Refuse care after receiving an explanation" },
      { id: "b", label: "B", text: "Be discussed in the hallway" },
      { id: "c", label: "C", text: "Have mail opened by staff" },
      { id: "d", label: "D", text: "Be forced into activities" },
    ],
    correctChoiceId: "a",
    rationale: "Residents keep the right to make informed choices, including refusing care.",
    memoryTip: "Explain first, respect the choice.",
    difficulty: 1,
  },
  {
    id: "pr-002",
    domainSlug: "patient-rights-and-ethics",
    domainTitle: "Patient Rights and Ethics",
    prompt: "If a nurse aide sees a coworker roughly handling a resident, the aide should:",
    choices: [
      { id: "a", label: "A", text: "Wait until the next shift to mention it" },
      { id: "b", label: "B", text: "Report it immediately to the nurse" },
      { id: "c", label: "C", text: "Ignore it if no injury occurred" },
      { id: "d", label: "D", text: "Discuss it with other aides first" },
    ],
    correctChoiceId: "b",
    rationale: "Possible abuse or neglect must be reported right away following facility policy.",
    memoryTip: "Protect first, report fast.",
    difficulty: 2,
  },
  {
    id: "pr-003",
    domainSlug: "patient-rights-and-ethics",
    domainTitle: "Patient Rights and Ethics",
    prompt: "Before giving personal care, the nurse aide should always:",
    choices: [
      { id: "a", label: "A", text: "Close privacy curtains and explain the care" },
      { id: "b", label: "B", text: "Ask the roommate for help" },
      { id: "c", label: "C", text: "Finish quickly without talking" },
      { id: "d", label: "D", text: "Turn on bright lights without warning" },
    ],
    correctChoiceId: "a",
    rationale: "Privacy and explanation support dignity and resident rights.",
    memoryTip: "Privacy plus explanation equals respect.",
    difficulty: 1,
  },
  {
    id: "cm-001",
    domainSlug: "communication-skills",
    domainTitle: "Communication Skills",
    prompt: "Which response best shows therapeutic communication?",
    choices: [
      { id: "a", label: "A", text: "You should not feel that way." },
      { id: "b", label: "B", text: "Tell me more about what is worrying you." },
      { id: "c", label: "C", text: "Everyone has problems." },
      { id: "d", label: "D", text: "Calm down right now." },
    ],
    correctChoiceId: "b",
    rationale: "Open-ended, respectful questions encourage expression and trust.",
    memoryTip: "Invite, do not dismiss.",
    difficulty: 1,
  },
  {
    id: "cm-002",
    domainSlug: "communication-skills",
    domainTitle: "Communication Skills",
    prompt: "A resident with hearing loss is having trouble understanding. The best action is to:",
    choices: [
      { id: "a", label: "A", text: "Shout from the doorway" },
      { id: "b", label: "B", text: "Face the resident and speak clearly" },
      { id: "c", label: "C", text: "Talk quickly to save time" },
      { id: "d", label: "D", text: "Turn away while speaking" },
    ],
    correctChoiceId: "b",
    rationale: "Facing the resident and speaking clearly supports lip-reading and respectful communication.",
    memoryTip: "Face, slow, clear.",
    difficulty: 1,
  },
  {
    id: "cm-003",
    domainSlug: "communication-skills",
    domainTitle: "Communication Skills",
    prompt: "When reporting a resident change to the nurse, the nurse aide should be:",
    choices: [
      { id: "a", label: "A", text: "Vague and brief" },
      { id: "b", label: "B", text: "Objective and specific" },
      { id: "c", label: "C", text: "Emotional and opinion-based" },
      { id: "d", label: "D", text: "Silent unless asked" },
    ],
    correctChoiceId: "b",
    rationale: "Clear, objective reporting helps the nurse act on accurate information.",
    memoryTip: "Report facts, not feelings.",
    difficulty: 2,
  },
  {
    id: "adl-001",
    domainSlug: "personal-care-adls",
    domainTitle: "Personal Care and ADLs",
    prompt: "While feeding a resident, the nurse aide should:",
    choices: [
      { id: "a", label: "A", text: "Keep the resident as flat as possible" },
      { id: "b", label: "B", text: "Offer small bites and allow time to chew" },
      { id: "c", label: "C", text: "Rush to finish before the tray cools" },
      { id: "d", label: "D", text: "Leave the resident alone between bites" },
    ],
    correctChoiceId: "b",
    rationale: "Safe feeding means upright positioning, small bites, and enough time to swallow.",
    memoryTip: "Small bites, slow pace, upright face.",
    difficulty: 1,
  },
  {
    id: "adl-002",
    domainSlug: "personal-care-adls",
    domainTitle: "Personal Care and ADLs",
    prompt: "When giving perineal care, the nurse aide should clean:",
    choices: [
      { id: "a", label: "A", text: "From dirty to clean" },
      { id: "b", label: "B", text: "From front to back" },
      { id: "c", label: "C", text: "With the same area of the cloth repeatedly" },
      { id: "d", label: "D", text: "Only if the resident asks" },
    ],
    correctChoiceId: "b",
    rationale: "Cleaning from front to back helps prevent contamination and infection.",
    memoryTip: "Front to back keeps bacteria back.",
    difficulty: 1,
  },
  {
    id: "adl-003",
    domainSlug: "personal-care-adls",
    domainTitle: "Personal Care and ADLs",
    prompt: "The best way to encourage independence during dressing is to:",
    choices: [
      { id: "a", label: "A", text: "Do the whole task quickly for the resident" },
      { id: "b", label: "B", text: "Let the resident do as much as safely possible" },
      { id: "c", label: "C", text: "Skip the task if it takes too long" },
      { id: "d", label: "D", text: "Choose clothes without asking" },
    ],
    correctChoiceId: "b",
    rationale: "Restorative care includes supporting independence whenever safe.",
    memoryTip: "Assist, do not replace.",
    difficulty: 2,
  },
  {
    id: "vs-001",
    domainSlug: "vital-signs-basics",
    domainTitle: "Vital Signs Basics",
    prompt: "Which finding should be reported to the nurse right away?",
    choices: [
      { id: "a", label: "A", text: "A resident says lunch tasted good" },
      { id: "b", label: "B", text: "A newly measured temperature of 102°F" },
      { id: "c", label: "C", text: "A resident asks for water" },
      { id: "d", label: "D", text: "A scheduled bedtime" },
    ],
    correctChoiceId: "b",
    rationale: "A fever can signal acute illness and should be reported promptly.",
    memoryTip: "Out-of-range vitals do not wait.",
    difficulty: 1,
  },
  {
    id: "vs-002",
    domainSlug: "vital-signs-basics",
    domainTitle: "Vital Signs Basics",
    prompt: "When counting respirations, the nurse aide should:",
    choices: [
      { id: "a", label: "A", text: "Tell the resident to breathe faster" },
      { id: "b", label: "B", text: "Count after taking the pulse so breathing stays natural" },
      { id: "c", label: "C", text: "Estimate based on appearance" },
      { id: "d", label: "D", text: "Count for only five seconds" },
    ],
    correctChoiceId: "b",
    rationale: "Residents may change breathing if they know it is being counted, so discreet observation is best.",
    memoryTip: "Pulse first, breaths second.",
    difficulty: 2,
  },
  {
    id: "vs-003",
    domainSlug: "vital-signs-basics",
    domainTitle: "Vital Signs Basics",
    prompt: "If a blood pressure reading seems very unusual, the nurse aide should first:",
    choices: [
      { id: "a", label: "A", text: "Chart it and move on" },
      { id: "b", label: "B", text: "Recheck according to policy and report" },
      { id: "c", label: "C", text: "Ignore it if the resident feels fine" },
      { id: "d", label: "D", text: "Ask the resident what the usual number is" },
    ],
    correctChoiceId: "b",
    rationale: "Unusual findings should be verified appropriately and reported to the nurse.",
    memoryTip: "Odd vital? Recheck and report.",
    difficulty: 2,
  },
  {
    id: "em-001",
    domainSlug: "emergency-procedures",
    domainTitle: "Emergency Procedures",
    prompt: "If a resident is found on the floor, the nurse aide should first:",
    choices: [
      { id: "a", label: "A", text: "Lift the resident back into bed" },
      { id: "b", label: "B", text: "Stay with the resident and call for the nurse" },
      { id: "c", label: "C", text: "Leave to get linens" },
      { id: "d", label: "D", text: "Offer food and water" },
    ],
    correctChoiceId: "b",
    rationale: "Do not move the resident after a fall until proper assessment and direction are given.",
    memoryTip: "After a fall: stay, call, do not lift.",
    difficulty: 1,
  },
  {
    id: "em-002",
    domainSlug: "emergency-procedures",
    domainTitle: "Emergency Procedures",
    prompt: "In a fire emergency, the nurse aide should follow the facility plan and:",
    choices: [
      { id: "a", label: "A", text: "Finish charting before responding" },
      { id: "b", label: "B", text: "Move residents to safety as directed" },
      { id: "c", label: "C", text: "Open all windows first" },
      { id: "d", label: "D", text: "Use the elevator immediately" },
    ],
    correctChoiceId: "b",
    rationale: "Resident safety and the facility fire response plan guide the aide’s actions.",
    memoryTip: "Safety first, plan first.",
    difficulty: 2,
  },
  {
    id: "doc-001",
    domainSlug: "documentation",
    domainTitle: "Documentation",
    prompt: "Good documentation by a nurse aide should be:",
    choices: [
      { id: "a", label: "A", text: "Objective and timely" },
      { id: "b", label: "B", text: "Based on guesses" },
      { id: "c", label: "C", text: "Shared with visitors" },
      { id: "d", label: "D", text: "Completed by another aide later" },
    ],
    correctChoiceId: "a",
    rationale: "Charting should be factual, timely, and based on actual observations.",
    memoryTip: "Chart facts, chart soon.",
    difficulty: 1,
  },
  {
    id: "doc-002",
    domainSlug: "documentation",
    domainTitle: "Documentation",
    prompt: "A nurse aide notices a new skin tear while giving care. The aide should:",
    choices: [
      { id: "a", label: "A", text: "Ignore it until the end of shift" },
      { id: "b", label: "B", text: "Report it promptly and document per policy" },
      { id: "c", label: "C", text: "Apply ointment without telling anyone" },
      { id: "d", label: "D", text: "Ask the resident to hide it" },
    ],
    correctChoiceId: "b",
    rationale: "Changes in condition must be reported promptly and documented correctly.",
    memoryTip: "Observe, report, document.",
    difficulty: 2,
  },
  {
    id: "mh-001",
    domainSlug: "mental-health-and-social-needs",
    domainTitle: "Mental Health and Social Needs",
    prompt: "A confused resident becomes upset and says, 'I need to go home.' The best response is:",
    choices: [
      { id: "a", label: "A", text: "You already live here now." },
      { id: "b", label: "B", text: "You sound worried. Tell me what you need right now." },
      { id: "c", label: "C", text: "Stop saying that." },
      { id: "d", label: "D", text: "Ignore the statement" },
    ],
    correctChoiceId: "b",
    rationale: "Validation and calm redirection support emotional safety better than arguing.",
    memoryTip: "Validate first, redirect gently.",
    difficulty: 2,
  },
  {
    id: "mh-002",
    domainSlug: "mental-health-and-social-needs",
    domainTitle: "Mental Health and Social Needs",
    prompt: "Social isolation in a resident should be reported because it may signal:",
    choices: [
      { id: "a", label: "A", text: "Improved independence" },
      { id: "b", label: "B", text: "A change in emotional or mental status" },
      { id: "c", label: "C", text: "A normal charting error" },
      { id: "d", label: "D", text: "That the resident wants less privacy" },
    ],
    correctChoiceId: "b",
    rationale: "Withdrawal can point to depression, illness, or another change that should be reported.",
    memoryTip: "Withdrawal is a change worth saying.",
    difficulty: 2,
  },
  {
    id: "bn-001",
    domainSlug: "basic-nursing-skills",
    domainTitle: "Basic Nursing Skills",
    prompt: "To transfer a resident safely, the nurse aide should:",
    choices: [
      { id: "a", label: "A", text: "Use good body mechanics and locked wheels" },
      { id: "b", label: "B", text: "Pull quickly from under the arms" },
      { id: "c", label: "C", text: "Twist at the waist while lifting" },
      { id: "d", label: "D", text: "Skip the gait belt when in a hurry" },
    ],
    correctChoiceId: "a",
    rationale: "Safe transfers use locked equipment, proper positioning, and body mechanics.",
    memoryTip: "Lock, position, protect.",
    difficulty: 1,
  },
  {
    id: "bn-002",
    domainSlug: "basic-nursing-skills",
    domainTitle: "Basic Nursing Skills",
    prompt: "A resident who has been in bed most of the day should be turned and repositioned:",
    choices: [
      { id: "a", label: "A", text: "Only if the resident complains" },
      { id: "b", label: "B", text: "According to the care plan and facility policy" },
      { id: "c", label: "C", text: "Once each shift only" },
      { id: "d", label: "D", text: "After meals only" },
    ],
    correctChoiceId: "b",
    rationale: "Repositioning follows the care plan to protect skin and comfort.",
    memoryTip: "Turn by plan, not by guess.",
    difficulty: 2,
  },
  {
    id: "rc-001",
    domainSlug: "restorative-care",
    domainTitle: "Restorative Care",
    prompt: "Restorative care focuses on:",
    choices: [
      { id: "a", label: "A", text: "Doing everything for the resident" },
      { id: "b", label: "B", text: "Helping the resident keep or improve function" },
      { id: "c", label: "C", text: "Keeping the resident in bed" },
      { id: "d", label: "D", text: "Avoiding all activity" },
    ],
    correctChoiceId: "b",
    rationale: "Restorative care supports ability, movement, and independence.",
    memoryTip: "Restore what the resident can still do.",
    difficulty: 1,
  },
  {
    id: "rc-002",
    domainSlug: "restorative-care",
    domainTitle: "Restorative Care",
    prompt: "During range-of-motion exercises, the nurse aide should:",
    choices: [
      { id: "a", label: "A", text: "Force the joint past resistance" },
      { id: "b", label: "B", text: "Move joints gently and stop if there is pain" },
      { id: "c", label: "C", text: "Skip reporting discomfort" },
      { id: "d", label: "D", text: "Work only one side of the body" },
    ],
    correctChoiceId: "b",
    rationale: "ROM should be slow, gentle, and within tolerance, with pain reported.",
    memoryTip: "Gentle motion, never force.",
    difficulty: 2,
  },
];
