import type { ExamQuestion } from "@/lib/exams/types";

export const expandedDomainExamBank: ExamQuestion[] = [
  {
    id: "adl-101",
    domainSlug: "personal-care-adls",
    domainTitle: "Personal Care and ADLs",
    type: "knowledge",
    prompt: "When giving a bed bath, which area should the CNA wash first?",
    choices: [
      { id: "a", label: "A", text: "The perineal area" },
      { id: "b", label: "B", text: "The face" },
      { id: "c", label: "C", text: "The feet" },
      { id: "d", label: "D", text: "The buttocks" },
    ],
    correctChoiceId: "b",
    rationale: "Bathing usually begins with the cleanest area, such as the face, and moves toward dirtier areas.",
    memoryTip: "Cleanest first, dirtiest last.",
    difficulty: 1,
  },
  {
    id: "adl-102",
    domainSlug: "personal-care-adls",
    domainTitle: "Personal Care and ADLs",
    type: "knowledge",
    prompt: "How often should oral care supplies be kept clean and stored properly?",
    choices: [
      { id: "a", label: "A", text: "Only after family visits" },
      { id: "b", label: "B", text: "After each use" },
      { id: "c", label: "C", text: "Once every few days" },
      { id: "d", label: "D", text: "Only when the resident asks" },
    ],
    correctChoiceId: "b",
    rationale: "Oral care items should be cleaned and stored correctly after each use to reduce contamination.",
    memoryTip: "Use it, clean it, store it.",
    difficulty: 1,
  },
  {
    id: "adl-103",
    domainSlug: "personal-care-adls",
    domainTitle: "Personal Care and ADLs",
    type: "knowledge",
    prompt: "A resident with weakness on one side should usually be dressed starting with the:",
    choices: [
      { id: "a", label: "A", text: "Strong side first" },
      { id: "b", label: "B", text: "Weak side first" },
      { id: "c", label: "C", text: "Legs first every time" },
      { id: "d", label: "D", text: "Arms at the same time" },
    ],
    correctChoiceId: "b",
    rationale: "For dressing, the weak side is usually dressed first to make the task easier and safer.",
    memoryTip: "Dress the weak side first.",
    difficulty: 2,
  },
  {
    id: "adl-104",
    domainSlug: "personal-care-adls",
    domainTitle: "Personal Care and ADLs",
    type: "knowledge",
    prompt: "Why should pillows or positioning devices be used when turning a resident?",
    choices: [
      { id: "a", label: "A", text: "To keep the resident from calling for help" },
      { id: "b", label: "B", text: "To support body alignment and reduce pressure" },
      { id: "c", label: "C", text: "To make the bed look full" },
      { id: "d", label: "D", text: "To keep linens from wrinkling" },
    ],
    correctChoiceId: "b",
    rationale: "Positioning devices help maintain alignment, comfort, and skin protection.",
    memoryTip: "Support alignment, protect skin.",
    difficulty: 2,
  },
  {
    id: "adl-105",
    domainSlug: "personal-care-adls",
    domainTitle: "Personal Care and ADLs",
    type: "knowledge",
    prompt: "What is the best way to protect privacy during grooming care?",
    choices: [
      { id: "a", label: "A", text: "Keep the door open for better light" },
      { id: "b", label: "B", text: "Cover only the area being cared for" },
      { id: "c", label: "C", text: "Ask the roommate to step closer" },
      { id: "d", label: "D", text: "Finish all care before explaining it" },
    ],
    correctChoiceId: "b",
    rationale: "Keeping the resident covered except for the body part being cared for maintains dignity and privacy.",
    memoryTip: "Expose only what you need.",
    difficulty: 1,
  },
  {
    id: "adl-scn-101",
    domainSlug: "personal-care-adls",
    domainTitle: "Personal Care and ADLs",
    type: "scenario",
    prompt:
      "You are helping a resident with a bed bath. The resident says the water feels cold and begins shivering. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Continue quickly so the bath ends sooner" },
      { id: "b", label: "B", text: "Check the water, provide warmth, and make the resident comfortable before continuing" },
      { id: "c", label: "C", text: "Tell the resident cold water wakes people up" },
      { id: "d", label: "D", text: "Skip the bath and leave the room" },
    ],
    correctChoiceId: "b",
    rationale: "The CNA should adjust care for comfort and safety before continuing personal care.",
    memoryTip: "Comfort comes before completion.",
    difficulty: 1,
  },
  {
    id: "adl-scn-102",
    domainSlug: "personal-care-adls",
    domainTitle: "Personal Care and ADLs",
    type: "scenario",
    prompt:
      "While providing oral care, a resident with dentures says the gums feel sore. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Handle the mouth gently and report soreness to the nurse" },
      { id: "b", label: "B", text: "Scrub harder so the gums toughen up" },
      { id: "c", label: "C", text: "Leave the dentures out without cleaning them" },
      { id: "d", label: "D", text: "Tell the resident soreness is expected and not important" },
    ],
    correctChoiceId: "a",
    rationale: "Soreness should be handled gently and reported because it may signal irritation or poor fit.",
    memoryTip: "Gentle care, then report changes.",
    difficulty: 2,
  },
  {
    id: "adl-scn-103",
    domainSlug: "personal-care-adls",
    domainTitle: "Personal Care and ADLs",
    type: "scenario",
    prompt:
      "A resident with right-sided weakness is getting dressed and becomes frustrated trying to put on a shirt. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Encourage the resident to do as much as possible and assist with the weak side first" },
      { id: "b", label: "B", text: "Take over the whole task without explanation" },
      { id: "c", label: "C", text: "Tell the resident to skip getting dressed today" },
      { id: "d", label: "D", text: "Dress the strong side first to save time" },
    ],
    correctChoiceId: "a",
    rationale: "The CNA should promote independence while using proper dressing technique for weakness.",
    memoryTip: "Support independence with safe steps.",
    difficulty: 2,
  },
  {
    id: "adl-scn-104",
    domainSlug: "personal-care-adls",
    domainTitle: "Personal Care and ADLs",
    type: "scenario",
    prompt:
      "You turn a resident to the side and notice the pillow behind the back has slipped away. The resident says the position feels uncomfortable. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Reposition the pillow and check body alignment" },
      { id: "b", label: "B", text: "Tell the resident to wait until the next round" },
      { id: "c", label: "C", text: "Remove all pillows so the resident lies flatter" },
      { id: "d", label: "D", text: "Massage the hip instead of repositioning" },
    ],
    correctChoiceId: "a",
    rationale: "Positioning devices should be adjusted so the resident is aligned, supported, and comfortable.",
    memoryTip: "Realign when support slips.",
    difficulty: 1,
  },
  {
    id: "adl-scn-105",
    domainSlug: "personal-care-adls",
    domainTitle: "Personal Care and ADLs",
    type: "scenario",
    prompt:
      "During morning grooming, a resident says, 'I want to comb my own hair today.' The resident can move the arms but needs extra time. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Allow the resident to do as much as possible and assist only as needed" },
      { id: "b", label: "B", text: "Do it all for the resident because it is faster" },
      { id: "c", label: "C", text: "Tell the resident grooming is staff responsibility" },
      { id: "d", label: "D", text: "Skip grooming altogether" },
    ],
    correctChoiceId: "a",
    rationale: "Residents should be encouraged to do what they can safely do for themselves.",
    memoryTip: "Independence matters in daily care.",
    difficulty: 1,
  },
  {
    id: "em-101",
    domainSlug: "emergency-procedures",
    domainTitle: "Emergency Procedures",
    type: "knowledge",
    prompt: "Which action best helps prevent falls when a resident transfers out of bed?",
    choices: [
      { id: "a", label: "A", text: "Leave the bed in the highest position" },
      { id: "b", label: "B", text: "Lock wheels and make sure footwear is secure" },
      { id: "c", label: "C", text: "Tell the resident to stand quickly" },
      { id: "d", label: "D", text: "Keep the call light out of reach" },
    ],
    correctChoiceId: "b",
    rationale: "Locked equipment and proper footwear reduce fall risk during transfers.",
    memoryTip: "Lock and check before standing.",
    difficulty: 1,
  },
  {
    id: "em-102",
    domainSlug: "emergency-procedures",
    domainTitle: "Emergency Procedures",
    type: "knowledge",
    prompt: "What is the safest response if a resident starts to fall while walking with you?",
    choices: [
      { id: "a", label: "A", text: "Try to hold the resident upright at any cost" },
      { id: "b", label: "B", text: "Ease the resident to the floor while protecting the head" },
      { id: "c", label: "C", text: "Step away to avoid injury to yourself" },
      { id: "d", label: "D", text: "Pull on the resident's arms to stop the fall" },
    ],
    correctChoiceId: "b",
    rationale: "Trying to stop a fall upright can injure both people; controlled lowering is safer.",
    memoryTip: "Guide down, do not yank up.",
    difficulty: 2,
  },
  {
    id: "em-103",
    domainSlug: "emergency-procedures",
    domainTitle: "Emergency Procedures",
    type: "knowledge",
    prompt: "Which statement about restraints is correct for a CNA?",
    choices: [
      { id: "a", label: "A", text: "A CNA may apply restraints whenever a resident wanders" },
      { id: "b", label: "B", text: "Restraints require proper authorization and ongoing monitoring" },
      { id: "c", label: "C", text: "Restraints are a normal substitute for supervision" },
      { id: "d", label: "D", text: "A family request alone is enough to start restraints" },
    ],
    correctChoiceId: "b",
    rationale: "Restraints are tightly controlled and cannot be used casually or without proper direction.",
    memoryTip: "Restraints are limited and monitored.",
    difficulty: 2,
  },
  {
    id: "em-104",
    domainSlug: "emergency-procedures",
    domainTitle: "Emergency Procedures",
    type: "knowledge",
    prompt: "If a resident with a history of wandering cannot be found on the unit, the CNA should first:",
    choices: [
      { id: "a", label: "A", text: "Wait to see whether the resident returns alone" },
      { id: "b", label: "B", text: "Report it immediately according to elopement policy" },
      { id: "c", label: "C", text: "Ask the roommate to search outside" },
      { id: "d", label: "D", text: "Document it after the shift is over" },
    ],
    correctChoiceId: "b",
    rationale: "A missing at-risk resident is an urgent safety issue and should be reported at once.",
    memoryTip: "Missing resident means immediate report.",
    difficulty: 2,
  },
  {
    id: "em-105",
    domainSlug: "emergency-procedures",
    domainTitle: "Emergency Procedures",
    type: "knowledge",
    prompt: "Which fire safety action is correct in a long-term care setting?",
    choices: [
      { id: "a", label: "A", text: "Use elevators to move residents faster" },
      { id: "b", label: "B", text: "Follow the facility fire plan and move residents as directed" },
      { id: "c", label: "C", text: "Open every window in the hallway first" },
      { id: "d", label: "D", text: "Return to finish charting before helping residents" },
    ],
    correctChoiceId: "b",
    rationale: "The CNA should follow the facility's fire procedure and prioritize resident safety.",
    memoryTip: "Follow the plan, protect residents.",
    difficulty: 1,
  },
  {
    id: "em-scn-101",
    domainSlug: "emergency-procedures",
    domainTitle: "Emergency Procedures",
    type: "scenario",
    prompt:
      "A resident who is supposed to use nonskid shoes stands up in socks and starts walking toward the bathroom. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Assist the resident safely and provide proper footwear" },
      { id: "b", label: "B", text: "Let the resident go alone to preserve independence" },
      { id: "c", label: "C", text: "Scold the resident loudly from across the room" },
      { id: "d", label: "D", text: "Wait outside the bathroom and check back later" },
    ],
    correctChoiceId: "a",
    rationale: "The CNA should act to reduce immediate fall risk while still supporting safe independence.",
    memoryTip: "Protect first, then proceed safely.",
    difficulty: 1,
  },
  {
    id: "em-scn-102",
    domainSlug: "emergency-procedures",
    domainTitle: "Emergency Procedures",
    type: "scenario",
    prompt:
      "During supper, a resident begins coughing forcefully after taking a large bite and then cannot speak. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Act right away using the facility choking response and call for help" },
      { id: "b", label: "B", text: "Give the resident another drink" },
      { id: "c", label: "C", text: "Wait a few minutes to see if it passes" },
      { id: "d", label: "D", text: "Take the resident back to bed first" },
    ],
    correctChoiceId: "a",
    rationale: "A silent resident who cannot clear the airway requires immediate emergency response.",
    memoryTip: "No speech means no waiting.",
    difficulty: 2,
  },
  {
    id: "em-scn-103",
    domainSlug: "emergency-procedures",
    domainTitle: "Emergency Procedures",
    type: "scenario",
    prompt:
      "You see smoke coming from a trash can in a resident room. The resident is in bed and awake. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Follow the fire response plan and move the resident to safety as directed" },
      { id: "b", label: "B", text: "Ignore it if the flame is small" },
      { id: "c", label: "C", text: "Finish morning care before reporting it" },
      { id: "d", label: "D", text: "Open the door wide and fan the smoke into the hallway" },
    ],
    correctChoiceId: "a",
    rationale: "Visible smoke is an active safety emergency that requires immediate policy-based response.",
    memoryTip: "Smoke means act by plan.",
    difficulty: 2,
  },
  {
    id: "em-scn-104",
    domainSlug: "emergency-procedures",
    domainTitle: "Emergency Procedures",
    type: "scenario",
    prompt:
      "A family member asks you to tie a resident into a chair 'just for a little while' because the resident keeps trying to get up. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Refuse to do it and report the request to the nurse" },
      { id: "b", label: "B", text: "Do it if the family promises to watch the resident" },
      { id: "c", label: "C", text: "Use a sheet to keep the resident in place" },
      { id: "d", label: "D", text: "Ask another aide to decide" },
    ],
    correctChoiceId: "a",
    rationale: "A CNA cannot apply restraints without proper authorization and direction.",
    memoryTip: "No informal restraints.",
    difficulty: 2,
  },
  {
    id: "em-scn-105",
    domainSlug: "emergency-procedures",
    domainTitle: "Emergency Procedures",
    type: "scenario",
    prompt:
      "You notice an exit alarm sounding and a resident with dementia is moving toward the outside door saying, 'I have to catch my bus.' What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Approach calmly, redirect the resident, and follow elopement safety procedures" },
      { id: "b", label: "B", text: "Shout from the desk for the resident to stop" },
      { id: "c", label: "C", text: "Lock the resident in the room for the rest of the day" },
      { id: "d", label: "D", text: "Ignore it if the resident has not reached the door yet" },
    ],
    correctChoiceId: "a",
    rationale: "Calm redirection and immediate response help prevent unsafe wandering or elopement.",
    memoryTip: "Redirect early and follow policy.",
    difficulty: 2,
  },
  {
    id: "ic-101",
    domainSlug: "infection-control-and-safety",
    domainTitle: "Infection Control and Safety",
    type: "knowledge",
    prompt: "When should a CNA perform hand hygiene during resident care?",
    choices: [
      { id: "a", label: "A", text: "Only at the start of the shift" },
      { id: "b", label: "B", text: "Before and after resident contact and after glove removal" },
      { id: "c", label: "C", text: "Only after contact with blood" },
      { id: "d", label: "D", text: "Only when hands look dirty" },
    ],
    correctChoiceId: "b",
    rationale: "Hand hygiene is required at multiple points in care, not only when visible soil is present.",
    memoryTip: "Before, after, and after gloves.",
    difficulty: 1,
  },
  {
    id: "ic-102",
    domainSlug: "infection-control-and-safety",
    domainTitle: "Infection Control and Safety",
    type: "knowledge",
    prompt: "Which PPE should be chosen based on the expected task and possible exposure?",
    choices: [
      { id: "a", label: "A", text: "Only gloves for every task" },
      { id: "b", label: "B", text: "The PPE indicated by standard or transmission-based precautions" },
      { id: "c", label: "C", text: "No PPE unless the resident is coughing" },
      { id: "d", label: "D", text: "The same PPE for an entire shift" },
    ],
    correctChoiceId: "b",
    rationale: "PPE is selected based on the care task and isolation or exposure risk.",
    memoryTip: "Match PPE to the risk.",
    difficulty: 2,
  },
  {
    id: "ic-103",
    domainSlug: "infection-control-and-safety",
    domainTitle: "Infection Control and Safety",
    type: "knowledge",
    prompt: "What is the correct action when removing a gown after isolation care?",
    choices: [
      { id: "a", label: "A", text: "Touch the front of the gown against your uniform" },
      { id: "b", label: "B", text: "Remove it carefully to avoid contaminating yourself" },
      { id: "c", label: "C", text: "Wear it into the next resident's room" },
      { id: "d", label: "D", text: "Hang it on a chair for later use" },
    ],
    correctChoiceId: "b",
    rationale: "Contaminated PPE should be removed carefully to prevent self-contamination.",
    memoryTip: "Take PPE off without spreading germs.",
    difficulty: 2,
  },
  {
    id: "ic-104",
    domainSlug: "infection-control-and-safety",
    domainTitle: "Infection Control and Safety",
    type: "knowledge",
    prompt: "Why should soiled linens never be shaken in the room?",
    choices: [
      { id: "a", label: "A", text: "It makes folding harder" },
      { id: "b", label: "B", text: "It can spread microorganisms into the air" },
      { id: "c", label: "C", text: "It wrinkles the clean linen cart" },
      { id: "d", label: "D", text: "It causes linens to dry too fast" },
    ],
    correctChoiceId: "b",
    rationale: "Shaking linens can spread contaminants and should be avoided.",
    memoryTip: "Do not shake germs loose.",
    difficulty: 1,
  },
  {
    id: "ic-105",
    domainSlug: "infection-control-and-safety",
    domainTitle: "Infection Control and Safety",
    type: "knowledge",
    prompt: "Standard precautions should be used with:",
    choices: [
      { id: "a", label: "A", text: "Only residents who are in isolation" },
      { id: "b", label: "B", text: "All residents" },
      { id: "c", label: "C", text: "Only residents with known infections" },
      { id: "d", label: "D", text: "Only residents receiving wound care" },
    ],
    correctChoiceId: "b",
    rationale: "Standard precautions apply to the care of every resident.",
    memoryTip: "Standard means everyone.",
    difficulty: 1,
  },
  {
    id: "ic-scn-101",
    domainSlug: "infection-control-and-safety",
    domainTitle: "Infection Control and Safety",
    type: "scenario",
    prompt:
      "You are changing an incontinent brief and then need to help the same resident with oral care. What should the CNA do before beginning oral care?",
    choices: [
      { id: "a", label: "A", text: "Keep the same gloves on to save time" },
      { id: "b", label: "B", text: "Remove gloves, clean hands, and use clean supplies and gloves as needed" },
      { id: "c", label: "C", text: "Wipe the gloves on a towel and continue" },
      { id: "d", label: "D", text: "Skip hand hygiene because it is the same resident" },
    ],
    correctChoiceId: "b",
    rationale: "Moving from a dirty task to a clean task requires hand hygiene and clean equipment.",
    memoryTip: "Dirty to clean means reset first.",
    difficulty: 2,
  },
  {
    id: "ic-scn-102",
    domainSlug: "infection-control-and-safety",
    domainTitle: "Infection Control and Safety",
    type: "scenario",
    prompt:
      "A resident on isolation precautions asks why you are putting on a gown and gloves before entering. What should the CNA say?",
    choices: [
      { id: "a", label: "A", text: "It helps protect you and others while following the care plan" },
      { id: "b", label: "B", text: "Because all residents are treated as dangerous" },
      { id: "c", label: "C", text: "Because I do not want to touch anything in your room" },
      { id: "d", label: "D", text: "The supplies are required only for inspection days" },
    ],
    correctChoiceId: "a",
    rationale: "The CNA should explain precautions respectfully and accurately.",
    memoryTip: "Explain protection with respect.",
    difficulty: 1,
  },
  {
    id: "ic-scn-103",
    domainSlug: "infection-control-and-safety",
    domainTitle: "Infection Control and Safety",
    type: "scenario",
    prompt:
      "While making an occupied bed, a soiled linen touches your uniform. What should the CNA do next?",
    choices: [
      { id: "a", label: "A", text: "Continue the task and change clothing or follow policy as directed after handling the contamination safely" },
      { id: "b", label: "B", text: "Ignore it because uniforms are expected to get dirty" },
      { id: "c", label: "C", text: "Shake the uniform sleeve out over the bed" },
      { id: "d", label: "D", text: "Wipe the uniform with a washcloth and keep going" },
    ],
    correctChoiceId: "a",
    rationale: "Contaminated clothing and linens should be handled safely according to infection control policy.",
    memoryTip: "Contain contamination, then follow policy.",
    difficulty: 2,
  },
  {
    id: "ic-scn-104",
    domainSlug: "infection-control-and-safety",
    domainTitle: "Infection Control and Safety",
    type: "scenario",
    prompt:
      "You finish emptying a urinary drainage bag and notice a small splash on your glove. The resident asks you to hand over dentures right away. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Remove gloves, perform hand hygiene, and use clean technique before touching the dentures" },
      { id: "b", label: "B", text: "Hand over the dentures with the same gloves because the resident is waiting" },
      { id: "c", label: "C", text: "Place the dentures on the bed and let the resident pick them up" },
      { id: "d", label: "D", text: "Rinse the gloves and continue" },
    ],
    correctChoiceId: "a",
    rationale: "The CNA must avoid cross-contaminating clean items after a body fluid task.",
    memoryTip: "Body fluid task ends before clean item touch.",
    difficulty: 2,
  },
  {
    id: "ic-scn-105",
    domainSlug: "infection-control-and-safety",
    domainTitle: "Infection Control and Safety",
    type: "scenario",
    prompt:
      "A resident begins sneezing repeatedly while you are helping with feeding. The resident does not cover the mouth and coughs over the tray. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Pause, handle the situation using hand hygiene and clean replacement items before resuming care" },
      { id: "b", label: "B", text: "Keep serving the food because the meal is already there" },
      { id: "c", label: "C", text: "Use the same utensils after wiping them on a napkin" },
      { id: "d", label: "D", text: "Leave the room without saying anything" },
    ],
    correctChoiceId: "a",
    rationale: "Contaminated food items and surfaces should be managed safely before care continues.",
    memoryTip: "Pause and reset when contamination happens.",
    difficulty: 2,
  },
  {
    id: "pr-101",
    domainSlug: "patient-rights-and-ethics",
    domainTitle: "Patient Rights and Ethics",
    type: "knowledge",
    prompt: "Which statement best supports HIPAA and confidentiality?",
    choices: [
      { id: "a", label: "A", text: "Share resident information only with staff involved in care and only as needed" },
      { id: "b", label: "B", text: "Discuss resident care with family in the hallway if they ask" },
      { id: "c", label: "C", text: "Read charts in the dining room to stay caught up" },
      { id: "d", label: "D", text: "Tell another resident about a roommate's diagnosis" },
    ],
    correctChoiceId: "a",
    rationale: "Confidential information must be shared only appropriately and privately.",
    memoryTip: "Need to know, not nice to know.",
    difficulty: 1,
  },
  {
    id: "pr-102",
    domainSlug: "patient-rights-and-ethics",
    domainTitle: "Patient Rights and Ethics",
    type: "knowledge",
    prompt: "What should a CNA do if an alert resident refuses scheduled morning care?",
    choices: [
      { id: "a", label: "A", text: "Respect the refusal after explanation and report it according to policy" },
      { id: "b", label: "B", text: "Perform the care anyway because it is on the assignment" },
      { id: "c", label: "C", text: "Argue with the resident until the resident gives in" },
      { id: "d", label: "D", text: "Tell the resident future care will be withheld" },
    ],
    correctChoiceId: "a",
    rationale: "Residents have the right to refuse care, and refusals should be handled respectfully.",
    memoryTip: "Explain, respect, report.",
    difficulty: 2,
  },
  {
    id: "pr-103",
    domainSlug: "patient-rights-and-ethics",
    domainTitle: "Patient Rights and Ethics",
    type: "knowledge",
    prompt: "Which action best protects a resident's dignity during toileting care?",
    choices: [
      { id: "a", label: "A", text: "Provide privacy, explain the care, and avoid unnecessary exposure" },
      { id: "b", label: "B", text: "Leave the door open so help is easier to find" },
      { id: "c", label: "C", text: "Rush the resident to finish before speaking" },
      { id: "d", label: "D", text: "Discuss the resident's needs with others in the hallway" },
    ],
    correctChoiceId: "a",
    rationale: "Dignity is protected when privacy and respectful explanation are maintained.",
    memoryTip: "Privacy and respect preserve dignity.",
    difficulty: 1,
  },
  {
    id: "pr-104",
    domainSlug: "patient-rights-and-ethics",
    domainTitle: "Patient Rights and Ethics",
    type: "knowledge",
    prompt: "Which situation should be reported immediately as possible abuse?",
    choices: [
      { id: "a", label: "A", text: "A resident says a staff member hit the arm during care" },
      { id: "b", label: "B", text: "A resident asks for a different blanket" },
      { id: "c", label: "C", text: "A resident is sleepy after lunch" },
      { id: "d", label: "D", text: "A family member brings flowers" },
    ],
    correctChoiceId: "a",
    rationale: "Any possible physical abuse allegation must be reported right away.",
    memoryTip: "Possible abuse means immediate report.",
    difficulty: 1,
  },
  {
    id: "pr-105",
    domainSlug: "patient-rights-and-ethics",
    domainTitle: "Patient Rights and Ethics",
    type: "knowledge",
    prompt: "Why is it important for a CNA to knock before entering a resident's room?",
    choices: [
      { id: "a", label: "A", text: "It respects privacy and personal space" },
      { id: "b", label: "B", text: "It proves the CNA is on time" },
      { id: "c", label: "C", text: "It helps other staff hear where the CNA is" },
      { id: "d", label: "D", text: "It avoids having to introduce yourself" },
    ],
    correctChoiceId: "a",
    rationale: "Knocking before entry supports resident rights, dignity, and privacy.",
    memoryTip: "Knock before you cross the line.",
    difficulty: 1,
  },
  {
    id: "pr-scn-101",
    domainSlug: "patient-rights-and-ethics",
    domainTitle: "Patient Rights and Ethics",
    type: "scenario",
    prompt:
      "A visitor asks, 'What exactly is wrong with my father's roommate?' What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Say you cannot share another resident's private information" },
      { id: "b", label: "B", text: "Answer briefly because the visitor seems concerned" },
      { id: "c", label: "C", text: "Point to the roommate's chart" },
      { id: "d", label: "D", text: "Ask another resident to explain it" },
    ],
    correctChoiceId: "a",
    rationale: "The CNA must protect confidential information and not share it with unauthorized people.",
    memoryTip: "Private information stays private.",
    difficulty: 1,
  },
  {
    id: "pr-scn-102",
    domainSlug: "patient-rights-and-ethics",
    domainTitle: "Patient Rights and Ethics",
    type: "scenario",
    prompt:
      "A resident says, 'Do not give me my bath until my daughter visits.' The resident is alert and understands the decision. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Respect the choice, report it as needed, and offer care later if appropriate" },
      { id: "b", label: "B", text: "Tell the resident visits are not a valid reason to refuse care" },
      { id: "c", label: "C", text: "Force the bath because supplies are already ready" },
      { id: "d", label: "D", text: "Threaten to chart that the resident was difficult" },
    ],
    correctChoiceId: "a",
    rationale: "An informed resident's refusal should be respected and handled according to policy.",
    memoryTip: "Choice first, pressure never.",
    difficulty: 2,
  },
  {
    id: "pr-scn-103",
    domainSlug: "patient-rights-and-ethics",
    domainTitle: "Patient Rights and Ethics",
    type: "scenario",
    prompt:
      "You hear a coworker mock a resident's speech in the hallway, and the resident looks embarrassed. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Address the concern and report the disrespectful behavior to the nurse or supervisor" },
      { id: "b", label: "B", text: "Laugh so the coworker does not feel awkward" },
      { id: "c", label: "C", text: "Ignore it because no physical harm occurred" },
      { id: "d", label: "D", text: "Repeat the joke later to other aides" },
    ],
    correctChoiceId: "a",
    rationale: "Humiliating or demeaning treatment violates resident dignity and should be reported.",
    memoryTip: "Dignity violations still count.",
    difficulty: 2,
  },
  {
    id: "pr-scn-104",
    domainSlug: "patient-rights-and-ethics",
    domainTitle: "Patient Rights and Ethics",
    type: "scenario",
    prompt:
      "A resident quietly tells you, 'My grandson took my wallet again.' The resident seems afraid and asks you not to make trouble. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Take the concern seriously and report it right away according to policy" },
      { id: "b", label: "B", text: "Promise to keep it secret" },
      { id: "c", label: "C", text: "Tell the resident it is a family matter and not your concern" },
      { id: "d", label: "D", text: "Wait until several days have passed to see whether it happens again" },
    ],
    correctChoiceId: "a",
    rationale: "Possible exploitation or theft should be reported immediately for resident protection.",
    memoryTip: "Protect even when the resident is afraid.",
    difficulty: 2,
  },
  {
    id: "pr-scn-105",
    domainSlug: "patient-rights-and-ethics",
    domainTitle: "Patient Rights and Ethics",
    type: "scenario",
    prompt:
      "A resident says, 'Please do not talk about my diagnosis while my family is in the room.' What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Honor the request and keep health information private" },
      { id: "b", label: "B", text: "Explain that families are always allowed to hear everything" },
      { id: "c", label: "C", text: "Speak louder so the family can understand clearly" },
      { id: "d", label: "D", text: "Tell the family after leaving the room" },
    ],
    correctChoiceId: "a",
    rationale: "The resident's privacy preferences should be respected within policy and role.",
    memoryTip: "Resident privacy guides the conversation.",
    difficulty: 1,
  },
  {
    id: "cm-101",
    domainSlug: "communication-skills",
    domainTitle: "Communication Skills",
    type: "knowledge",
    prompt: "When charting care, the CNA should record:",
    choices: [
      { id: "a", label: "A", text: "Objective facts and observations" },
      { id: "b", label: "B", text: "Personal opinions about the resident" },
      { id: "c", label: "C", text: "Guesses about why the resident acted a certain way" },
      { id: "d", label: "D", text: "Information another aide said might be true" },
    ],
    correctChoiceId: "a",
    rationale: "Charting must be factual, accurate, and based on direct observation.",
    memoryTip: "Chart facts, not stories.",
    difficulty: 1,
  },
  {
    id: "cm-102",
    domainSlug: "communication-skills",
    domainTitle: "Communication Skills",
    type: "knowledge",
    prompt: "Which report to the nurse is best?",
    choices: [
      { id: "a", label: "A", text: "Mr. Hall seems weird today" },
      { id: "b", label: "B", text: "Mr. Hall ate only two bites at lunch and says he feels nauseated" },
      { id: "c", label: "C", text: "I do not think Mr. Hall likes the food" },
      { id: "d", label: "D", text: "Maybe Mr. Hall is just having a bad day" },
    ],
    correctChoiceId: "b",
    rationale: "A good report is specific, objective, and helpful for clinical follow-up.",
    memoryTip: "Specific beats vague.",
    difficulty: 1,
  },
  {
    id: "cm-103",
    domainSlug: "communication-skills",
    domainTitle: "Communication Skills",
    type: "knowledge",
    prompt: "What is the best way to communicate with an angry resident?",
    choices: [
      { id: "a", label: "A", text: "Stay calm, listen, and respond respectfully" },
      { id: "b", label: "B", text: "Match the resident's tone so you stay in control" },
      { id: "c", label: "C", text: "Argue until the resident stops" },
      { id: "d", label: "D", text: "Walk away without explanation" },
    ],
    correctChoiceId: "a",
    rationale: "Calm, respectful listening helps reduce tension and supports therapeutic communication.",
    memoryTip: "Stay calm to lower the heat.",
    difficulty: 1,
  },
  {
    id: "cm-104",
    domainSlug: "communication-skills",
    domainTitle: "Communication Skills",
    type: "knowledge",
    prompt: "When speaking with a resident who has difficulty understanding, the CNA should:",
    choices: [
      { id: "a", label: "A", text: "Use simple explanations and allow time for response" },
      { id: "b", label: "B", text: "Talk faster to keep the resident focused" },
      { id: "c", label: "C", text: "Use long medical words to be accurate" },
      { id: "d", label: "D", text: "Repeat the same sentence louder and louder" },
    ],
    correctChoiceId: "a",
    rationale: "Simple, clear communication and patience improve understanding.",
    memoryTip: "Simple and slow helps understanding grow.",
    difficulty: 1,
  },
  {
    id: "cm-105",
    domainSlug: "communication-skills",
    domainTitle: "Communication Skills",
    type: "knowledge",
    prompt: "Which statement about family communication is correct for a CNA?",
    choices: [
      { id: "a", label: "A", text: "Answer within your role and refer clinical questions to the nurse" },
      { id: "b", label: "B", text: "Give any medical explanation the family requests" },
      { id: "c", label: "C", text: "Ignore families because they are not part of care" },
      { id: "d", label: "D", text: "Share another resident's experience to reassure them" },
    ],
    correctChoiceId: "a",
    rationale: "The CNA should communicate respectfully but stay within scope and refer clinical concerns appropriately.",
    memoryTip: "Be helpful, stay in role.",
    difficulty: 2,
  },
  {
    id: "cm-scn-101",
    domainSlug: "communication-skills",
    domainTitle: "Communication Skills",
    type: "scenario",
    prompt:
      "A resident says, 'I feel more short of breath than usual.' The nurse is passing medications nearby. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Report the resident's statement to the nurse immediately" },
      { id: "b", label: "B", text: "Wait until the end of the shift to avoid interrupting" },
      { id: "c", label: "C", text: "Tell the resident to rest and not mention it again" },
      { id: "d", label: "D", text: "Chart it later without telling anyone" },
    ],
    correctChoiceId: "a",
    rationale: "A change in breathing is urgent information that should be communicated promptly.",
    memoryTip: "Breathing changes do not wait.",
    difficulty: 1,
  },
  {
    id: "cm-scn-102",
    domainSlug: "communication-skills",
    domainTitle: "Communication Skills",
    type: "scenario",
    prompt:
      "A family member asks whether a resident's confusion means the resident is 'losing it.' What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Respond respectfully within your role and direct clinical concerns to the nurse" },
      { id: "b", label: "B", text: "Agree and describe other confused residents" },
      { id: "c", label: "C", text: "Guess at the cause to reassure the family" },
      { id: "d", label: "D", text: "Tell the family not to ask questions" },
    ],
    correctChoiceId: "a",
    rationale: "The CNA should be respectful, avoid guessing, and refer medical interpretation to licensed staff.",
    memoryTip: "Answer kindly, not beyond scope.",
    difficulty: 2,
  },
  {
    id: "cm-scn-103",
    domainSlug: "communication-skills",
    domainTitle: "Communication Skills",
    type: "scenario",
    prompt:
      "A resident begins yelling, 'No one ever listens to me!' during morning care. What should the CNA do first?",
    choices: [
      { id: "a", label: "A", text: "Pause, listen calmly, and acknowledge the resident's feelings" },
      { id: "b", label: "B", text: "Tell the resident to stop yelling or care will end" },
      { id: "c", label: "C", text: "Argue that staff do listen" },
      { id: "d", label: "D", text: "Walk out and come back later without saying anything" },
    ],
    correctChoiceId: "a",
    rationale: "Acknowledging emotion and staying calm can de-escalate the situation and preserve trust.",
    memoryTip: "Calm listening opens the door.",
    difficulty: 1,
  },
  {
    id: "cm-scn-104",
    domainSlug: "communication-skills",
    domainTitle: "Communication Skills",
    type: "scenario",
    prompt:
      "While charting, you realize you forgot to record a resident's intake from lunch. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Correct the omission according to policy using accurate information" },
      { id: "b", label: "B", text: "Guess a likely amount and chart it" },
      { id: "c", label: "C", text: "Leave it blank and say nothing" },
      { id: "d", label: "D", text: "Ask another aide to sign your name to the entry" },
    ],
    correctChoiceId: "a",
    rationale: "Documentation errors or omissions should be corrected properly and honestly.",
    memoryTip: "Fix charting honestly, not creatively.",
    difficulty: 2,
  },
  {
    id: "cm-scn-105",
    domainSlug: "communication-skills",
    domainTitle: "Communication Skills",
    type: "scenario",
    prompt:
      "A resident with limited English is pointing to the water pitcher and looking frustrated. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Use calm communication, gestures, and available language support to meet the need safely" },
      { id: "b", label: "B", text: "Ignore the resident until someone else arrives" },
      { id: "c", label: "C", text: "Speak louder in English until the resident understands" },
      { id: "d", label: "D", text: "Assume the resident wants something else and leave" },
    ],
    correctChoiceId: "a",
    rationale: "The CNA should use available communication supports and respectful observation to understand needs.",
    memoryTip: "Bridge the gap with calm support.",
    difficulty: 2,
  },
  {
    id: "bn-101",
    domainSlug: "basic-nursing-skills",
    domainTitle: "Basic Nursing Skills",
    type: "knowledge",
    prompt: "Before taking an oral temperature, the CNA should make sure the resident has not had hot or cold liquids recently because it can:",
    choices: [
      { id: "a", label: "A", text: "Change the reading" },
      { id: "b", label: "B", text: "Improve circulation" },
      { id: "c", label: "C", text: "Prevent charting" },
      { id: "d", label: "D", text: "Lower pulse rate" },
    ],
    correctChoiceId: "a",
    rationale: "Recent hot or cold intake can affect the accuracy of an oral temperature.",
    memoryTip: "Recent drinks can change the number.",
    difficulty: 1,
  },
  {
    id: "bn-102",
    domainSlug: "basic-nursing-skills",
    domainTitle: "Basic Nursing Skills",
    type: "knowledge",
    prompt: "When assisting with range-of-motion exercises, the CNA should:",
    choices: [
      { id: "a", label: "A", text: "Move joints slowly and stop with pain or resistance" },
      { id: "b", label: "B", text: "Force movement to improve flexibility faster" },
      { id: "c", label: "C", text: "Do the exercises only on the stronger side" },
      { id: "d", label: "D", text: "Skip reporting discomfort if the exercise was completed" },
    ],
    correctChoiceId: "a",
    rationale: "ROM should be gentle and safe, and pain or resistance should not be forced through.",
    memoryTip: "Gentle motion, never force.",
    difficulty: 1,
  },
  {
    id: "bn-103",
    domainSlug: "basic-nursing-skills",
    domainTitle: "Basic Nursing Skills",
    type: "knowledge",
    prompt: "Which observation about a urinary catheter should be reported to the nurse?",
    choices: [
      { id: "a", label: "A", text: "Tubing is looped and urine is not draining well" },
      { id: "b", label: "B", text: "The drainage bag is below bladder level" },
      { id: "c", label: "C", text: "The tubing is secured according to policy" },
      { id: "d", label: "D", text: "The resident is lying on the back" },
    ],
    correctChoiceId: "a",
    rationale: "Kinked or looped tubing can block drainage and should be corrected and reported as needed.",
    memoryTip: "Poor flow needs attention.",
    difficulty: 2,
  },
  {
    id: "bn-104",
    domainSlug: "basic-nursing-skills",
    domainTitle: "Basic Nursing Skills",
    type: "knowledge",
    prompt: "What is the safest resident position for feeding assistance unless the care plan says otherwise?",
    choices: [
      { id: "a", label: "A", text: "Flat on the back" },
      { id: "b", label: "B", text: "Upright or as high as tolerated" },
      { id: "c", label: "C", text: "On the stomach" },
      { id: "d", label: "D", text: "Low with the head turned away" },
    ],
    correctChoiceId: "b",
    rationale: "An upright position lowers aspiration risk during feeding.",
    memoryTip: "Up for meals helps protect the airway.",
    difficulty: 1,
  },
  {
    id: "bn-105",
    domainSlug: "basic-nursing-skills",
    domainTitle: "Basic Nursing Skills",
    type: "knowledge",
    prompt: "When walking with a resident using a gait belt, the CNA should generally walk:",
    choices: [
      { id: "a", label: "A", text: "Several steps ahead to lead the way" },
      { id: "b", label: "B", text: "Slightly behind and to the side for support" },
      { id: "c", label: "C", text: "Directly behind without touching the belt" },
      { id: "d", label: "D", text: "On the stronger side only and out of reach" },
    ],
    correctChoiceId: "b",
    rationale: "This position allows the CNA to support balance while promoting safe ambulation.",
    memoryTip: "Stay close enough to steady safely.",
    difficulty: 2,
  },
  {
    id: "bn-scn-101",
    domainSlug: "basic-nursing-skills",
    domainTitle: "Basic Nursing Skills",
    type: "scenario",
    prompt:
      "You count a resident's pulse and get a result much lower than usual for that resident. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Recheck according to policy and report the unusual finding to the nurse" },
      { id: "b", label: "B", text: "Chart it and say nothing because it may be normal today" },
      { id: "c", label: "C", text: "Ask the resident to exercise and then recheck later" },
      { id: "d", label: "D", text: "Ignore the number if the resident is sleeping" },
    ],
    correctChoiceId: "a",
    rationale: "Unexpected vital sign findings should be verified appropriately and reported.",
    memoryTip: "Odd vital? Recheck, then report.",
    difficulty: 2,
  },
  {
    id: "bn-scn-102",
    domainSlug: "basic-nursing-skills",
    domainTitle: "Basic Nursing Skills",
    type: "scenario",
    prompt:
      "A resident with a catheter complains that the tubing feels tight while turning in bed. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Check the tubing and drainage bag position, relieve tension, and report problems as needed" },
      { id: "b", label: "B", text: "Clamp the tubing so it stops pulling" },
      { id: "c", label: "C", text: "Lift the drainage bag onto the mattress" },
      { id: "d", label: "D", text: "Tell the resident not to move so much" },
    ],
    correctChoiceId: "a",
    rationale: "Tubing should not pull, kink, or be placed above bladder level.",
    memoryTip: "Relieve tension, protect drainage.",
    difficulty: 2,
  },
  {
    id: "bn-scn-103",
    domainSlug: "basic-nursing-skills",
    domainTitle: "Basic Nursing Skills",
    type: "scenario",
    prompt:
      "A resident coughs after each bite while you are helping with lunch. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Stop feeding, keep the resident upright, and report the swallowing concern" },
      { id: "b", label: "B", text: "Keep feeding quickly so the tray does not get cold" },
      { id: "c", label: "C", text: "Lay the resident back and offer a bigger sip of water" },
      { id: "d", label: "D", text: "Tell the resident coughing is normal and continue" },
    ],
    correctChoiceId: "a",
    rationale: "Coughing with feeding may signal aspiration risk and should be addressed immediately.",
    memoryTip: "Coughing at meals means pause and report.",
    difficulty: 2,
  },
  {
    id: "bn-scn-104",
    domainSlug: "basic-nursing-skills",
    domainTitle: "Basic Nursing Skills",
    type: "scenario",
    prompt:
      "You are assisting a resident to ambulate in the hall. The resident says the left leg feels weak and begins leaning toward you. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Support the resident with the gait belt and guide to a safe seat or lower as needed" },
      { id: "b", label: "B", text: "Tell the resident to push through it and keep walking" },
      { id: "c", label: "C", text: "Let go of the gait belt so the resident can rebalance independently" },
      { id: "d", label: "D", text: "Turn away to call for help first" },
    ],
    correctChoiceId: "a",
    rationale: "During ambulation, the CNA must maintain control and prioritize a safe outcome.",
    memoryTip: "Keep support until the resident is safe.",
    difficulty: 2,
  },
  {
    id: "bn-scn-105",
    domainSlug: "basic-nursing-skills",
    domainTitle: "Basic Nursing Skills",
    type: "scenario",
    prompt:
      "While helping with passive range-of-motion exercises, a resident says, 'That hurts when you move my shoulder that high.' What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Stop the movement and report the pain to the nurse" },
      { id: "b", label: "B", text: "Move the shoulder farther so it loosens up" },
      { id: "c", label: "C", text: "Finish the set quickly before stopping" },
      { id: "d", label: "D", text: "Tell the resident pain is part of exercise" },
    ],
    correctChoiceId: "a",
    rationale: "ROM exercises should not be forced through pain.",
    memoryTip: "Pain is a stop sign.",
    difficulty: 1,
  },
  {
    id: "mh-101",
    domainSlug: "mental-health-and-social-needs",
    domainTitle: "Mental Health and Social Needs",
    type: "knowledge",
    prompt: "Which approach is best when caring for a resident with dementia who is confused?",
    choices: [
      { id: "a", label: "A", text: "Use calm, simple communication and gentle redirection" },
      { id: "b", label: "B", text: "Argue until the resident agrees with reality" },
      { id: "c", label: "C", text: "Give several directions at once" },
      { id: "d", label: "D", text: "Ignore all confused statements" },
    ],
    correctChoiceId: "a",
    rationale: "Simple, calm communication is more effective and less distressing than arguing.",
    memoryTip: "Simple and calm helps confused minds.",
    difficulty: 1,
  },
  {
    id: "mh-102",
    domainSlug: "mental-health-and-social-needs",
    domainTitle: "Mental Health and Social Needs",
    type: "knowledge",
    prompt: "Which change may suggest depression in a long-term care resident?",
    choices: [
      { id: "a", label: "A", text: "Withdrawal from usual activities" },
      { id: "b", label: "B", text: "Enjoying a family visit" },
      { id: "c", label: "C", text: "Requesting extra blankets" },
      { id: "d", label: "D", text: "Taking a nap after lunch" },
    ],
    correctChoiceId: "a",
    rationale: "Withdrawal and loss of interest can be warning signs of depression and should be reported.",
    memoryTip: "Withdrawal is a change worth noting.",
    difficulty: 1,
  },
  {
    id: "mh-103",
    domainSlug: "mental-health-and-social-needs",
    domainTitle: "Mental Health and Social Needs",
    type: "knowledge",
    prompt: "What is the best way to support a resident's social needs?",
    choices: [
      { id: "a", label: "A", text: "Encourage meaningful interaction and participation when appropriate" },
      { id: "b", label: "B", text: "Keep the resident alone to prevent complaints" },
      { id: "c", label: "C", text: "Make decisions without asking the resident" },
      { id: "d", label: "D", text: "Talk only during required care tasks" },
    ],
    correctChoiceId: "a",
    rationale: "Social engagement supports emotional well-being and quality of life.",
    memoryTip: "Connection supports mental health.",
    difficulty: 1,
  },
  {
    id: "mh-104",
    domainSlug: "mental-health-and-social-needs",
    domainTitle: "Mental Health and Social Needs",
    type: "knowledge",
    prompt: "If a resident becomes agitated in a noisy environment, the CNA should:",
    choices: [
      { id: "a", label: "A", text: "Reduce stimulation and use a calm approach" },
      { id: "b", label: "B", text: "Speak louder so the resident pays attention" },
      { id: "c", label: "C", text: "Crowd around the resident with more staff" },
      { id: "d", label: "D", text: "Tell the resident to stop overreacting" },
    ],
    correctChoiceId: "a",
    rationale: "Reducing noise and stimulation may help de-escalate agitation.",
    memoryTip: "Less noise, less stress.",
    difficulty: 1,
  },
  {
    id: "mh-105",
    domainSlug: "mental-health-and-social-needs",
    domainTitle: "Mental Health and Social Needs",
    type: "knowledge",
    prompt: "A resident repeatedly asks for a spouse who died years ago. The best response is to:",
    choices: [
      { id: "a", label: "A", text: "Respond to the emotion and redirect gently" },
      { id: "b", label: "B", text: "Tell the resident bluntly that the spouse is dead every time" },
      { id: "c", label: "C", text: "Ignore the question and walk away" },
      { id: "d", label: "D", text: "Laugh because the resident will not remember anyway" },
    ],
    correctChoiceId: "a",
    rationale: "Validation and gentle redirection are often more supportive than repeated correction.",
    memoryTip: "Answer the feeling, not just the fact.",
    difficulty: 2,
  },
  {
    id: "mh-scn-101",
    domainSlug: "mental-health-and-social-needs",
    domainTitle: "Mental Health and Social Needs",
    type: "scenario",
    prompt:
      "A resident with dementia becomes upset in the late afternoon and says, 'I have to go pick up my children.' What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Acknowledge the concern and redirect the resident to a calming activity" },
      { id: "b", label: "B", text: "Argue that the children are grown adults" },
      { id: "c", label: "C", text: "Tell the resident to stop talking nonsense" },
      { id: "d", label: "D", text: "Walk away because the resident will forget soon" },
    ],
    correctChoiceId: "a",
    rationale: "Validation and redirection help reduce distress without escalating confusion.",
    memoryTip: "Calm the feeling, redirect the moment.",
    difficulty: 2,
  },
  {
    id: "mh-scn-102",
    domainSlug: "mental-health-and-social-needs",
    domainTitle: "Mental Health and Social Needs",
    type: "scenario",
    prompt:
      "A usually social resident has stopped attending activities and has eaten very little for two days. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Report the changes in behavior and appetite to the nurse" },
      { id: "b", label: "B", text: "Assume the resident wants more privacy now" },
      { id: "c", label: "C", text: "Wait until the weekly report to mention it" },
      { id: "d", label: "D", text: "Tell the resident to cheer up" },
    ],
    correctChoiceId: "a",
    rationale: "Withdrawal and poor intake are important changes that should be reported promptly.",
    memoryTip: "Behavior change plus poor intake means report.",
    difficulty: 1,
  },
  {
    id: "mh-scn-103",
    domainSlug: "mental-health-and-social-needs",
    domainTitle: "Mental Health and Social Needs",
    type: "scenario",
    prompt:
      "During care, a resident says, 'Nothing matters anymore. I am just tired of all this.' What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Take the statement seriously, stay with the resident, and report it to the nurse immediately" },
      { id: "b", label: "B", text: "Say everyone feels that way sometimes and continue working" },
      { id: "c", label: "C", text: "Promise not to tell anyone" },
      { id: "d", label: "D", text: "Change the subject and leave the room" },
    ],
    correctChoiceId: "a",
    rationale: "Statements of hopelessness can signal serious emotional risk and require immediate reporting.",
    memoryTip: "Take hopeless talk seriously.",
    difficulty: 2,
  },
  {
    id: "mh-scn-104",
    domainSlug: "mental-health-and-social-needs",
    domainTitle: "Mental Health and Social Needs",
    type: "scenario",
    prompt:
      "A resident with dementia becomes combative when several aides crowd around during toileting care. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Reduce stimulation, use a calm approach, and proceed only as safely tolerated" },
      { id: "b", label: "B", text: "Hold the resident down until care is complete" },
      { id: "c", label: "C", text: "Raise your voice so the resident understands the instructions" },
      { id: "d", label: "D", text: "Argue that the resident is being unreasonable" },
    ],
    correctChoiceId: "a",
    rationale: "Too much stimulation may worsen agitation, so the CNA should calm the setting and approach.",
    memoryTip: "Less chaos, less combativeness.",
    difficulty: 2,
  },
  {
    id: "mh-scn-105",
    domainSlug: "mental-health-and-social-needs",
    domainTitle: "Mental Health and Social Needs",
    type: "scenario",
    prompt:
      "A resident who usually enjoys family calls says, 'I do not want to talk to anyone today,' and turns to the wall. What should the CNA do?",
    choices: [
      { id: "a", label: "A", text: "Respect the moment, offer support, and report the change in mood or behavior" },
      { id: "b", label: "B", text: "Force the resident to answer the phone anyway" },
      { id: "c", label: "C", text: "Tell the family the resident is just being rude" },
      { id: "d", label: "D", text: "Ignore it because moods change every day" },
    ],
    correctChoiceId: "a",
    rationale: "The CNA should respect the resident while recognizing a possible emotional change that needs follow-up.",
    memoryTip: "Respect and report mood changes.",
    difficulty: 1,
  },
];
