import type { ExamQuestion } from "@/lib/exams/types";

// ─── I. Role of the Nurse Aide (18%) ─────────────────────────────────────────
// Covers: personal responsibility, reporting, resident rights, time management,
// ethical conduct, registry, nurse aide role on the health care team,
// communication skills
// Domain slug: "role-of-nurse-aide"

const roleOfNurseAideBank: ExamQuestion[] = [
  {
    id: "rna-001",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "The nurse aide's scope of practice is determined by:",
    choices: [
      { id: "a", label: "A", text: "The supervising nurse" },
      { id: "b", label: "B", text: "State law and facility policy" },
      { id: "c", label: "C", text: "The resident and their family" },
      { id: "d", label: "D", text: "The nurse aide's own training level" },
    ],
    correctChoiceId: "b",
    rationale: "State law and facility policy define the legal boundaries of what a nurse aide may and may not do, regardless of personal training.",
    memoryTip: "Scope = state law + facility policy.",
    difficulty: 1,
  },
  {
    id: "rna-002",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "When a nurse aide notices an unusual change in a resident's condition, the aide should first:",
    choices: [
      { id: "a", label: "A", text: "Document the observation at the end of shift" },
      { id: "b", label: "B", text: "Treat the symptom before telling anyone" },
      { id: "c", label: "C", text: "Report the change promptly to the licensed nurse" },
      { id: "d", label: "D", text: "Ask the resident if they want it reported" },
    ],
    correctChoiceId: "c",
    rationale: "Prompt reporting to the licensed nurse is required so clinical decisions can be made quickly. Delay can harm the resident.",
    memoryTip: "Change = report immediately.",
    difficulty: 1,
  },
  {
    id: "rna-003",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "A complete verbal report to the nurse should include:",
    choices: [
      { id: "a", label: "A", text: "The aide's personal opinion about the cause" },
      { id: "b", label: "B", text: "Who, what, when, where, and how observations were made" },
      { id: "c", label: "C", text: "Only physical symptoms, not behavioral changes" },
      { id: "d", label: "D", text: "Diagnosis and treatment recommendations" },
    ],
    correctChoiceId: "b",
    rationale: "An effective report is objective and includes all relevant facts: who the resident is, what was observed, when and where it happened, and how it appeared.",
    memoryTip: "5 Ws: who, what, when, where, how.",
    difficulty: 2,
  },
  {
    id: "rna-004",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "Which action by a nurse aide is an example of proper body mechanics?",
    choices: [
      { id: "a", label: "A", text: "Twisting at the waist while lifting" },
      { id: "b", label: "B", text: "Bending at the back to reach the floor" },
      { id: "c", label: "C", text: "Keeping the load close to the body and bending at the knees" },
      { id: "d", label: "D", text: "Holding the breath while lifting heavy objects" },
    ],
    correctChoiceId: "c",
    rationale: "Keeping the load close and bending at the knees uses leg muscles and protects the spine from injury.",
    memoryTip: "Close + knees = safe lift.",
    difficulty: 1,
  },
  {
    id: "rna-005",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "HIPAA protects a resident's right to:",
    choices: [
      { id: "a", label: "A", text: "Refuse all medical treatment" },
      { id: "b", label: "B", text: "Privacy of their personal health information" },
      { id: "c", label: "C", text: "Choose their nurse aide" },
      { id: "d", label: "D", text: "Be discharged whenever they want" },
    ],
    correctChoiceId: "b",
    rationale: "HIPAA (Health Insurance Portability and Accountability Act) specifically protects the confidentiality of protected health information.",
    memoryTip: "HIPAA = health information privacy.",
    difficulty: 1,
  },
  {
    id: "rna-006",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "scenario",
    prompt: "A nurse aide is caring for a resident whose family member asks what medications the resident is taking. The aide should:",
    choices: [
      { id: "a", label: "A", text: "Read the medication list from the chart" },
      { id: "b", label: "B", text: "Refer the family member to the nurse" },
      { id: "c", label: "C", text: "Explain that medications are none of their business" },
      { id: "d", label: "D", text: "Tell the family what the aide remembers giving" },
    ],
    correctChoiceId: "b",
    rationale: "Medication information is clinical and confidential. The nurse aide should refer medical questions to the licensed nurse, who can determine what information may appropriately be shared.",
    memoryTip: "Medical questions → nurse, not aide.",
    difficulty: 2,
  },
  {
    id: "rna-007",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "Which is an example of physical abuse of a resident?",
    choices: [
      { id: "a", label: "A", text: "Forgetting to bring a meal tray on time" },
      { id: "b", label: "B", text: "Raising one's voice during a difficult care task" },
      { id: "c", label: "C", text: "Striking a resident during care" },
      { id: "d", label: "D", text: "Leaving a call light out of reach once" },
    ],
    correctChoiceId: "c",
    rationale: "Striking a resident is physical abuse. Any intentional infliction of physical pain or injury is abuse and must be reported immediately.",
    memoryTip: "Striking = physical abuse, must report.",
    difficulty: 1,
  },
  {
    id: "rna-008",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "Neglect by a nurse aide is best described as:",
    choices: [
      { id: "a", label: "A", text: "Intentionally harming a resident" },
      { id: "b", label: "B", text: "Failing to provide required care" },
      { id: "c", label: "C", text: "Stealing a resident's property" },
      { id: "d", label: "D", text: "Sharing private information" },
    ],
    correctChoiceId: "b",
    rationale: "Neglect is the failure to provide care that a resident requires, whether intentional or due to inattention. It is a reportable form of mistreatment.",
    memoryTip: "Neglect = failing to provide required care.",
    difficulty: 1,
  },
  {
    id: "rna-009",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "The Nurse Aide Registry is used by employers to:",
    choices: [
      { id: "a", label: "A", text: "Schedule nurse aide shifts" },
      { id: "b", label: "B", text: "Verify certification status and check for abuse findings before hiring" },
      { id: "c", label: "C", text: "Assign aides to specific residents" },
      { id: "d", label: "D", text: "Track nurse aide earnings" },
    ],
    correctChoiceId: "b",
    rationale: "Employers are required to check the Nurse Aide Registry to confirm an aide is certified and has no substantiated findings of abuse, neglect, or misappropriation before hiring.",
    memoryTip: "Registry = certification + background check.",
    difficulty: 2,
  },
  {
    id: "rna-010",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "A resident has the right to self-determination, which means the resident can:",
    choices: [
      { id: "a", label: "A", text: "Make decisions about their own care and daily routines" },
      { id: "b", label: "B", text: "Override the doctor's orders" },
      { id: "c", label: "C", text: "Demand care from a specific aide at all times" },
      { id: "d", label: "D", text: "Refuse to follow safety rules" },
    ],
    correctChoiceId: "a",
    rationale: "Self-determination is a fundamental resident right: residents have the right to make choices about their care, daily routines, and preferences.",
    memoryTip: "Self-determination = resident's right to choose.",
    difficulty: 1,
  },
  {
    id: "rna-011",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "Which is an example of verbal abuse?",
    choices: [
      { id: "a", label: "A", text: "Helping a resident dress more quickly than they prefer" },
      { id: "b", label: "B", text: "Calling a resident demeaning names" },
      { id: "c", label: "C", text: "Declining to answer a personal question from a resident" },
      { id: "d", label: "D", text: "Forgetting to knock before entering a room" },
    ],
    correctChoiceId: "b",
    rationale: "Verbal abuse includes using demeaning, threatening, or profane language toward a resident. It causes emotional harm and is a reportable offense.",
    memoryTip: "Demeaning language = verbal abuse.",
    difficulty: 1,
  },
  {
    id: "rna-012",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "Therapeutic communication by the nurse aide means:",
    choices: [
      { id: "a", label: "A", text: "Using medical jargon so the resident understands diagnosis" },
      { id: "b", label: "B", text: "Communicating in ways that are helpful and supportive to the resident" },
      { id: "c", label: "C", text: "Giving advice about treatment decisions" },
      { id: "d", label: "D", text: "Avoiding difficult topics so the resident is comfortable" },
    ],
    correctChoiceId: "b",
    rationale: "Therapeutic communication uses active listening, empathy, open-ended questions, and supportive language to build trust and meet the resident's emotional and social needs.",
    memoryTip: "Therapeutic = helpful, empathetic, supportive.",
    difficulty: 2,
  },
  {
    id: "rna-013",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "scenario",
    prompt: "A nurse aide is asked by a supervisor to perform a task that is outside the aide's legal scope of practice. The aide should:",
    choices: [
      { id: "a", label: "A", text: "Perform the task because the supervisor asked" },
      { id: "b", label: "B", text: "Refuse and report the request through the chain of command" },
      { id: "c", label: "C", text: "Perform the task but document it differently" },
      { id: "d", label: "D", text: "Ask a coworker if it is okay first" },
    ],
    correctChoiceId: "b",
    rationale: "A nurse aide should never perform tasks outside their legal scope, even if a supervisor asks. The aide should refuse and escalate through the chain of command.",
    memoryTip: "Out of scope = refuse and report.",
    difficulty: 2,
  },
  {
    id: "rna-014",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "Which statement describes an interdisciplinary care team?",
    choices: [
      { id: "a", label: "A", text: "A group of nurses who plan care without input from others" },
      { id: "b", label: "B", text: "Multiple health professionals working together to meet the resident's needs" },
      { id: "c", label: "C", text: "The resident's family and the primary physician only" },
      { id: "d", label: "D", text: "The nurse and aide assigned to the same floor" },
    ],
    correctChoiceId: "b",
    rationale: "An interdisciplinary team includes nurses, therapists, social workers, dietitians, physicians, and other professionals — all contributing to a coordinated care plan.",
    memoryTip: "Interdisciplinary = many disciplines, one plan.",
    difficulty: 2,
  },
  {
    id: "rna-015",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "Documentation by the nurse aide must be:",
    choices: [
      { id: "a", label: "A", text: "Written only at the end of the shift to save time" },
      { id: "b", label: "B", text: "Accurate, objective, and completed in a timely manner" },
      { id: "c", label: "C", text: "Based on what the nurse expects the aide to have done" },
      { id: "d", label: "D", text: "Completed for major events only, not routine care" },
    ],
    correctChoiceId: "b",
    rationale: "Documentation must be accurate (truthful), objective (based on observation, not opinion), and timely. Falsification or delayed documentation is a serious legal violation.",
    memoryTip: "Documentation: accurate, objective, timely.",
    difficulty: 1,
  },
  {
    id: "rna-016",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "scenario",
    prompt: "A resident refuses care from the nurse aide. The aide should:",
    choices: [
      { id: "a", label: "A", text: "Insist the care is necessary and proceed anyway" },
      { id: "b", label: "B", text: "Respect the refusal, document it, and report to the nurse" },
      { id: "c", label: "C", text: "Ask a family member to force the resident to comply" },
      { id: "d", label: "D", text: "Skip that resident's care for the rest of the shift" },
    ],
    correctChoiceId: "b",
    rationale: "Residents have the right to refuse care. The aide must respect the refusal, report it to the nurse, and document it. The nurse will determine next steps.",
    memoryTip: "Resident refuses = respect, report, document.",
    difficulty: 2,
  },
  {
    id: "rna-017",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "Misappropriation of a resident's property by a nurse aide means:",
    choices: [
      { id: "a", label: "A", text: "Borrowing the resident's property with permission" },
      { id: "b", label: "B", text: "Using or taking the resident's property without consent" },
      { id: "c", label: "C", text: "Accidentally misplacing a resident's belonging" },
      { id: "d", label: "D", text: "Moving property for safety reasons without telling the resident" },
    ],
    correctChoiceId: "b",
    rationale: "Misappropriation is the deliberate taking, using, or transferring of a resident's property without consent. It is a form of abuse reportable to the state registry.",
    memoryTip: "Misappropriation = taking/using resident property without consent.",
    difficulty: 2,
  },
  {
    id: "rna-018",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "The purpose of the care plan is to:",
    choices: [
      { id: "a", label: "A", text: "Tell the aide how to document observations" },
      { id: "b", label: "B", text: "Provide individualized goals and instructions for each resident's care" },
      { id: "c", label: "C", text: "List all facility rules for nurse aides" },
      { id: "d", label: "D", text: "Replace verbal communication between staff" },
    ],
    correctChoiceId: "b",
    rationale: "The care plan is individualized to each resident's needs, goals, preferences, and conditions. Aides must follow the care plan when providing care.",
    memoryTip: "Care plan = individualized goals and instructions.",
    difficulty: 1,
  },
  {
    id: "rna-019",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "A nurse aide who witnesses abuse of a resident is legally required to:",
    choices: [
      { id: "a", label: "A", text: "Wait to see if it happens again before reporting" },
      { id: "b", label: "B", text: "Discuss it with coworkers to get their opinion" },
      { id: "c", label: "C", text: "Report it immediately to a supervisor or regulatory agency" },
      { id: "d", label: "D", text: "Confront the abuser directly before reporting" },
    ],
    correctChoiceId: "c",
    rationale: "Nurse aides are mandated reporters and have a legal obligation to report suspected or witnessed abuse immediately. Delay or failure to report can result in loss of certification.",
    memoryTip: "Witness abuse = report immediately — legal obligation.",
    difficulty: 1,
  },
  {
    id: "rna-020",
    domainSlug: "role-of-nurse-aide",
    domainTitle: "Role of the Nurse Aide",
    type: "knowledge",
    prompt: "Which practice helps the nurse aide manage time effectively during a shift?",
    choices: [
      { id: "a", label: "A", text: "Skipping documentation to spend more time at the bedside" },
      { id: "b", label: "B", text: "Prioritizing tasks by urgency and resident need, then following through in order" },
      { id: "c", label: "C", text: "Completing the easiest tasks first regardless of resident priority" },
      { id: "d", label: "D", text: "Waiting until the nurse assigns each task before starting" },
    ],
    correctChoiceId: "b",
    rationale: "Effective time management means organizing tasks by urgency and resident need, then working systematically so nothing critical is missed.",
    memoryTip: "Time management = prioritize by urgency and need.",
    difficulty: 2,
  },
];

// ─── II. Promotion of Safety (18%) ────────────────────────────────────────────
// Covers: hazards in healthcare, common resident injuries, safety and comfort,
// restraints, infection prevention and control, standard precautions

const promotionOfSafetyBank: ExamQuestion[] = [
  {
    id: "pos-001",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "The single most important action for preventing the spread of infection is:",
    choices: [
      { id: "a", label: "A", text: "Wearing gloves at all times" },
      { id: "b", label: "B", text: "Handwashing" },
      { id: "c", label: "C", text: "Wearing a mask during every interaction" },
      { id: "d", label: "D", text: "Using disposable gowns" },
    ],
    correctChoiceId: "b",
    rationale: "Handwashing is consistently identified as the most effective infection-prevention measure. Gloves, masks, and gowns supplement but do not replace hand hygiene.",
    memoryTip: "Hand hygiene = #1 infection prevention.",
    difficulty: 1,
  },
  {
    id: "pos-002",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "Standard precautions require the nurse aide to treat which body fluids as potentially infectious?",
    choices: [
      { id: "a", label: "A", text: "Only blood" },
      { id: "b", label: "B", text: "Blood and all body fluids, secretions, and excretions" },
      { id: "c", label: "C", text: "Only fluids from residents with a known diagnosis" },
      { id: "d", label: "D", text: "Only sweat and saliva" },
    ],
    correctChoiceId: "b",
    rationale: "Standard precautions treat all blood and body fluids as potentially infectious, regardless of diagnosis. This protects both staff and residents.",
    memoryTip: "Standard precautions = all body fluids, every resident.",
    difficulty: 1,
  },
  {
    id: "pos-003",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "Gloves must be changed and hands washed:",
    choices: [
      { id: "a", label: "A", text: "Only when visibly dirty" },
      { id: "b", label: "B", text: "Between residents and between dirty and clean tasks on the same resident" },
      { id: "c", label: "C", text: "Once at the beginning and once at the end of each shift" },
      { id: "d", label: "D", text: "Only when switching from one type of care to another" },
    ],
    correctChoiceId: "b",
    rationale: "Gloves must be changed between residents and between dirty-to-clean task transitions on the same resident to prevent cross-contamination.",
    memoryTip: "Glove change: between residents and dirty→clean tasks.",
    difficulty: 2,
  },
  {
    id: "pos-004",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "Falls are among the most common injuries in long-term care. A key fall prevention strategy is:",
    choices: [
      { id: "a", label: "A", text: "Keeping residents in bed as much as possible" },
      { id: "b", label: "B", text: "Answering call lights promptly and keeping pathways clear" },
      { id: "c", label: "C", text: "Locking the door so the resident cannot leave the room" },
      { id: "d", label: "D", text: "Removing all furniture from the room" },
    ],
    correctChoiceId: "b",
    rationale: "Prompt call-light response, keeping pathways clear, appropriate footwear, and bed in the lowest position are core fall prevention strategies.",
    memoryTip: "Fall prevention: answer calls promptly, clear paths, low bed.",
    difficulty: 1,
  },
  {
    id: "pos-005",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "When applying a physical restraint, the nurse aide must:",
    choices: [
      { id: "a", label: "A", text: "Apply it as tightly as possible to prevent movement" },
      { id: "b", label: "B", text: "Have a physician's or nurse's order and check the resident frequently" },
      { id: "c", label: "C", text: "Apply it based on personal judgment without an order" },
      { id: "d", label: "D", text: "Tie it to a fixed part of the bed frame" },
    ],
    correctChoiceId: "b",
    rationale: "Restraints require a physician's or authorized healthcare professional's order. The aide must check the resident at least every two hours and release and reposition regularly.",
    memoryTip: "Restraint: order required, check every 2 hours.",
    difficulty: 2,
  },
  {
    id: "pos-006",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "The proper technique for using a fire extinguisher follows the acronym PASS, which stands for:",
    choices: [
      { id: "a", label: "A", text: "Pull, Aim, Squeeze, Sweep" },
      { id: "b", label: "B", text: "Push, Aim, Spray, Sweep" },
      { id: "c", label: "C", text: "Pull, Activate, Spray, Stop" },
      { id: "d", label: "D", text: "Press, Aim, Swing, Spray" },
    ],
    correctChoiceId: "a",
    rationale: "PASS: Pull the pin, Aim at the base of the fire, Squeeze the handle, Sweep side to side.",
    memoryTip: "PASS: Pull, Aim, Squeeze, Sweep.",
    difficulty: 2,
  },
  {
    id: "pos-007",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "A wander guard or door alarm is used to:",
    choices: [
      { id: "a", label: "A", text: "Restrain residents who are combative" },
      { id: "b", label: "B", text: "Alert staff when a cognitively impaired resident approaches an exit" },
      { id: "c", label: "C", text: "Monitor resident vital signs from a distance" },
      { id: "d", label: "D", text: "Lock residents in their rooms overnight" },
    ],
    correctChoiceId: "b",
    rationale: "Wander guards and door alarms are safety devices that alert staff when a resident at risk for elopement approaches an exit, without restraining movement.",
    memoryTip: "Wander guard = elopement alert, not a restraint.",
    difficulty: 2,
  },
  {
    id: "pos-008",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "scenario",
    prompt: "A nurse aide enters a resident's room and sees a small fire in the wastebasket. The correct first action is to:",
    choices: [
      { id: "a", label: "A", text: "Open a window for ventilation" },
      { id: "b", label: "B", text: "Try to put it out with water" },
      { id: "c", label: "C", text: "Activate the fire alarm and get the resident out safely" },
      { id: "d", label: "D", text: "Wait to see if it grows before reporting" },
    ],
    correctChoiceId: "c",
    rationale: "In a fire emergency, the priority is resident safety first. Activate the alarm (RACE: Rescue, Alarm, Contain, Extinguish/Evacuate), then get residents out of danger.",
    memoryTip: "Fire: RACE — Rescue first, Alarm, Contain, Evacuate.",
    difficulty: 2,
  },
  {
    id: "pos-009",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "Contact precautions are used when a resident has an infection spread by:",
    choices: [
      { id: "a", label: "A", text: "Airborne droplets only" },
      { id: "b", label: "B", text: "Direct or indirect physical contact" },
      { id: "c", label: "C", text: "Sharing food or water" },
      { id: "d", label: "D", text: "Insect vectors only" },
    ],
    correctChoiceId: "b",
    rationale: "Contact precautions are used for infections spread by direct contact (touching the resident) or indirect contact (touching contaminated surfaces). MRSA is a common example.",
    memoryTip: "Contact precautions = spread by touching.",
    difficulty: 2,
  },
  {
    id: "pos-010",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "The correct hand hygiene technique using soap and water requires rubbing for at least:",
    choices: [
      { id: "a", label: "A", text: "5 seconds" },
      { id: "b", label: "B", text: "20 seconds" },
      { id: "c", label: "C", text: "60 seconds" },
      { id: "d", label: "D", text: "10 seconds" },
    ],
    correctChoiceId: "b",
    rationale: "CDC guidelines require at least 20 seconds of friction when washing hands with soap and water — about the time it takes to hum 'Happy Birthday' twice.",
    memoryTip: "Soap + water = 20 seconds minimum.",
    difficulty: 1,
  },
  {
    id: "pos-011",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "A skin tear on a resident is most often caused by:",
    choices: [
      { id: "a", label: "A", text: "Poor nutrition" },
      { id: "b", label: "B", text: "Friction or shearing forces during care activities" },
      { id: "c", label: "C", text: "Excessive moisture" },
      { id: "d", label: "D", text: "Prolonged bed rest only" },
    ],
    correctChoiceId: "b",
    rationale: "Skin tears are most commonly caused by friction or shearing during transfers, repositioning, or removal of tape. Fragile skin in older adults tears easily.",
    memoryTip: "Skin tears = friction/shear during care.",
    difficulty: 2,
  },
  {
    id: "pos-012",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "The chain of infection describes how infection spreads. Breaking the chain requires:",
    choices: [
      { id: "a", label: "A", text: "Eliminating at least one link, such as breaking transmission routes" },
      { id: "b", label: "B", text: "Treating all residents with antibiotics" },
      { id: "c", label: "C", text: "Isolating all residents from each other" },
      { id: "d", label: "D", text: "Using only disposable equipment" },
    ],
    correctChoiceId: "a",
    rationale: "The chain of infection has six links: pathogen, reservoir, portal of exit, mode of transmission, portal of entry, susceptible host. Breaking any link stops the spread.",
    memoryTip: "Break any link in the chain = infection stopped.",
    difficulty: 3,
  },
  {
    id: "pos-013",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "Restraint alternatives the nurse aide can use include:",
    choices: [
      { id: "a", label: "A", text: "Tying the resident loosely to the wheelchair" },
      { id: "b", label: "B", text: "Increased supervision, activity redirection, and wedge cushions" },
      { id: "c", label: "C", text: "Sedating medications without a physician's order" },
      { id: "d", label: "D", text: "Locking the resident's room door" },
    ],
    correctChoiceId: "b",
    rationale: "The least restrictive approach is always preferred. Alternatives include more frequent checks, meaningful activities, repositioning devices, and bed/chair alarms.",
    memoryTip: "Restraint alternatives: supervision, activity, positioning aids.",
    difficulty: 2,
  },
  {
    id: "pos-014",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "scenario",
    prompt: "A nurse aide finds sharps (needles) in a resident's room that were left on the bedside table. The aide should:",
    choices: [
      { id: "a", label: "A", text: "Place them in the nearest regular trash can" },
      { id: "b", label: "B", text: "Dispose of them in the approved sharps container" },
      { id: "c", label: "C", text: "Leave them and notify the nurse to handle it" },
      { id: "d", label: "D", text: "Recap the needles before disposal" },
    ],
    correctChoiceId: "b",
    rationale: "Sharps must always be disposed of in approved sharps containers. Never recap needles (needlestick risk) and never use regular trash.",
    memoryTip: "Sharps → sharps container only. Never recap.",
    difficulty: 1,
  },
  {
    id: "pos-015",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "When caring for a resident in droplet precautions, the nurse aide should wear:",
    choices: [
      { id: "a", label: "A", text: "Gloves only" },
      { id: "b", label: "B", text: "A surgical mask when within 3 feet of the resident" },
      { id: "c", label: "C", text: "A respirator (N95) at all times" },
      { id: "d", label: "D", text: "No PPE unless performing direct care" },
    ],
    correctChoiceId: "b",
    rationale: "Droplet precautions require a surgical mask when within approximately 3 feet (1 meter) of the resident. These are used for illnesses like influenza.",
    memoryTip: "Droplet = surgical mask within 3 feet.",
    difficulty: 3,
  },
  {
    id: "pos-016",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "Elopement risk refers to the danger of a resident:",
    choices: [
      { id: "a", label: "A", text: "Falling out of bed at night" },
      { id: "b", label: "B", text: "Leaving the facility without authorization" },
      { id: "c", label: "C", text: "Refusing to take medications" },
      { id: "d", label: "D", text: "Becoming agitated during care" },
    ],
    correctChoiceId: "b",
    rationale: "Elopement is when a cognitively impaired resident leaves the facility unsupervised. It is a serious safety risk requiring monitoring, wander guards, and a care plan.",
    memoryTip: "Elopement = leaving facility without authorization.",
    difficulty: 1,
  },
  {
    id: "pos-017",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "When a resident's bed is in use, the bed height should be:",
    choices: [
      { id: "a", label: "A", text: "At the highest position for easy aide access" },
      { id: "b", label: "B", text: "At the lowest position for resident safety" },
      { id: "c", label: "C", text: "At waist height for the resident" },
      { id: "d", label: "D", text: "In whatever position is most convenient for the shift" },
    ],
    correctChoiceId: "b",
    rationale: "Keeping the bed in the lowest position reduces injury risk if the resident attempts to get up or falls. The bed is raised to working height during care and immediately lowered again.",
    memoryTip: "Bed in use = lowest position.",
    difficulty: 1,
  },
  {
    id: "pos-018",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "A Material Safety Data Sheet (MSDS / SDS) provides information about:",
    choices: [
      { id: "a", label: "A", text: "Resident medication schedules" },
      { id: "b", label: "B", text: "Hazardous chemical properties, safe use, and emergency procedures" },
      { id: "c", label: "C", text: "Equipment maintenance schedules" },
      { id: "d", label: "D", text: "Employee scheduling requirements" },
    ],
    correctChoiceId: "b",
    rationale: "Safety Data Sheets (formerly MSDS) describe chemical hazards, proper handling, storage, PPE requirements, and what to do in case of exposure or spill.",
    memoryTip: "SDS = chemical hazard information.",
    difficulty: 2,
  },
  {
    id: "pos-019",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "knowledge",
    prompt: "After removing gloves, the nurse aide should:",
    choices: [
      { id: "a", label: "A", text: "Wash hands immediately" },
      { id: "b", label: "B", text: "Reuse the gloves if they appear clean" },
      { id: "c", label: "C", text: "Put on new gloves before washing hands" },
      { id: "d", label: "D", text: "Wash hands only if the gloves tore" },
    ],
    correctChoiceId: "a",
    rationale: "Hands must be washed immediately after removing gloves. Gloves do not eliminate the need for hand hygiene; they can develop small undetected holes.",
    memoryTip: "After gloves → wash hands always.",
    difficulty: 1,
  },
  {
    id: "pos-020",
    domainSlug: "promotion-of-safety",
    domainTitle: "Promotion of Safety",
    type: "scenario",
    prompt: "A nurse aide notices a wet spill on the hallway floor. The aide should:",
    choices: [
      { id: "a", label: "A", text: "Step over it and report it at the end of the shift" },
      { id: "b", label: "B", text: "Clean it up immediately or place a wet floor sign and notify housekeeping" },
      { id: "c", label: "C", text: "Put a chair over it so no one walks there" },
      { id: "d", label: "D", text: "Report it only if someone slips first" },
    ],
    correctChoiceId: "b",
    rationale: "Wet floors are a fall hazard. The aide should clean it up immediately or mark the area with a warning sign and notify housekeeping. Prompt action prevents injury.",
    memoryTip: "Wet floor: clean up or mark immediately.",
    difficulty: 1,
  },
];

// ─── III. Function and Health of the Resident (24%) ──────────────────────────
// Covers: ADLs, nutrition/hydration, sleep, elimination, mobility,
// effects of immobility, assistive devices, age-related changes,
// psychosocial needs

const functionAndHealthBank: ExamQuestion[] = [
  {
    id: "fah-001",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "Activities of daily living (ADLs) include which of the following?",
    choices: [
      { id: "a", label: "A", text: "Taking medications and reading" },
      { id: "b", label: "B", text: "Bathing, dressing, grooming, eating, and toileting" },
      { id: "c", label: "C", text: "Exercise therapy and cognitive testing" },
      { id: "d", label: "D", text: "Social activities and recreational programs" },
    ],
    correctChoiceId: "b",
    rationale: "ADLs are the basic self-care tasks necessary for daily living: bathing, dressing, grooming, eating, toileting, and transferring. The nurse aide assists with these.",
    memoryTip: "ADLs: bathe, dress, groom, eat, toilet, transfer.",
    difficulty: 1,
  },
  {
    id: "fah-002",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "When assisting a resident with eating, the nurse aide should:",
    choices: [
      { id: "a", label: "A", text: "Feed the resident as quickly as possible to finish on time" },
      { id: "b", label: "B", text: "Position the resident upright and allow adequate time for each bite" },
      { id: "c", label: "C", text: "Tilt the resident's head back to make swallowing easier" },
      { id: "d", label: "D", text: "Offer only pureed foods to all residents" },
    ],
    correctChoiceId: "b",
    rationale: "Residents should be upright (90 degrees or as specified in the care plan) to reduce aspiration risk. The aide should offer small bites and allow adequate time between each.",
    memoryTip: "Eating: sit upright, small bites, no rush.",
    difficulty: 1,
  },
  {
    id: "fah-003",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "Adequate hydration in elderly residents is important because older adults:",
    choices: [
      { id: "a", label: "A", text: "Have a stronger sense of thirst than younger adults" },
      { id: "b", label: "B", text: "Have a reduced thirst sensation and are at greater risk of dehydration" },
      { id: "c", label: "C", text: "Require less fluid than younger adults" },
      { id: "d", label: "D", text: "Absorb fluids faster through the intestine" },
    ],
    correctChoiceId: "b",
    rationale: "Aging reduces the sensation of thirst, making older adults less likely to drink enough. Dehydration can cause confusion, falls, and serious health complications.",
    memoryTip: "Elderly = reduced thirst → higher dehydration risk.",
    difficulty: 2,
  },
  {
    id: "fah-004",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "A contracture occurs when:",
    choices: [
      { id: "a", label: "A", text: "A resident moves too much without supervision" },
      { id: "b", label: "B", text: "Joints and muscles shorten and tighten from lack of movement" },
      { id: "c", label: "C", text: "The skin breaks down from prolonged pressure" },
      { id: "d", label: "D", text: "A resident gains weight rapidly" },
    ],
    correctChoiceId: "b",
    rationale: "Contractures result from disuse and immobility — muscles and tendons shorten, causing permanent joint restriction. Range of motion exercises help prevent them.",
    memoryTip: "Contracture = joints/muscles shorten from lack of movement.",
    difficulty: 2,
  },
  {
    id: "fah-005",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "The purpose of range of motion (ROM) exercises is to:",
    choices: [
      { id: "a", label: "A", text: "Strengthen muscles for independent ambulation" },
      { id: "b", label: "B", text: "Maintain or restore joint flexibility and prevent contractures" },
      { id: "c", label: "C", text: "Measure how far a joint can move for documentation" },
      { id: "d", label: "D", text: "Replace physical therapy for residents who cannot walk" },
    ],
    correctChoiceId: "b",
    rationale: "ROM exercises move joints through their full range to maintain flexibility, prevent contractures, promote circulation, and maintain function.",
    memoryTip: "ROM = maintain joint flexibility, prevent contractures.",
    difficulty: 1,
  },
  {
    id: "fah-006",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "A pressure injury (pressure ulcer) is caused by:",
    choices: [
      { id: "a", label: "A", text: "Poor nutrition alone" },
      { id: "b", label: "B", text: "Prolonged pressure on skin over a bony prominence" },
      { id: "c", label: "C", text: "Excessive physical activity" },
      { id: "d", label: "D", text: "Allergic reactions to bed linens" },
    ],
    correctChoiceId: "b",
    rationale: "Pressure injuries develop when sustained pressure reduces blood flow to skin over bony prominences like heels, sacrum, and hips. Repositioning every 2 hours prevents them.",
    memoryTip: "Pressure ulcer = sustained pressure over bony areas.",
    difficulty: 1,
  },
  {
    id: "fah-007",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "The nurse aide should reposition an immobile resident at least:",
    choices: [
      { id: "a", label: "A", text: "Once every 8 hours" },
      { id: "b", label: "B", text: "Once per shift" },
      { id: "c", label: "C", text: "Every 2 hours" },
      { id: "d", label: "D", text: "Every 30 minutes" },
    ],
    correctChoiceId: "c",
    rationale: "Repositioning every 2 hours is the standard to prevent pressure injuries. The schedule may be more frequent based on the resident's risk level and care plan.",
    memoryTip: "Reposition = every 2 hours minimum.",
    difficulty: 1,
  },
  {
    id: "fah-008",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "Normal bowel elimination patterns for adults generally include:",
    choices: [
      { id: "a", label: "A", text: "One bowel movement per hour" },
      { id: "b", label: "B", text: "Three bowel movements per day" },
      { id: "c", label: "C", text: "A range from three times per day to three times per week" },
      { id: "d", label: "D", text: "Exactly one bowel movement per day" },
    ],
    correctChoiceId: "c",
    rationale: "Normal bowel patterns vary widely. Three times per day to three times per week is considered within normal range. Deviations should be documented and reported.",
    memoryTip: "Normal bowel: 3×/day to 3×/week is normal range.",
    difficulty: 2,
  },
  {
    id: "fah-009",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "Age-related changes to the skin that increase injury risk include:",
    choices: [
      { id: "a", label: "A", text: "Increased skin elasticity and thicker dermis" },
      { id: "b", label: "B", text: "Thinning skin, reduced elasticity, and slower wound healing" },
      { id: "c", label: "C", text: "Increased oil production and better circulation" },
      { id: "d", label: "D", text: "Fewer nerve endings reducing pain sensitivity only" },
    ],
    correctChoiceId: "b",
    rationale: "With aging, skin becomes thinner, loses elasticity, and heals more slowly. This increases risk of tears, pressure injuries, and bruising from normal care activities.",
    memoryTip: "Aging skin: thinner, less elastic, heals slowly.",
    difficulty: 2,
  },
  {
    id: "fah-010",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "A therapeutic diet is ordered for a resident to:",
    choices: [
      { id: "a", label: "A", text: "Reduce the facility's food costs" },
      { id: "b", label: "B", text: "Meet specific medical needs such as heart disease, diabetes, or dysphagia" },
      { id: "c", label: "C", text: "Match the resident's personal food preferences only" },
      { id: "d", label: "D", text: "Simplify meal preparation for dietary staff" },
    ],
    correctChoiceId: "b",
    rationale: "Therapeutic diets are medically ordered to manage conditions like diabetes (carbohydrate-controlled), heart disease (low sodium), or swallowing problems (texture-modified).",
    memoryTip: "Therapeutic diet = medically ordered for a specific condition.",
    difficulty: 2,
  },
  {
    id: "fah-011",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "Maslow's Hierarchy of Needs places which category at the most basic level?",
    choices: [
      { id: "a", label: "A", text: "Safety and security" },
      { id: "b", label: "B", text: "Self-actualization" },
      { id: "c", label: "C", text: "Physiological needs (food, water, air, warmth, rest)" },
      { id: "d", label: "D", text: "Social belonging and love" },
    ],
    correctChoiceId: "c",
    rationale: "Maslow's hierarchy starts with physiological needs at the base: food, water, oxygen, warmth, and rest must be met before higher-level needs can be addressed.",
    memoryTip: "Maslow's base = physiological needs first.",
    difficulty: 2,
  },
  {
    id: "fah-012",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "A gait belt is used by the nurse aide to:",
    choices: [
      { id: "a", label: "A", text: "Secure residents to the bed during sleep" },
      { id: "b", label: "B", text: "Provide a safe grip during ambulation and transfers" },
      { id: "c", label: "C", text: "Measure the resident's waist circumference" },
      { id: "d", label: "D", text: "Hold clothing in place during dressing" },
    ],
    correctChoiceId: "b",
    rationale: "A gait belt is placed around the resident's waist to give the aide a secure handhold during ambulation and transfers, reducing risk of falls and injury.",
    memoryTip: "Gait belt = secure grip for walking and transfers.",
    difficulty: 1,
  },
  {
    id: "fah-013",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "Effects of immobility on a resident include:",
    choices: [
      { id: "a", label: "A", text: "Increased muscle strength and improved circulation" },
      { id: "b", label: "B", text: "Pressure injuries, muscle weakness, constipation, and depression" },
      { id: "c", label: "C", text: "Better sleep quality and reduced pain" },
      { id: "d", label: "D", text: "Improved respiratory function and reduced infection risk" },
    ],
    correctChoiceId: "b",
    rationale: "Immobility causes multiple complications: pressure injuries, muscle atrophy, contractures, constipation, blood clots, pneumonia, and psychological effects like depression.",
    memoryTip: "Immobility complications: pressure ulcers, weakness, constipation, depression.",
    difficulty: 2,
  },
  {
    id: "fah-014",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "When a resident uses a walker, the nurse aide should:",
    choices: [
      { id: "a", label: "A", text: "Walk ahead of the resident to open doors" },
      { id: "b", label: "B", text: "Walk slightly behind and to the side of the resident" },
      { id: "c", label: "C", text: "Hold the walker for the resident at all times" },
      { id: "d", label: "D", text: "Walk on the opposite side from the walker" },
    ],
    correctChoiceId: "b",
    rationale: "The aide should walk slightly behind and to the weak side, ready to assist without obstructing the resident's movement or balance.",
    memoryTip: "With walker: aide walks slightly behind on the weak side.",
    difficulty: 2,
  },
  {
    id: "fah-015",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "Urinary incontinence in older residents is best managed by the nurse aide by:",
    choices: [
      { id: "a", label: "A", text: "Limiting fluids so the resident urinates less" },
      { id: "b", label: "B", text: "Offering scheduled toileting every 2 hours and maintaining skin integrity" },
      { id: "c", label: "C", text: "Applying an indwelling catheter to avoid cleanup" },
      { id: "d", label: "D", text: "Using only adult briefs and changing once per shift" },
    ],
    correctChoiceId: "b",
    rationale: "Scheduled toileting every 2 hours (or per care plan), prompt response to call lights, and keeping skin clean and dry are the cornerstone of incontinence management.",
    memoryTip: "Incontinence: scheduled toileting + skin protection.",
    difficulty: 2,
  },
  {
    id: "fah-016",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "When doing passive ROM, the nurse aide should stop if the resident:",
    choices: [
      { id: "a", label: "A", text: "Asks a question during the exercise" },
      { id: "b", label: "B", text: "Reports pain or resistance is felt in the joint" },
      { id: "c", label: "C", text: "Falls asleep during the exercises" },
      { id: "d", label: "D", text: "Completes more repetitions than ordered" },
    ],
    correctChoiceId: "b",
    rationale: "Pain or resistance during ROM means the joint has reached its limit. Forcing beyond that point can cause injury. The aide must stop and report.",
    memoryTip: "ROM: pain or resistance = stop immediately.",
    difficulty: 1,
  },
  {
    id: "fah-017",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "Residents experience psychosocial needs that include:",
    choices: [
      { id: "a", label: "A", text: "Only physical comfort and medical treatment" },
      { id: "b", label: "B", text: "Social interaction, emotional support, sense of belonging, and dignity" },
      { id: "c", label: "C", text: "Recreational activities and entertainment only" },
      { id: "d", label: "D", text: "Financial planning and legal advice" },
    ],
    correctChoiceId: "b",
    rationale: "Psychosocial needs encompass emotional, social, and spiritual dimensions. Residents need connection, dignity, purpose, and support to cope with nursing home placement.",
    memoryTip: "Psychosocial needs: belonging, dignity, emotional support.",
    difficulty: 2,
  },
  {
    id: "fah-018",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "A common age-related change in vision includes:",
    choices: [
      { id: "a", label: "A", text: "Improved night vision" },
      { id: "b", label: "B", text: "Increased pupil size and better peripheral vision" },
      { id: "c", label: "C", text: "Reduced ability to see in dim light and decreased depth perception" },
      { id: "d", label: "D", text: "Sharper distance vision" },
    ],
    correctChoiceId: "c",
    rationale: "Age-related vision changes include reduced night vision (smaller pupils), decreased depth perception, and difficulty adjusting to light changes — all increasing fall risk.",
    memoryTip: "Aging eyes: poor night vision, less depth perception.",
    difficulty: 2,
  },
  {
    id: "fah-019",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "knowledge",
    prompt: "The nurse aide should report a resident's food intake that is:",
    choices: [
      { id: "a", label: "A", text: "100% of the meal" },
      { id: "b", label: "B", text: "Less than 75% of the meal (or per facility policy)" },
      { id: "c", label: "C", text: "Any amount different from yesterday" },
      { id: "d", label: "D", text: "Only zero percent, when nothing is eaten" },
    ],
    correctChoiceId: "b",
    rationale: "Most facilities require reporting when a resident eats less than 75% of their meal. Poor intake can indicate illness, depression, or swallowing problems.",
    memoryTip: "Report food intake less than 75% (or per policy).",
    difficulty: 2,
  },
  {
    id: "fah-020",
    domainSlug: "function-and-health",
    domainTitle: "Function and Health of the Resident",
    type: "scenario",
    prompt: "A resident tells the nurse aide they are having trouble sleeping. The aide should:",
    choices: [
      { id: "a", label: "A", text: "Suggest the resident take an over-the-counter sleep aid" },
      { id: "b", label: "B", text: "Report the concern to the nurse and note comfort measures used" },
      { id: "c", label: "C", text: "Ignore it since minor sleep problems are normal in nursing homes" },
      { id: "d", label: "D", text: "Tell the resident to exercise more during the day" },
    ],
    correctChoiceId: "b",
    rationale: "Sleep disturbance is significant and should be reported to the nurse. The aide can support comfort measures (quiet environment, comfortable positioning) while the nurse investigates.",
    memoryTip: "Sleep problems: report to nurse, support comfort.",
    difficulty: 2,
  },
];

// ─── IV. Basic Nursing Care Provided by the Nurse Aide (26%) ──────────────────
// Covers: observation and reporting of physical and behavioral changes,
// acute emergency situations

const basicNursingCareBank: ExamQuestion[] = [
  {
    id: "bnc-001",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "Normal adult oral temperature is approximately:",
    choices: [
      { id: "a", label: "A", text: "96.0°F (35.6°C)" },
      { id: "b", label: "B", text: "98.6°F (37°C)" },
      { id: "c", label: "C", text: "100.4°F (38°C)" },
      { id: "d", label: "D", text: "101.0°F (38.3°C)" },
    ],
    correctChoiceId: "b",
    rationale: "Normal oral temperature is 98.6°F (37°C). Temperatures above 100.4°F are generally considered a fever in adults.",
    memoryTip: "Normal oral temp = 98.6°F (37°C).",
    difficulty: 1,
  },
  {
    id: "bnc-002",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "Normal adult resting pulse rate is:",
    choices: [
      { id: "a", label: "A", text: "40–59 beats per minute" },
      { id: "b", label: "B", text: "60–100 beats per minute" },
      { id: "c", label: "C", text: "101–120 beats per minute" },
      { id: "d", label: "D", text: "120–160 beats per minute" },
    ],
    correctChoiceId: "b",
    rationale: "The normal adult resting heart rate is 60–100 beats per minute. A rate below 60 is bradycardia; above 100 is tachycardia — both should be reported.",
    memoryTip: "Normal adult pulse = 60–100 BPM.",
    difficulty: 1,
  },
  {
    id: "bnc-003",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "Normal adult respiratory rate is:",
    choices: [
      { id: "a", label: "A", text: "8–10 breaths per minute" },
      { id: "b", label: "B", text: "12–20 breaths per minute" },
      { id: "c", label: "C", text: "22–30 breaths per minute" },
      { id: "d", label: "D", text: "30–40 breaths per minute" },
    ],
    correctChoiceId: "b",
    rationale: "Normal adult respirations are 12–20 per minute. Fewer than 12 or more than 20 are abnormal and should be reported to the nurse.",
    memoryTip: "Normal respirations = 12–20/min.",
    difficulty: 1,
  },
  {
    id: "bnc-004",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "Normal adult blood pressure is approximately:",
    choices: [
      { id: "a", label: "A", text: "80/50 mmHg" },
      { id: "b", label: "B", text: "120/80 mmHg" },
      { id: "c", label: "C", text: "160/100 mmHg" },
      { id: "d", label: "D", text: "140/90 mmHg" },
    ],
    correctChoiceId: "b",
    rationale: "The American Heart Association considers less than 120/80 mmHg as normal blood pressure. Readings above 130/80 are considered elevated or hypertensive.",
    memoryTip: "Normal BP = 120/80 mmHg.",
    difficulty: 1,
  },
  {
    id: "bnc-005",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "Apical pulse is measured by:",
    choices: [
      { id: "a", label: "A", text: "Pressing two fingers on the wrist" },
      { id: "b", label: "B", text: "Listening to the heart with a stethoscope at the apex of the heart" },
      { id: "c", label: "C", text: "Pressing two fingers on the inside of the elbow" },
      { id: "d", label: "D", text: "Using a pulse oximeter on the finger" },
    ],
    correctChoiceId: "b",
    rationale: "Apical pulse is auscultated with a stethoscope placed at the apex of the heart (4th to 5th intercostal space, left of the sternum) and counted for one full minute.",
    memoryTip: "Apical pulse = stethoscope at heart apex.",
    difficulty: 2,
  },
  {
    id: "bnc-006",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "scenario",
    prompt: "A resident suddenly grabs their chest and says, 'My chest hurts.' The nurse aide should immediately:",
    choices: [
      { id: "a", label: "A", text: "Get the resident a glass of water and sit with them" },
      { id: "b", label: "B", text: "Have the resident do deep breathing exercises" },
      { id: "c", label: "C", text: "Call for the nurse immediately and stay with the resident" },
      { id: "d", label: "D", text: "Help the resident walk to the nurse's station" },
    ],
    correctChoiceId: "c",
    rationale: "Chest pain is a potential cardiac emergency. The aide must call the nurse immediately, stay with the resident, keep them still and calm, and be prepared to initiate emergency procedures.",
    memoryTip: "Chest pain: call nurse NOW, stay with resident.",
    difficulty: 1,
  },
  {
    id: "bnc-007",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "Signs of a possible stroke include:",
    choices: [
      { id: "a", label: "A", text: "Slow onset of joint stiffness and fatigue" },
      { id: "b", label: "B", text: "Sudden facial drooping, arm weakness, and speech difficulty" },
      { id: "c", label: "C", text: "Gradual confusion over several weeks" },
      { id: "d", label: "D", text: "Increased appetite and elevated energy levels" },
    ],
    correctChoiceId: "b",
    rationale: "The FAST mnemonic: Face drooping, Arm weakness, Speech difficulty, Time to call 911. These are sudden warning signs of stroke requiring immediate emergency response.",
    memoryTip: "Stroke: FAST — Face, Arm, Speech, Time (call 911).",
    difficulty: 1,
  },
  {
    id: "bnc-008",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "If a resident begins to have a seizure, the nurse aide should:",
    choices: [
      { id: "a", label: "A", text: "Hold the resident down to prevent movement" },
      { id: "b", label: "B", text: "Insert a finger or object into the resident's mouth to prevent biting" },
      { id: "c", label: "C", text: "Clear the area of hazards, time the seizure, and call for help" },
      { id: "d", label: "D", text: "Shake the resident to try to stop the seizure" },
    ],
    correctChoiceId: "c",
    rationale: "During a seizure: clear hazards, do not restrain, do not put anything in the mouth, time the seizure, turn the resident on their side after, and call for help immediately.",
    memoryTip: "Seizure: clear area, time it, call for help, never restrain.",
    difficulty: 2,
  },
  {
    id: "bnc-009",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "A resident is choking and cannot speak, cough, or breathe. The nurse aide should:",
    choices: [
      { id: "a", label: "A", text: "Give the resident water to help clear the obstruction" },
      { id: "b", label: "B", text: "Perform abdominal thrusts (Heimlich maneuver) and call for help" },
      { id: "c", label: "C", text: "Have the resident lie down and breathe slowly" },
      { id: "d", label: "D", text: "Gently pat the resident on the back once" },
    ],
    correctChoiceId: "b",
    rationale: "A silent choking victim with no breath or speech has a complete airway obstruction. Abdominal thrusts (Heimlich) are the appropriate response. Call for help simultaneously.",
    memoryTip: "Complete obstruction = Heimlich + call for help.",
    difficulty: 1,
  },
  {
    id: "bnc-010",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "The nurse aide should report changes in a resident's mental status such as:",
    choices: [
      { id: "a", label: "A", text: "The resident choosing a different meal preference" },
      { id: "b", label: "B", text: "Sudden onset of confusion, agitation, or disorientation" },
      { id: "c", label: "C", text: "The resident taking longer than usual to answer questions" },
      { id: "d", label: "D", text: "Normal sadness after a difficult phone call" },
    ],
    correctChoiceId: "b",
    rationale: "Sudden changes in mental status — especially new confusion, agitation, or disorientation — can signal a UTI, medication reaction, or stroke. These must be reported immediately.",
    memoryTip: "Sudden confusion = report immediately.",
    difficulty: 2,
  },
  {
    id: "bnc-011",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "Objective observations by the nurse aide are based on:",
    choices: [
      { id: "a", label: "A", text: "The aide's feelings about the resident's condition" },
      { id: "b", label: "B", text: "Information measured or directly observed using the senses" },
      { id: "c", label: "C", text: "What the resident or family members report" },
      { id: "d", label: "D", text: "The aide's past experience with similar situations" },
    ],
    correctChoiceId: "b",
    rationale: "Objective data is measurable and directly observed: vital signs, skin color, edema, wounds. Subjective data is what the resident reports. Both belong in documentation.",
    memoryTip: "Objective = what you measure or see. Subjective = what resident says.",
    difficulty: 2,
  },
  {
    id: "bnc-012",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "scenario",
    prompt: "A nurse aide enters a room and finds a resident unresponsive and not breathing. The aide should:",
    choices: [
      { id: "a", label: "A", text: "Wait to confirm no breathing for 5 minutes" },
      { id: "b", label: "B", text: "Call for help immediately and begin CPR if trained and instructed to do so" },
      { id: "c", label: "C", text: "Attempt to move the resident to a better location first" },
      { id: "d", label: "D", text: "Check the resident's medication list first" },
    ],
    correctChoiceId: "b",
    rationale: "An unresponsive, non-breathing resident is a cardiac arrest emergency. Call for help and activate the emergency response immediately; begin CPR per facility policy if trained.",
    memoryTip: "Unresponsive + not breathing = call help, begin CPR.",
    difficulty: 1,
  },
  {
    id: "bnc-013",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "Signs of a hypoglycemic (low blood sugar) emergency in a diabetic resident include:",
    choices: [
      { id: "a", label: "A", text: "Extreme thirst, frequent urination, and fatigue" },
      { id: "b", label: "B", text: "Shakiness, sweating, confusion, and pale skin" },
      { id: "c", label: "C", text: "Slow breathing and decreased heart rate" },
      { id: "d", label: "D", text: "High fever and joint swelling" },
    ],
    correctChoiceId: "b",
    rationale: "Hypoglycemia causes shakiness, diaphoresis (sweating), confusion, pale skin, and rapid heartbeat. It requires prompt treatment — the nurse must be called immediately.",
    memoryTip: "Hypoglycemia: shaky, sweaty, confused, pale.",
    difficulty: 2,
  },
  {
    id: "bnc-014",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "When a resident falls and cannot get up, the nurse aide should:",
    choices: [
      { id: "a", label: "A", text: "Immediately help the resident stand without checking for injury" },
      { id: "b", label: "B", text: "Call for help, stay with the resident, and not move them until assessed" },
      { id: "c", label: "C", text: "Leave to get help and return when the nurse is available" },
      { id: "d", label: "D", text: "Help the resident up and document later" },
    ],
    correctChoiceId: "b",
    rationale: "After a fall, the aide stays with the resident, calls for help, and does not move the resident until a nurse assesses for injury. Moving without assessment can worsen hidden injuries.",
    memoryTip: "Post-fall: stay, call help, don't move until assessed.",
    difficulty: 1,
  },
  {
    id: "bnc-015",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "Reality orientation techniques are used with residents who experience:",
    choices: [
      { id: "a", label: "A", text: "Physical pain from arthritis" },
      { id: "b", label: "B", text: "Confusion or disorientation due to dementia or acute illness" },
      { id: "c", label: "C", text: "Depression caused by isolation" },
      { id: "d", label: "D", text: "Difficulty swallowing" },
    ],
    correctChoiceId: "b",
    rationale: "Reality orientation uses cues (time, date, place, name) to gently remind a confused resident of current reality. It is used for mild-to-moderate confusion from dementia or acute illness.",
    memoryTip: "Reality orientation = gentle reminders for confused residents.",
    difficulty: 2,
  },
  {
    id: "bnc-016",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "When a resident is vomiting, the nurse aide should first:",
    choices: [
      { id: "a", label: "A", text: "Lay the resident flat on their back" },
      { id: "b", label: "B", text: "Position the resident on their side or sitting up to prevent aspiration" },
      { id: "c", label: "C", text: "Give the resident water to clear the throat" },
      { id: "d", label: "D", text: "Document the vomiting and continue other tasks" },
    ],
    correctChoiceId: "b",
    rationale: "Positioning the resident on their side or sitting up prevents aspiration of vomit into the lungs. The aide should also call the nurse and document amount, color, and appearance.",
    memoryTip: "Vomiting: side or sitting position first — prevent aspiration.",
    difficulty: 1,
  },
  {
    id: "bnc-017",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "Defense mechanisms such as denial, withdrawal, or projection are:",
    choices: [
      { id: "a", label: "A", text: "Signs of psychotic disorder that need medication" },
      { id: "b", label: "B", text: "Normal psychological responses that protect a person from anxiety" },
      { id: "c", label: "C", text: "Evidence of abuse or neglect by the facility" },
      { id: "d", label: "D", text: "Ways residents manipulate staff to get better care" },
    ],
    correctChoiceId: "b",
    rationale: "Defense mechanisms are unconscious psychological responses that protect people from distressing feelings. Understanding them helps the aide respond with patience rather than frustration.",
    memoryTip: "Defense mechanisms = normal anxiety protection, not manipulation.",
    difficulty: 3,
  },
  {
    id: "bnc-018",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "A resident's skin integrity should be assessed by the nurse aide during:",
    choices: [
      { id: "a", label: "A", text: "Weekly baths only" },
      { id: "b", label: "B", text: "Daily care activities such as bathing, dressing, and repositioning" },
      { id: "c", label: "C", text: "Only after a fall or injury" },
      { id: "d", label: "D", text: "Skin assessments are the nurse's responsibility only" },
    ],
    correctChoiceId: "b",
    rationale: "The aide observes skin condition continuously during daily care — bathing, repositioning, dressing — and reports any redness, breakdown, or changes to the nurse.",
    memoryTip: "Skin check: every care interaction, not just baths.",
    difficulty: 2,
  },
  {
    id: "bnc-019",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "knowledge",
    prompt: "A resident experiencing respiratory distress shows which sign?",
    choices: [
      { id: "a", label: "A", text: "Slow, deep, regular respirations" },
      { id: "b", label: "B", text: "Pink, warm skin" },
      { id: "c", label: "C", text: "Labored, noisy breathing and use of accessory muscles to breathe" },
      { id: "d", label: "D", text: "Normal speaking pattern and calm demeanor" },
    ],
    correctChoiceId: "c",
    rationale: "Respiratory distress signs include labored breathing, noisy respirations, use of neck and chest muscles, sitting upright to breathe, nasal flaring, and cyanosis (bluish color).",
    memoryTip: "Respiratory distress: labored, noisy, uses extra muscles.",
    difficulty: 2,
  },
  {
    id: "bnc-020",
    domainSlug: "basic-nursing-care",
    domainTitle: "Basic Nursing Care Provided by the Nurse Aide",
    type: "scenario",
    prompt: "A resident reports significant rectal bleeding. The nurse aide should:",
    choices: [
      { id: "a", label: "A", text: "Assist the resident to clean up and chart at the end of the shift" },
      { id: "b", label: "B", text: "Apply pressure to the rectal area and monitor for 30 minutes" },
      { id: "c", label: "C", text: "Report the bleeding to the nurse immediately" },
      { id: "d", label: "D", text: "Ask the resident if they have a history of bleeding before reporting" },
    ],
    correctChoiceId: "c",
    rationale: "Rectal bleeding is abnormal and potentially serious. Immediate reporting allows the nurse to assess severity, determine cause, and initiate appropriate intervention.",
    memoryTip: "Bleeding: report immediately, don't wait.",
    difficulty: 1,
  },
];

// ─── V. Providing Specialized Care for Residents with Changes in Health (14%) ─
// Covers: physical problems (sensory, speech, mobility impairments), cognitive
// impairment, emotional/mental health, restorative care, end-of-life care

const specializedCareBank: ExamQuestion[] = [
  {
    id: "sc-001",
    domainSlug: "specialized-care",
    domainTitle: "Specialized Care for Residents with Changes in Health",
    type: "knowledge",
    prompt: "When communicating with a resident who has a hearing impairment, the nurse aide should:",
    choices: [
      { id: "a", label: "A", text: "Shout loudly to make sure the resident can hear" },
      { id: "b", label: "B", text: "Face the resident directly, speak clearly and at normal volume, and reduce background noise" },
      { id: "c", label: "C", text: "Write all communication, never speaking" },
      { id: "d", label: "D", text: "Ask family members to handle all communication" },
    ],
    correctChoiceId: "b",
    rationale: "For hearing-impaired residents: face them, speak clearly (not louder), reduce background noise, and ensure hearing aids are in place. Shouting distorts sounds and is not helpful.",
    memoryTip: "Hearing impaired: face them, clear speech, reduce noise.",
    difficulty: 1,
  },
  {
    id: "sc-002",
    domainSlug: "specialized-care",
    domainTitle: "Specialized Care for Residents with Changes in Health",
    type: "knowledge",
    prompt: "A resident with aphasia (difficulty speaking) should be approached by the nurse aide with:",
    choices: [
      { id: "a", label: "A", text: "Rapid speech to model faster communication" },
      { id: "b", label: "B", text: "Patience, simple questions, and adequate time to respond" },
      { id: "c", label: "C", text: "Complete silence to avoid frustrating the resident" },
      { id: "d", label: "D", text: "Communication only through written notes" },
    ],
    correctChoiceId: "b",
    rationale: "Aphasia affects speech production or comprehension. The aide should be patient, ask yes/no questions, allow extra response time, and use picture boards if helpful.",
    memoryTip: "Aphasia: patience, simple questions, time to respond.",
    difficulty: 2,
  },
  {
    id: "sc-003",
    domainSlug: "specialized-care",
    domainTitle: "Specialized Care for Residents with Changes in Health",
    type: "knowledge",
    prompt: "Alzheimer's disease is a type of dementia characterized by:",
    choices: [
      { id: "a", label: "A", text: "Sudden onset with complete recovery expected" },
      { id: "b", label: "B", text: "Progressive, irreversible cognitive decline affecting memory and function" },
      { id: "c", label: "C", text: "Cognitive changes caused by medication side effects only" },
      { id: "d", label: "D", text: "Primarily mood and personality changes without memory loss" },
    ],
    correctChoiceId: "b",
    rationale: "Alzheimer's disease is the most common form of dementia. It is progressive and irreversible, with gradual loss of memory, language, problem-solving, and eventually basic function.",
    memoryTip: "Alzheimer's: progressive, irreversible cognitive decline.",
    difficulty: 1,
  },
  {
    id: "sc-004",
    domainSlug: "specialized-care",
    domainTitle: "Specialized Care for Residents with Changes in Health",
    type: "knowledge",
    prompt: "When a resident with dementia becomes agitated and combative during care, the nurse aide should:",
    choices: [
      { id: "a", label: "A", text: "Use force to complete the care quickly" },
      { id: "b", label: "B", text: "Stop care, speak calmly, and try again later if safe to do so" },
      { id: "c", label: "C", text: "Ask another aide to hold the resident while care is completed" },
      { id: "d", label: "D", text: "Argue with the resident to resolve the misunderstanding" },
    ],
    correctChoiceId: "b",
    rationale: "Forcing care on a combative resident risks injury. A calm pause, reassuring words, and returning later — with a different approach or different aide — is the safest strategy.",
    memoryTip: "Combative dementia: pause, calm, try again later.",
    difficulty: 2,
  },
  {
    id: "sc-005",
    domainSlug: "specialized-care",
    domainTitle: "Specialized Care for Residents with Changes in Health",
    type: "knowledge",
    prompt: "Validation therapy is used with residents with dementia to:",
    choices: [
      { id: "a", label: "A", text: "Correct their false beliefs to restore reality" },
      { id: "b", label: "B", text: "Acknowledge and respect their feelings and subjective reality" },
      { id: "c", label: "C", text: "Test their cognitive function against a standard scale" },
      { id: "d", label: "D", text: "Verify that their personal information is still accurate" },
    ],
    correctChoiceId: "b",
    rationale: "Validation therapy focuses on the feelings behind a confused resident's statements rather than correcting factual errors. This approach reduces distress and builds connection.",
    memoryTip: "Validation: acknowledge feelings, don't correct reality.",
    difficulty: 3,
  },
  {
    id: "sc-006",
    domainSlug: "specialized-care",
    domainTitle: "Specialized Care for Residents with Changes in Health",
    type: "knowledge",
    prompt: "Restorative nursing care is focused on:",
    choices: [
      { id: "a", label: "A", text: "Keeping residents in bed to promote rest and healing" },
      { id: "b", label: "B", text: "Helping residents regain or maintain the highest possible level of function and independence" },
      { id: "c", label: "C", text: "Performing all care tasks for the resident to save time" },
      { id: "d", label: "D", text: "Reversing all effects of aging and illness" },
    ],
    correctChoiceId: "b",
    rationale: "Restorative nursing promotes independence through rehabilitative activities. The aide encourages residents to do as much for themselves as safely possible.",
    memoryTip: "Restorative = maximize independence and function.",
    difficulty: 1,
  },
  {
    id: "sc-007",
    domainSlug: "specialized-care",
    domainTitle: "Specialized Care for Residents with Changes in Health",
    type: "knowledge",
    prompt: "The nurse aide can best support a resident experiencing depression by:",
    choices: [
      { id: "a", label: "A", text: "Telling the resident to cheer up and think positively" },
      { id: "b", label: "B", text: "Listening empathetically, spending time with the resident, and reporting concerns to the nurse" },
      { id: "c", label: "C", text: "Leaving the resident alone to process their feelings" },
      { id: "d", label: "D", text: "Suggesting the resident call family to solve the problem" },
    ],
    correctChoiceId: "b",
    rationale: "The aide supports depressed residents with presence, active listening, empathy, and reporting mood changes to the nurse. Dismissing feelings or false reassurance is unhelpful.",
    memoryTip: "Depression: listen, be present, report to nurse.",
    difficulty: 2,
  },
  {
    id: "sc-008",
    domainSlug: "specialized-care",
    domainTitle: "Specialized Care for Residents with Changes in Health",
    type: "knowledge",
    prompt: "Hospice care focuses on:",
    choices: [
      { id: "a", label: "A", text: "Curing the terminal illness with aggressive treatment" },
      { id: "b", label: "B", text: "Comfort, dignity, and quality of life for residents near end of life" },
      { id: "c", label: "C", text: "Preparing the resident for transfer to an acute hospital" },
      { id: "d", label: "D", text: "Physical therapy to maintain strength during the final weeks" },
    ],
    correctChoiceId: "b",
    rationale: "Hospice is palliative care for people near end of life. The focus is comfort, pain management, dignity, and supporting both the resident and family — not curative treatment.",
    memoryTip: "Hospice = comfort and dignity, not cure.",
    difficulty: 1,
  },
  {
    id: "sc-009",
    domainSlug: "specialized-care",
    domainTitle: "Specialized Care for Residents with Changes in Health",
    type: "knowledge",
    prompt: "When caring for a resident with a visual impairment, the nurse aide should:",
    choices: [
      { id: "a", label: "A", text: "Rearrange the room so objects are in more logical locations" },
      { id: "b", label: "B", text: "Keep the room consistently arranged and announce yourself when entering" },
      { id: "c", label: "C", text: "Move quickly through care tasks so the resident doesn't feel anxious" },
      { id: "d", label: "D", text: "Avoid speaking during care to prevent confusion" },
    ],
    correctChoiceId: "b",
    rationale: "Visually impaired residents rely on consistent room arrangement for orientation and safety. The aide should always announce themselves on entering, describe actions, and avoid moving belongings without notice.",
    memoryTip: "Visual impaired: consistent room, announce yourself.",
    difficulty: 2,
  },
  {
    id: "sc-010",
    domainSlug: "specialized-care",
    domainTitle: "Specialized Care for Residents with Changes in Health",
    type: "knowledge",
    prompt: "A contracture is prevented through:",
    choices: [
      { id: "a", label: "A", text: "Bed rest and minimal movement" },
      { id: "b", label: "B", text: "Regular range of motion exercises and proper positioning" },
      { id: "c", label: "C", text: "Strong pain medication to allow more movement" },
      { id: "d", label: "D", text: "Keeping affected limbs in a flexed position at all times" },
    ],
    correctChoiceId: "b",
    rationale: "Contractures are prevented through frequent ROM exercises and proper body alignment. Keeping a joint in a fixed position without movement promotes shortening.",
    memoryTip: "Contracture prevention: ROM + correct positioning.",
    difficulty: 1,
  },
  {
    id: "sc-011",
    domainSlug: "specialized-care",
    domainTitle: "Specialized Care for Residents with Changes in Health",
    type: "knowledge",
    prompt: "Kübler-Ross identified five stages of grief that a terminally ill resident may experience. Which of the following is NOT one of those stages?",
    choices: [
      { id: "a", label: "A", text: "Denial" },
      { id: "b", label: "B", text: "Bargaining" },
      { id: "c", label: "C", text: "Confusion" },
      { id: "d", label: "D", text: "Acceptance" },
    ],
    correctChoiceId: "c",
    rationale: "Kübler-Ross's five stages are: Denial, Anger, Bargaining, Depression, and Acceptance. Confusion is not one of them. Residents may move between stages in any order.",
    memoryTip: "Grief stages: Denial, Anger, Bargaining, Depression, Acceptance.",
    difficulty: 2,
  },
  {
    id: "sc-012",
    domainSlug: "specialized-care",
    domainTitle: "Specialized Care for Residents with Changes in Health",
    type: "scenario",
    prompt: "A resident with paralysis on the left side needs to be dressed. The aide should:",
    choices: [
      { id: "a", label: "A", text: "Dress the strong (right) side first to keep it comfortable" },
      { id: "b", label: "B", text: "Dress the weak (left) side first so it does not have to be forced through clothing" },
      { id: "c", label: "C", text: "Dress both sides simultaneously to save time" },
      { id: "d", label: "D", text: "Place the garment over the resident's head before inserting any arms" },
    ],
    correctChoiceId: "b",
    rationale: "The rule for dressing with a weak or affected side: dress the weak side first (it needs more space in the garment), undress the strong side first. Weak in first, strong out first.",
    memoryTip: "Weak side: dress first, undress last.",
    difficulty: 1,
  },
  {
    id: "sc-013",
    domainSlug: "specialized-care",
    domainTitle: "Specialized Care for Residents with Changes in Health",
    type: "knowledge",
    prompt: "A prosthetic device (artificial limb) should be:",
    choices: [
      { id: "a", label: "A", text: "Removed and stored permanently when the resident is in bed" },
      { id: "b", label: "B", text: "Cared for per the care plan and resident's preferences" },
      { id: "c", label: "C", text: "Cleaned only by the physical therapist" },
      { id: "d", label: "D", text: "Removed during all care activities to prevent damage" },
    ],
    correctChoiceId: "b",
    rationale: "Prosthetic devices require specialized care per the care plan and the resident's preference. The aide should follow facility-specific instructions for application, removal, and cleaning.",
    memoryTip: "Prosthetics: follow care plan and resident preference.",
    difficulty: 2,
  },
  {
    id: "sc-014",
    domainSlug: "specialized-care",
    domainTitle: "Specialized Care for Residents with Changes in Health",
    type: "knowledge",
    prompt: "Signs that a resident is approaching end of life include:",
    choices: [
      { id: "a", label: "A", text: "Increased appetite and higher energy" },
      { id: "b", label: "B", text: "Mottling of skin, decreased urine output, and irregular respirations" },
      { id: "c", label: "C", text: "Higher blood pressure and increased alertness" },
      { id: "d", label: "D", text: "Frequent requests for food and large amounts of urine output" },
    ],
    correctChoiceId: "b",
    rationale: "End-of-life signs include mottling (patchy skin discoloration), decreased or no urine output, Cheyne-Stokes respirations (irregular), coolness of extremities, and decreased consciousness.",
    memoryTip: "End of life: mottling, decreased urine, irregular breathing.",
    difficulty: 3,
  },
  {
    id: "sc-015",
    domainSlug: "specialized-care",
    domainTitle: "Specialized Care for Residents with Changes in Health",
    type: "knowledge",
    prompt: "A resident with a contracture of the hand should have the hand positioned:",
    choices: [
      { id: "a", label: "A", text: "In a tight fist to prevent further contracture" },
      { id: "b", label: "B", text: "In a functional position, supported with a splint or rolled washcloth per the care plan" },
      { id: "c", label: "C", text: "Fully extended with fingers spread as wide as possible" },
      { id: "d", label: "D", text: "Secured to the bed rail for stability" },
    ],
    correctChoiceId: "b",
    rationale: "A functional position (slight wrist extension, fingers gently curved) with appropriate support prevents worsening of the contracture and reduces discomfort.",
    memoryTip: "Contracted hand: functional position + support per care plan.",
    difficulty: 3,
  },
];

// ─── Export ────────────────────────────────────────────────────────────────────

export const officialWrittenBank: ExamQuestion[] = [
  ...roleOfNurseAideBank,
  ...promotionOfSafetyBank,
  ...functionAndHealthBank,
  ...basicNursingCareBank,
  ...specializedCareBank,
];
